#!/usr/bin/env python3
"""Create distinct, bounded public-data/original-code cloud questions."""
from pathlib import Path
import hashlib

ROOT = Path(__file__).resolve().parent / 'lanes'
ITEMS = [
('A907-PARITY', 'Implicit KKT derivative parity', 'Independently derive the derivative of a strongly convex equality constrained quadratic force solver with respect to geometry. Construct a seeded 2-body synthetic case with changing mass and wrench, compare implicit derivative with converged central finite differences at 5 step sizes, and give a cancellation/error budget. A907 reports 2.6e-8 on its private model, which is context only.', 'PASS if 20 of 20 seeded regular cases have relative error below 1e-4 at an identified stable step and all singular/active-set changes are flagged. Private A907 numerical parity remains UNKNOWN.'),
('A363-ALGO', 'Independent batched NNLS algorithm audit', 'Derive a batched projected active-set or block principal-pivot method for original synthetic NNLS, benchmark against SciPy NNLS on 1000 seeded systems at 4 conditioning levels, including rank defects. Report KKT, objective and CPU throughput scaling. A363 private GPU throughput is context only.', 'PASS if at least 990/1000 match reference objective within 1e-7 relative and scaled KKT <=1e-6; report any failures and timing separately.'),
('A295-EXACT', 'Exactness and numerical certificates', 'Construct an independent primal-dual certificate for small synthetic box-constrained quadratic programs with unequal scales. Compare solver answers with high-precision or interval residual bounds, distinguish equality of solutions from tolerance-induced agreement. A295 private force matrices are unavailable.', 'PASS if all 100 seeded well-conditioned cases have objective gap <=1e-8 and all seeded ill-conditioned uncertified cases are labeled UNKNOWN.'),
('A303-BOUND', 'Emulator error bounds at active-set switches', 'On original piecewise-smooth convex QP families, test one-sided derivative emulators against held-out exact solves near active-set boundaries. Compare global smooth and set-aware baseline; compute coverage by distance-to-switch strata. A303 reported 0.146% private-model max error, context only.', 'PASS if one-sided emulator max relative error <=3% on >=1000 held-out points and 90% intervals cover 85–95% in every preregistered switch stratum.'),
('A194-ARMS', 'Moment-arm geometry independent audit', 'Use only a checked public anatomy/model geometry with explicit license and source, or original synthetic paths if public geometry cannot be accessed. Compare moment arms from virtual work, force line, and finite differences under controlled f attachments and wraps. A194 private 0.39 versus 0.77 mm is context only.', 'PASS empirical only if public geometry and independent measured moment arms are versioned, matched by anatomical definition, and improvement holds in >=4 of 5 muscle groups; otherwise UNKNOWN. Synthetic method PASS if virtual-work error <0.1% away from switches.'),
('PATELLA-RANGE', 'Patella mechanics across operating range', 'Use public primary Krevolin 2004 DOI 10.1016/j.jbiomech.2003.09.010 abstract for its reported peak near 45 degrees, and any verifiably downloadable curves with their definitions. Build an original bounded planar countermodel and locate conditions for interior versus endpoint peaks. Do not claim the public abstract supplies digitized curves.', 'PASS mathematics if extrema and virtual-work derivatives agree within 1% on 0–120 degrees and sensitivity separates endpoint and interior peaks; empirical peak reproduction UNKNOWN without digitized matched curves.'),
('PATELLA-SWITCH', 'Patella contact and tendon routing transitions', 'Investigate non-smooth transition of patella contact in an original planar model. Compare complementarity, smoothed penalty and explicit mode switching; map force jumps and energy error on 0–120 degrees. Cite one checked primary reference if obtainable.', 'PASS if all transitions are detected and energy error <0.1% on converged meshes; anatomical validity UNKNOWN without matched measured curves.'),
('B1-MEASURE', 'Robust minimal measurement design', 'Revisit B1 after its previous synthetic OED robustness failure. Form a positive-definite prior family and correlated measurement bias, compare DXA, radiograph, landmarks and strength channels in an original 5-parameter toy model under two budgets. Use common random numbers and a strong all-measurements baseline.', 'PASS if selected design has >=80% survival across >=2000 prespecified prior/noise draws and 90% predictive interval coverage 85–95%; otherwise FAIL.'),
('B2-BONE', 'Bone density to local mechanics error budget', 'Use a checked public primary CT-density/mechanical-property relation if downloadable. In an original 1D/2D finite element toy bone, propagate calibration, partial-volume and segmentation uncertainty into stiffness; quantify how voxel size changes failure. Distinguish published calibration from assumed geometry.', 'PASS numerical if mesh refinement changes stiffness <2% and all uncertainty terms are independently varied; empirical prediction UNKNOWN absent matched test specimens.'),
('B3-CELL', 'Cell shape and diffusion-reaction identifiability', 'Use public Janelia CellMap/COSEM metadata only where actual download/version/voxel scale can be verified. Compare equal-volume sphere versus segmented organelle crop with diffusion-reaction finite volumes and boundary-truncation sensitivity. Prior cell-mesh crop touched its boundary.', 'PASS numerical if flux balance <1e-5 and refinement change <2%, and report crop-boundary contribution; biological calibration UNKNOWN without same-cell transport measurements.'),
('B4-STRENGTH', 'Muscle parameter identifiability from strength curves', 'Derive structural identifiability for capacity, moment-arm scale, optimum length, slack angle and activation from knee-angle strength curves. Show exact symmetries, Fisher rank and profile likelihood with strength-only and one extra measurement; original synthetic data only.', 'PASS if algebraic symmetry and numerical rank agree in all 6 frozen designs and held-out parameter coverage is reported for >=500 replicates.'),
('B5-DISC', 'L4/L5 disc pressure matched-level validation', 'Use Wilke et al. 1999 primary PDF https://fonar.com/pdf/spine_vol_24.No.8.pdf as source: one person, L4/L5, area 1800 mm2, 0.50 MPa relaxed standing and 1.10 MPa standing flexed. Create original equilibrium model; fit one posture and hold out the other. Propagate area and muscle-arm uncertainty explicitly.', 'PASS empirical only if held-out pressure is within a prespecified 20% without tuning on it; otherwise FAIL. Population generalization UNKNOWN.'),
('VASCULAR-TRANS', 'Vascular-interstitial transient inference', 'Construct original mass-conserving Starling-lymph two-compartment transient and compare plasma-only with plasma-plus-interstitial observation. Source a public primary transient only if matched variables and units exist. Previous synthetic Fisher rank failed 2/4 designs.', 'PASS if Fisher rank, profile likelihood and 90% interval coverage agree for all 4 prespecified designs with >=500 replicates; empirical validity UNKNOWN absent measured transient.'),
('TISSUE-VOXEL', 'Thin tissue layer transfer to mechanics', 'Original analytic slab-and-voxel model: show when total volume conservation hides a lost thin high-modulus layer. Compare per-material volume, first moments and effective bending stiffness at three resolutions. A194 material partition error is context only.', 'PASS if exact slab limit reproduced within 1% at finest grid and a total-volume-only false pass is detected by per-material checks.'),
('ORGAN-FE', 'Organ material mapping uncertainty', 'Use one checked public primary soft-tissue modulus source if accessible. Build a bounded original organ-shell finite-element or analytic membrane model; compare how geometry and modulus uncertainty affect displacement. Keep units, material regime and measured modality explicit.', 'PASS numerical if analytic limiting case <1% and convergence <2%; empirical calibration UNKNOWN without matched specimen geometry and loading.'),
('MUSCLE-CURVE', 'Muscle force-length-velocity confounding', 'Original muscle-tendon toy dynamics with excitation and tendon compliance. Determine whether static strength-angle plus one controlled velocity identifies optimal length, tendon slack and maximum force; show counterexamples and observation design.', 'PASS if structural rank and profile results agree in 5 seeded regimes and a held-out trajectory tests each fitted design.'),
('CONTACT-INV', 'Contact inference from measured kinematics', 'Coordinate by scope only with Field INVIVO-THEORY: study a single rigid body with known measured pose and unknown contact wrench, no duplicate whole-body field experiment. Derive minimum sensors and conditions for unique normal/tangential contact under friction cone. Give analytic counterexamples.', 'PASS mathematics if uniqueness conditions are proved or constructively falsified for 4 frozen observation sets and noisy uncertainty is quantified.'),
('CELL-ATP', 'ATP transport scaling in segmented cells', 'Use public CellMap crop only if metadata and label version verified; otherwise original synthetic ellipsoid. Bound ATP reaction-diffusion Damkohler regimes and test mesh/flux conservation. No membrane permeability claim from volume agreement alone.', 'PASS numerical if conservation <1e-5 and regime boundary agrees with analytic sphere within 5%; empirical ATP level UNKNOWN without matched measurement.'),
('JOINT-CART', 'Cartilage contact resolution and pressure', 'Original axisymmetric compliant-layer model with public primary cartilage thickness/source only if verified. Compare mesh refinement, contact penalty and layer thickness for force and peak pressure. Do not infer in vivo damage.', 'PASS numerical if force balance <0.1% and peak pressure converges <5% on 3 finest resolutions; tissue calibration UNKNOWN.'),
('NATO-LINK', 'Fatigue chain source attribution', 'Audit activity-to-load-to-strain-to-fatigue-to-risk chain using checked public primary sources. Separate directly measured relations, calibration transfers and unknown risk mapping; carry intervals with units and one reversal counterexample. Carter 1981 is a bone-fatigue source, not an injury-risk calibration.', 'PASS source audit if every numeric interval in final model has a checked exact source or is marked assumption, and no individual injury-risk number is emitted without a validated mapping.'),
('A359-FAIR', 'Strength prediction cohort transport', 'Use the bundled public NHANES CDC XPT archive, verified by MANIFEST.sha256, and the bundled baseline code a359.py. Do not change the frozen cohort or split. Compare A359 adjusted mass+height+sex+age baseline with DXA across sex and age cells; quantify eligibility and missingness. Do not alter holdout split after inspection.', 'PASS transport only if positive DXA gain has 95% lower bound >0 in every prespecified cell and calibration slope 0.8–1.2; else FAIL.'),
('SURROGATE-OOD', 'Surrogate abstention under geometry shift', 'Original synthetic geometry-to-force map with known active sets. Train on one geometry regime, test severe shift and compare conformal intervals with abstention certificate versus no abstention. State coverage assumptions.', 'PASS if retained 90% intervals have 85–95% coverage in every shift group and abstention rate is reported, with >=1000 held-out samples.'),
]

COMMON = ('Only public primary data or original synthetic code. Do not access private repositories, restricted model data, TLEM, the collaborator data, LHDL or internal A matrices. Do not use subagents, push, email, publish or enable paid usage. Cite sources actually checked, including exact URL/DOI and which value they support. Clearly distinguish synthetic method checks from empirical validation. If required public data are unavailable, report UNKNOWN and do not invent values. Deliver RESULTS.md, results.json and small runnable code, and print files in final message between =====FILE <path>===== and =====END FILE=====, total <=200 KB.')
for short, title, work, criterion in ITEMS:
    lane = 'CLOUD-W4-' + short
    directory = ROOT / lane
    directory.mkdir(parents=True, exist_ok=True)
    files = {
        'BRIEF.md': f'# {lane}: {title}\n\n{COMMON}\n\n## Bounded work\n{work}\n\nReport baseline, independent check, exact command, units, uncertainty, failure cases and limitations.\n',
        'PREREG.md': f'# PREREG {lane}\n\nQuestion: {title}.\n\nFrozen criterion: {criterion}\n\nNo post-hoc change to the criterion; record any exploratory correction separately.\n',
    }
    for name, content in files.items():
        path = directory / name
        if path.exists() and path.read_text() != content:
            raise RuntimeError(f'existing {path} differs')
        path.write_text(content)
    (directory / 'PREREG.sha256').write_text(hashlib.sha256(files['PREREG.md'].encode()).hexdigest() + '  PREREG.md\n')
    print(lane)
