#!/usr/bin/env python3
"""Prepare 15 bounded, public/own-code coordinator tasks for CX-CLOUDWAVE2."""
from pathlib import Path
import hashlib
import shutil

ROOT = Path(__file__).resolve().parent / 'lanes'
COMMON = '''Use only public data bundled here or downloaded from primary public sources and original code written for this lane. Do not open other repositories or use restricted model data, TLEM, the collaborator data, LHDL or internal A matrices. Prior register numbers below are unreviewed claims, not input observations. Distinguish proof, synthetic test, public empirical evidence, and UNKNOWN. Give exact commands, units, source URL/DOI, uncertainty and counterexamples. Do not invent unavailable data or references. No push, publishing, email, credentials or subagents. Final answer: print RESULTS.md, results.json and small code exactly between =====FILE <relative path>===== and =====END FILE===== markers (total <=200 KB).'''
# id: title, context, task, frozen decision
LANES = {
'CLOUD-W2-A359-MISSING': ('NHANES A359 selection and missingness audit', 'Wave 1 replicated a 13.1% mass-only improvement with public CDC 1999–2002 data, but the stronger adjusted baseline gained only 2.34%; original 19.1% did not reproduce. Eight CDC XPT files and hashes are bundled.', 'Using the bundled data, quantify age>=50 inclusion, DXA and strength missingness by age/sex/cycle; inverse-probability weighted sensitivity and pessimistic pattern-mixture bounds for the adjusted DXA increment. Keep train 1999–2000 and untouched 2001–02 holdout. Report force in N and assumed torque arm separately. Compare adjusted baseline and adjusted+DXA on identical rows.', 'PASS only if positive adjusted DXA improvement survives all prespecified complete-case/IPW and 10% missing-outcome shift scenarios and lower 95% paired PSU-bootstrap bound >0; otherwise FAIL or UNKNOWN.'),
'CLOUD-W2-A359-SURVEY': ('NHANES A359 survey-design robustness', 'Wave 1 adjusted DXA increment: 84.43 to 82.46 N, 2.34% holdout improvement; descriptive prediction among completers. Eight public CDC XPT files and hashes are bundled.', 'Independently implement weight-aware training and evaluation with NHANES strata/PSU and cycle weights. Avoid combining incompatible weights without stating assumption. Compare weighted and unweighted adjusted models, paired uncertainty by PSU, and sex/age strata. Audit coding, merge, imputation and leakage. Report exact estimands.', 'PASS if weighted adjusted DXA increment is positive in all five imputations and PSU 95% lower bound >0 on matched holdout subjects; else FAIL/UNKNOWN.'),
'CLOUD-W2-A367-GEOM': ('Patellar tendon arm: definitions and geometry counterexample', 'First wave found two public OpenSim model curves decrease from full extension; forced 30–60 degree peaks lost. A peak near 45 degrees is therefore not established.', 'Derive three non-equivalent definitions: tendon line-to-joint-center distance, virtual-work derivative of tendon length, and quadriceps effective arm. Make original planar geometry with moving instantaneous center and wrapping contact. Find when one definition peaks but another does not, with synthetic parameter sweep and signed angle conventions. Cite public OpenSim or primary anatomy source only where checked.', 'PASS as mathematical counterexample if numerical differentiation matches analytic virtual-work derivative to <=1e-4 relative away from singularities and at least one prespecified geometry yields differing peak bins; empirical peak status UNKNOWN absent public measured coordinates.'),
'CLOUD-W2-A369-KKT': ('Independent active-set derivative audit for what-if curves', 'A369 reports 195/216 accepted points, 21 gaps, a frozen-active-set KKT tangent agreeing at one peak; patient matrices cannot be bundled. Treat this only as a numerical claim to stress-test.', 'Build original small parametric nonnegative quadratic recruitment model. Derive implicit derivative of KKT system on a fixed active set, compare to central differences, map active-set switch points and peak-envelope nondifferentiability. Design a certifier that rejects tangent use near switching and unfilled grid gaps. No internal A matrices or case data.', 'PASS if analytic and finite-difference derivatives agree <0.1% at >=20 well-conditioned interior test points, and certifier rejects every constructed switch/gap counterexample; actual A369 patient claim remains UNKNOWN.'),
'CLOUD-W2-A363-BATCH': ('Independent A363 batched NNLS algorithm audit', 'A363 register claims a batched GPU solver around 499 steps/s at 1000 individuals with agreement ~5.8e-9. No internal systems or matrices are allowed.', 'Implement original batched nonnegative convex quadratic/NNLS solver and scalar reference on synthetic positive, correlated, rank-deficient and changing-active-set systems. Report primal/dual KKT residual, objective gap, timing with hardware and scaling; include warm-start and failure cases. Use public NumPy/SciPy only or explain alternatives.', 'PASS if >=99% of >=100 seeded cases meet relative objective gap <=1e-7 and scaled KKT <=1e-6 against independent SciPy reference, with honest timing; A363 specific throughput is UNKNOWN.'),
'CLOUD-W2-PATELLA': ('Patella wrapping and tendon-routing mechanism', 'Wave 1 A367 monotonically falling public OpenSim tendon arms contradicted the proposed universal 45-degree peak. The BT-2 mechanism needs an explicit geometric reason for curve shape.', 'Derive a minimal two-dimensional patella pulley/wrap model with tendon and quadriceps attachment, contact constraints, equilibrium and virtual-work knee moment arm. Compare no-patella, fixed pulley and moving patella; sweep geometry and identify peak conditions. Use public anatomy/model DOI if obtainable; no fabricated measured coordinates.', 'PASS for mechanical derivation if energy/virtual-work and direct moment balances agree within 1e-4 in >=90% of valid synthetic grid and contact transitions are flagged; empirical angle of maximum UNKNOWN unless measured data obtained.'),
'CLOUD-W2-OPRANGE': ('Operating-range identifiability of strength curves', 'Wave 1 B4 found structural capacity/moment-arm/force-length confounding. The decision is which measurement angles and operating range can separate them.', 'Derive local and global identifiability for capacity, force-length optimum/width and moment-arm shape under a single isometric curve. Simulate 2/3/5/7 angle designs and realistic bounded noise scenarios; evaluate profile likelihood and held-out angles. Add an independent imaging/DXA prior as distinct observation, never as ground truth.', 'PASS if a chosen <=5-angle design has full numerical rank and <=20% relative parameter error in >=80% of held-out synthetic subjects under stated assumptions, and profile likelihood catches a constructed nonidentifiable case; public empirical validity UNKNOWN.'),
'CLOUD-W2-B1-ROBUST': ('Robust minimal personal measurement protocol', 'Wave 1 B1 OED returned synthetic recommendations but failed its robustness criterion. Register claims 5 X-ray measures improve femur fit; no patient Jacobians are available.', 'Build a robust minimax or Bayes OED with explicit costs, correlated errors and separate geometry/strength target variances. Compare against wave-1 equal-cost greedy and one-modality baselines. Sweep plausible noise and Jacobian correlations with transparent synthetic assumptions; find a short conditional decision tree.', 'PASS only if the recommended first measurement is unchanged in >=80% of preregistered scenarios AND target variance beats both baselines at equal budget in >=80%; else FAIL. Never claim patient-level optimality.'),
'CLOUD-W2-B5-LEVEL': ('Disc-pressure load transfer and level mismatch', 'Wave 1 B5 could not verify Wilke primary values and mistakenly treated L4/L5 values as potential L5/S1 validation. Pressure is not simply mean axial stress.', 'Using verified public primary sources if accessible, distinguish L4/L5 from L5/S1, nucleus pressure from average disc compression, and level-specific area. Derive minimal posture equilibrium and dimensioned uncertainty intervals. If sources blocked, give a symbolic bound and explicit data requirements; write reproducible calculations.', 'PASS only if two postures have same-level primary pressure observations and independent area/lever-arm inputs and beat axial-body-weight baseline without posture fitting; otherwise UNKNOWN.'),
'CLOUD-W2-NATO-FATIGUE': ('NATO activity-to-bone-fatigue chain with source-backed ranges', 'Wave 1 produced dimensioned synthetic chain but all parameter ranges unverified, and injury risk could not be derived from fatigue damage.', 'Find primary public bone fatigue epsilon-N data or explicitly state access failure. Reconstruct a unit-aware cycle/strain/damage model, quantify linkwise uncertainty and sequence/remodeling sensitivity. Construct ranking reversal and bound it; keep injury-risk map separate and UNKNOWN absent epidemiology.', 'PASS only if all numerical parameter ranges have directly checked primary source tables/figures plus units, a reproducible sensitivity decomposition, and >=1 source-supported ranking reversal; else FAIL/UNKNOWN.'),
'CLOUD-W2-CELL-GEOM': ('Measured 3D cell geometry: segmentation-to-mesh conservation', 'Roadmap says no verified measured cell volume -> organelle segmentation -> mesh -> spatial physiology chain; OpenOrganelle and Allen are candidates, not local validation.', 'Choose one public small segmented cell or organelle subvolume with version/voxel size and label meaning; if download blocked, use an explicitly synthetic labeled volume. Implement topology/volume/surface/scale checks, mesh or finite-volume conversion and uncertainty under 1-voxel erosion/dilation. Distinguish prediction from measurement.', 'PASS for data-linked pipeline only if public volume and labels are verified, physical-volume error <=1% after conversion and scale/label provenance retained; synthetic-only is PARTIAL/UNKNOWN.'),
'CLOUD-W2-CELL-TRANSPORT': ('Organelle geometry versus transport observable', 'Roadmap notes a prior cristae-to-respirometry mismatch in biological system, so structure-function calibration is open.', 'With an original diffusion-reaction toy model and public geometry/transport reference if accessible, compare equal-volume geometries with different surface area and separation. Report dimensionless groups, numerical convergence, and a measurable flux or concentration response. Identify which parameter combinations remain unidentifiable without matched functional data.', 'PASS mathematical test if mass balance <1e-6 and mesh convergence <2% for the chosen observable, plus a clear geometry-dependent counterexample; empirical structure-function validation UNKNOWN without matched data.'),
'CLOUD-W2-VASCULAR-ID': ('Vascular-interstitial transient identifiability follow-up', 'Wave 1 vascular model conserved mass but had no quantitative public transient. It included assumed Starling/lymph parameters.', 'Use original mass-conserving two-compartment equations; derive identifiable combinations from plasma dilution alone versus plasma plus interstitial observations. Implement profile likelihood/Fisher rank on synthetic time courses and identify minimum sampling schedule. Seek a public transient, but mark empirical status UNKNOWN if inaccessible.', 'PASS mathematical criterion if volume/solute balance <1e-8 and rank predictions match simulated profile likelihood in >=3 designs; empirical pass requires a checked public transient.'),
'CLOUD-W2-N1G-PLACEBO': ('Shared-constraint placebo calibration', 'Wave 1 N1g audit proved rank-one information collapse under assumptions but did not verify the actual matrices or N_eff.', 'Construct original correlated-constraint simulation with shared and individual Jacobians. Compare posterior intervals, placebo constraints and held-out calibration under misspecified independence. Explain rank versus effective sample size and derive measurable geometry needed to gain rank.', 'PASS if nominal 90% intervals cover 85-95% on >=1000 seeded test cases for correct covariance and naive-independent version visibly miscalibrates under high correlation; actual N1g status UNKNOWN.'),
'CLOUD-W2-B4-DESIGN': ('Joint DXA and multiangle strength experimental design', 'Wave 1 shows DXA adds only 2.34% over adjusted demographic prediction while a single strength-angle curve cannot separate capacity and moment-arm shape.', 'Construct a hierarchical synthetic model of DXA lean, capacity, force-length, and moment arm. Compare DXA only, 1-angle, 3-angle, 5-angle and one imaging measurement under equal-cost alternatives. Quantify held-out torque prediction and parameter identifiability, including correlated measurement errors. Give a minimal prospective real-data protocol.', 'PASS as design result if a prespecified <=3-angle+one-imaging design improves held-out torque RMSE >=10% over adjusted+DXA synthetic baseline across >=80% of scenario grid; clinical/empirical benefit UNKNOWN.'),
}

def main():
    for lane, (title, context, task, criterion) in LANES.items():
        directory = ROOT / lane
        directory.mkdir(parents=True, exist_ok=True)
        brief = f'# {lane}: {title}\n\n{COMMON}\n\n## Prior evidence and strongest baseline\n{context}\n\n## Bounded work\n{task}\n\nDeliver RESULTS.md, results.json and original runnable code; state exact commands, sample sizes, baselines, deviations and limitations.\n'
        prereg = f'# PREREG {lane}\n\nQuestion: {title}.\n\nFrozen decision: {criterion}\n\nFreeze numerical thresholds before analysis. If required data or reference is unavailable, report UNKNOWN or PARTIAL, not a fabricated pass.\n'
        for name, content in [('BRIEF.md', brief), ('PREREG.md', prereg)]:
            path = directory / name
            if path.exists() and path.read_text() != content:
                raise RuntimeError(f'existing differing {path}')
            path.write_text(content)
        (directory / 'PREREG.sha256').write_text(hashlib.sha256(prereg.encode()).hexdigest() + '  PREREG.md\n')
        if lane in ('CLOUD-W2-A359-MISSING', 'CLOUD-W2-A359-SURVEY'):
            source = ROOT / 'CLOUD-A359DATA'
            for name in ('nhanes_public.zip', 'MANIFEST.sha256', 'a359.py'):
                target = directory / name
                if not target.exists():
                    shutil.copy2(source / name, target)
        print(lane)

if __name__ == '__main__':
    main()
