#!/usr/bin/env python3
"""Further bounded follow-up questions for the remaining cloud window."""
from pathlib import Path
import hashlib

root = Path(__file__).resolve().parent / 'lanes'
items = [
('A907-STEPS', 'Finite-difference step selection', 'Test adaptive central differences against complex-step and implicit differentiation on an original parametric quadratic solver with scales spanning 1e-6 to 1e6.', 'PASS if adaptive error <1e-4 on >=95% of 400 smooth seeded cases; report all nonsmooth cases separately.'),
('A907-INERTIA', 'Segment inertia sensitivity', 'Derive normalized contribution of shape-dependent mass and inertia to joint-force geometry derivatives in an original articulated 2D model; vary density and posture independently.', 'PASS if analytic sensitivities agree with finite differences within 1e-4 in 100 seeded cases; private A907 proportion UNKNOWN.'),
('A363-SCALE', 'Batch solver throughput fairness', 'Original NNLS only: compare batched and per-case CPU solvers at batch sizes 1,10,100,1000 with identical stopping certificates, warmup and thread counts.', 'PASS if all timing cells have >=5 repeats and 99% of solves meet scaled KKT <=1e-6; report overhead and any crossovers.'),
('A363-MINMAX', 'Force envelope tolerance dependence', 'Original constrained force allocation: compare bisection and LP/HiGHS min-max envelopes at three feasibility tolerances; quantify changed muscle activity decisions.', 'PASS if envelope error is bounded by independent dual certificates in 100 seeded problems; no claim about private force profiles.'),
('A295-REFERENCE', 'Unconverged reference adjudication', 'Create synthetic QP families in which a reference solver halts early; compare candidate and reference using independent KKT/objective certificates rather than answer equality.', 'PASS if all 100 deliberately unconverged references are identified and all 100 converged ones are accepted under frozen 1e-8 gate.'),
('A303-COVERAGE', 'Coverage at active-set boundaries', 'Original piecewise QP surrogate: calculate 90% conformal coverage separately at active-set interior, switch neighborhood and out-of-support geometry.', 'PASS if all three groups have 85–95% coverage or explicitly abstain on the out-of-support group, across >=1000 points each.'),
('A194-WRAP', 'Wrapped muscle path derivative', 'Original cylinder-wrap path with explicit tangent geometry; compare line-of-action, path-length derivative and force-based moment arms, including crossing modes.', 'PASS if virtual-work and force methods agree within 0.1% away from transitions and all mode switches are identified.'),
('A194-BANDS', 'Moment-arm uncertainty band calibration', 'On original geometry with simulated landmark noise, compare naive linear bands, bootstrap and conformal prediction of held-out moment arms; include wrong-noise counterexample.', 'PASS if >=90% nominal bands cover 85–95% over >=1000 held-out cases; document conditions causing undercoverage.'),
('PATELLA-AXIS', 'Finite screw axis versus perpendicular distance', 'Recreate Krevolin 2004 abstract distinction using original 3D screw-axis and tendon-line geometry; vary tendon-axis angle near extension and compare true screw-axis arm with perpendicular distance.', 'PASS if analytic and numerical virtual-work arms agree within 1% for >=100 regular configurations; measured-individual comparison UNKNOWN.'),
('PATELLA-LOADING', 'Patella loading with coupled quadriceps geometry', 'Original sagittal patella equilibrium model: quantify how quadriceps versus patellar tendon force ratio and contact normal alter inferred knee moment arm across flexion.', 'PASS if vector force and moment balances <1e-6 relative on 100 seeded configurations and operating-range sensitivity is reported.'),
('B1-SELECTION', 'Measurement selection under prior mismatch', 'Original five-parameter linearized model: compare Bayesian OED selections when prior is correct versus 2x/5x wrong and correlated observation errors.', 'PASS if rank of selected designs and >=1000-trial held-out coverage are reported with frozen budgets; no claim of individual clinical utility.'),
('B2-DENSITY', 'CT density calibration extrapolation', 'Find a checked public primary density-to-modulus relation; numerically test extrapolation and partial volume in an original segmented beam. Keep source specimen type and units explicit.', 'PASS method if all interpolated values remain within source regime and finite-element/beam limiting cases agree <2%; empirical transfer UNKNOWN.'),
('B3-BOUNDARY', 'Segmented cell crop boundary bias', 'With public CellMap metadata or a declared original surrogate, compare organelle volume, surface and transport flux under truncation and three boundary treatments.', 'PASS if errors are bounded against a full synthetic volume and every crop touching boundary is explicitly flagged.'),
('B4-ACTIVATION', 'Strength curve activation confounding', 'Prove and test capacity-activation scaling symmetry for knee strength curves under original noise model; compare EMG amplitude and twitch calibration as added observations.', 'PASS if symbolic invariance, Fisher null vector and profile likelihood agree for each of 4 designs.'),
('B5-DISC-AREA', 'Disc area and pressure uncertainty', 'Using Wilke 1999 L4/L5 area 1800 mm2 and the two verified posture pressures as context, calculate force and uncertainty under area shape/measurement error without tuning a lever arm.', 'PASS if all units and pressure-force conversions are checked and interval arithmetic encloses 100000 seeded samples; no patient-risk estimate.'),
('B5-POSTURES', 'Disc posture transfer test', 'Use checked public Wilke 1999 L4/L5 measurements, calibrate a one-parameter equilibrium model on one posture, predict a distinct posture with fixed geometry and report failure plainly.', 'PASS only if held-out posture pressure relative error <=20% with all parameters frozen before testing; population validation UNKNOWN.'),
('VASCULAR-OBS', 'Observability of plasma and interstitial compartments', 'Original two-compartment model: compare input pulse, infusion and recovery observations using exact sensitivity ODE and finite difference, with 4 sampled designs.', 'PASS if rank and profile-likelihood decisions agree for all 4 designs and sensitivity derivative error <1e-4.'),
('TISSUE-MOMENTS', 'Conservative material subcell moments', 'Original crossing-slab voxel model: derive exact per-material volume and first moments, compare voxel methods and test for cancellation in signed sums.', 'PASS if exact moments recovered within 1e-8 relative for 100 analytic slab cases and cancellation counterexample detected.'),
('ORGAN-FLOW', 'Coupled organ perfusion toy model', 'Original lumped perfusion-diffusion model: solve tissue oxygen transient and test mass balance, stiffness and observation identifiability under synthetic parameters.', 'PASS if mass-balance residual <1e-6 and analytic zero-flow and well-mixed limits agree <1%.'),
('MUSCLE-TENDON', 'Tendon compliance versus fiber length', 'Original Hill-type muscle-tendon equilibrium: compare rigid and compliant tendon under isometric angle sweep and one dynamic contraction; test parameter profiles.', 'PASS if force equilibrium <1e-6 and at least one exact or near-identifiability symmetry is demonstrated or refuted.'),
('CONTACT-SENSOR', 'Contact wrench sensor design', 'For one rigid foot/body only, derive uncertainty of normal force and center of pressure from kinematics, IMU and force plate alternatives; avoid Field whole-body theory duplication.', 'PASS if observability rank matches explicit counterexamples in four frozen sensor setups and noise propagation is checked with >=1000 trials.'),
('CELL-ENERGY', 'Mitochondrial geometry and ATP supply', 'Use only verified public segmented geometry or original labeled volume; quantify supply-to-demand ratio under diffusion and reaction with explicit assumed kinetics.', 'PASS if supply flux and consumption balance <1e-5 and grid-convergence <2%; real-cell ATP calibration UNKNOWN.'),
('JOINT-PRESSURE', 'Peak pressure versus contact area', 'Original elastic-contact toy knee: compare Hertz-like analytic limit, penalty mesh and compliant layer; distinguish resultant-force agreement from peak-pressure agreement.', 'PASS if integrated force <0.1% error and peak pressure converges <5% on finest three meshes.'),
('SURROGATE-CERT', 'Solver residual as surrogate certificate', 'Original parametric QP: evaluate whether a learned force estimate plus primal/dual residual and strong-convexity bound can certify force error without ground truth.', 'PASS if certified bounds enclose exact error in all 1000 seeded cases and abstention fraction is reported.'),
('FATIGUE-HEAL', 'Fatigue and repair time-scale uncertainty', 'Original damage-healing ODE with Carter 1981 as a checked fatigue source only if exact specimen data accessible; compare two exercise schedules and uncertain repair rate.', 'PASS mathematical if analytic constant-load solution <1e-5 error and rank reversal region is reproducible; injury risk UNKNOWN.'),
]
common = ('Only public primary data or original code. Do not access restricted model data, TLEM, the collaborator/LHDL data, private A matrices or other repositories. No subagents, push, email, publishing or paid usage. Cite only checked sources and identify exactly which value each source supports. Treat synthetic PASS and anatomical/empirical validity separately. Never invent missing data. Deliver RESULTS.md, results.json and runnable small code; print result files verbatim in final answer between =====FILE <path>===== and =====END FILE=====, total <=200 KB.')
for short, title, task, gate in items:
    lane = 'CLOUD-W5-' + short
    directory = root / lane
    directory.mkdir(parents=True, exist_ok=True)
    brief = f'# {lane}: {title}\n\n{common}\n\n## Bounded work\n{task}\n\nReport baseline, uncertainty, counterexamples, source/version, exact commands, and limitations.\n'
    if lane == 'CLOUD-W5-A303-COVERAGE':
        brief += '\n## Prior returned work\nRead `prior/MANIFEST.md` and the bundled prior code/results before designing this follow-up; do not treat the prior producer verdict as independent evidence.\n'
    prereg = f'# PREREG {lane}\n\nQuestion: {title}.\n\nFrozen criterion: {gate}\n\nIf data needed for an empirical decision are unavailable, report UNKNOWN. Do not revise the frozen gate after seeing results.\n'
    for name, content in [('BRIEF.md', brief), ('PREREG.md', prereg)]:
        path = directory / name
        if path.exists() and path.read_text() != content:
            raise RuntimeError(f'existing {path} differs')
        path.write_text(content)
    (directory / 'PREREG.sha256').write_text(hashlib.sha256(prereg.encode()).hexdigest() + '  PREREG.md\n')
    print(lane)
