#!/usr/bin/env python3
"""Follow-ups triggered by Wave 3/4 outcomes and the spatial-cell roadmap."""
from pathlib import Path
import hashlib

root = Path(__file__).resolve().parent / 'lanes'
items = [
('A363-COLSCALE', 'Column-scaled NNLS stopping counterexample', 'Wave 4 A363 audit passed 1000/1000 on normalized matrices, but only 31/100 when columns spanned 1e-6 to 1e6. Build original seeded benchmark comparing original stopping, column-normalized solver and per-column dual tolerances with independent SciPy/BVLS references. Freeze seeds and tolerance before comparing.', 'PASS if a proposed repair gives >=95/100 correct objectives and scaled KKT in held-out badly scaled cases, without losing more than 5/100 normalized cases.'),
('A295-DUAL', 'Sharp exact QP certificate without reference solve', 'Wave 4 A295 tight solver true gaps were tiny, yet a frozen exact Wolfe dual point certified only 4/100. Derive a cheaper dual-point construction based only on the candidate active set, then stress-test it on original dyadic box QPs with a separate exact reference for audit only.', 'PASS if >=99/100 well-conditioned cases certify absolute gap <=1e-8 and 100% of uncertified ill-conditioned cases stay UNKNOWN; no post-hoc rule changes.'),
('A907-SWITCH', 'Active-set switch detection without constructed-test tuning', 'Wave 4 A907 synthetic derivative check needed post-hoc repair of its switch generator. Freeze an independently generated family of nonnegative QPs with analytic switch location. Test one-sided implicit derivatives, FD and singularity alarms across exact, near and far switch points.', 'PASS if 100/100 seeded switch or near-switch cases are flagged or directionally bounded while >=95/100 regular cases retain relative derivative error <1e-4.'),
('A194-PUBLIC', 'OpenSim model versus measured moment-arm source audit', 'Read SOURCE_NOTES.md and the bundled pinned public Gait2354 XML first. Locate a versioned research-use public hip/knee model and actual independent cadaver or imaging moment-arm series for at least one matched muscle and coordinate. Gait2354 is CC BY 3.0 but explicitly a demonstration model; do not present it as research validation. Audit axis, sign, units and subject matching before any numerical comparison.', 'PASS data readiness only if model license/version and measured series with DOI, numeric samples, anatomical and angle definitions can all be verified for >=1 muscle; otherwise UNKNOWN with exact missing element.'),
('PATELLA-DATA', 'Patella 45-degree peak evidence resolution', 'Use the checked Krevolin 2004 PubMed abstract DOI 10.1016/j.jbiomech.2003.09.010, which reports six cadaver knees and a peak near 45 degrees about the finite screw axis. Seek numeric per-angle individual data legally available. Compare with two public OpenSim model curves only after matching definitions; do not fabricate points from an abstract.', 'PASS empirical only if >=6 independent measured curves are digitized or tabulated with uncertainty and matched angle definitions; otherwise report UNKNOWN and an exact retrieval map.'),
('OED-CONTRAST', 'OED covariance calibration failure on contrast target', 'Wave 3 OED-CORREL gave covariance-aware coverage 0.827 for thigh-minus-shank despite passing the sum target. Fix the target and original Gaussian generator, compare plug-in covariance, shrinkage and held-out calibration of intervals under 100 versus 500 calibration subjects.', 'PASS if held-out nominal 90% coverage is 85–95% for both sum and contrast over >=1000 trials each, without changing target after design.'),
('VASCULAR-RANK', 'Threshold-stable vascular observability', 'Wave 3 VASCULAR-SAMPLE labeled plasma-only rank 3 at singular ratio 1.4e-7 under a 1e-6 threshold. Derive structural parameter symmetry if any, evaluate singular spectra versus timescale/noise and compare profile likelihood over four frozen sampling designs.', 'PASS if structural rank and practical rank are explicitly separated, and all four profile decisions agree with their declared noise-dependent threshold.'),
('NATO-PRIMARY', 'Bone fatigue source-anchored interval extraction', 'Prior NATO-chain sessions found no checked ranges due cloud egress. Use Carter et al. 1981 primary entry https://actaorthop.org/actao/article/view/28841 and any directly accessible table/pdf. Extract only specimen-matched fatigue strain/cycles/units with uncertainty; leave load-to-injury mapping unknown.', 'PASS source audit if every numerical interval has a verified primary table or is labeled ASSUMED, and at least one fatigue relation is transcribed with specimen and loading regime.'),
('CELL-REDUCE', 'Output-aware reduction of segmented cell transport', 'Roadmap H1: compare original 3D finite-volume two-region diffusion-reaction geometry against an equal-volume/equal-area compartment baseline and a resistance-preserving region graph. Hold out shapes and reaction rates; include reduction cost and conserved quantity. Read public_s2/PROVENANCE.md and use its checked CellMap geometry as one separately reported illustrative case; its crop touches the boundary, so it is not full-cell ground truth. Read prior_b3/MANIFEST.md for the earlier crop-closure sensitivity result; do not use that synthetic PDE output as biological truth.', 'PASS numerical if held-out output error <=5% at lower total runtime for >=80% of >=20 original synthetic shapes while mass residual <1e-6; no biology claim.'),
('CELL-PARTICLE', 'Positive particle-field port at low copy number', 'Roadmap H2: implement original two-sided finite-volume/SSA port with molecule counts. Compare all-particle baseline for a bounded two-compartment toy and check integer transfer, positivity and time-step sensitivity at low copy number.', 'PASS if exact molecule count conserved in all >=1000 seeded runs, no negative counts, and first-event distribution differs <=5% from all-particle baseline.'),
('CELL-MEMBRANE', 'Conservative remap of moving membrane receptors', 'Roadmap H3: construct an original moving triangulated ring/sphere patch model with known material map. Compare overlap remap against naive vertex interpolation for receptor counts, moments and spatial correlations across 100 deformations.', 'PASS if mass residual <1e-10, first-moment error <1%, and no artificial variance gain in all invertible deformations.'),
('CELL-ELECTRO', 'Variable-area membrane charge balance', 'Roadmap H4: implement original crista-like membrane patches with variable area, capacitance, pump and leak. Compare d(C_m A V)/dt to the incorrect fixed-area C_m A dV/dt form under known deformation and a charge-conserving numerical scheme.', 'PASS if total charge residual <1e-6 in 100 seeded deformations and the omitted area term is exposed by an analytic counterexample.'),
('CELL-ADAPT', 'Adaptive cell detail with output-error certificate', 'Roadmap H5: original heterogeneous diffusion-reaction toy with region graph and local error estimator for fixed ATP flux observable. Compare static coarse and converged fine meshes; include estimator overhead and rare-event failure case.', 'PASS if certified output bounds enclose true error in >=95% of 100 held-out geometries and total runtime is lower than static fine on >=70%.'),
('TISSUE-PARTITION', 'Material-partition false conservation pass', 'Following A194/A204 field observations, use an original analytic crossing-slab voxel setup to separate total volume conservation from per-material stiffness and first moments. Sweep resolution and layer orientation.', 'PASS if per-material moments expose every deliberately swapped partition and analytic effective stiffness is recovered to 1% at finest resolution.'),
('ORGAN-PERFUSION', 'Perfusion reaction identifiability in tissue', 'Original one-dimensional organ slab with capillary source, diffusion and consumption. Compare concentration-only versus concentration-plus-flow observations under four frozen protocols; use a checked public primary reference only if matched variables can be verified.', 'PASS synthetic if mass balance <1e-6 and profile/Fisher identifiability agrees across four designs; empirical validity UNKNOWN without matched data.'),
]
common = ('Read SOURCE_NOTES.md when present. Only public primary data or original code. No restricted model data, TLEM, the collaborator/LHDL data, private A matrices or private repositories. No subagents, Git push, email, publishing or paid usage. Cite exact checked source URLs/DOIs and what each supports. Distinguish synthetic method checks from empirical/anatomical validity. If required data are unavailable, say UNKNOWN without fabricating. Deliver RESULTS.md, results.json and runnable code; print small files between =====FILE <path>===== and =====END FILE=====, total <=200 KB.')
for short, title, task, gate in items:
    lane = 'CLOUD-W6-' + short
    directory = root / lane
    directory.mkdir(parents=True, exist_ok=True)
    brief = f'# {lane}: {title}\n\n{common}\n\n## Bounded task\n{task}\n\nReport strongest baseline, source/version, exact commands, units, uncertainty, counterexamples and limitations.\n'
    if lane in {'CLOUD-W6-A907-SWITCH', 'CLOUD-W6-A194-PUBLIC', 'CLOUD-W6-OED-CONTRAST',
                'CLOUD-W6-VASCULAR-RANK', 'CLOUD-W6-PATELLA-DATA', 'CLOUD-W6-CELL-REDUCE'}:
        brief += '\n## Prior returned work\nRead `prior/MANIFEST.md` and the bundled prior code/results before designing this follow-up; do not treat the prior producer verdict as independent evidence.\n'
    prereg = f'# PREREG {lane}\n\nQuestion: {title}.\n\nFrozen criterion: {gate}\n\nDo not revise this gate after inspecting outcomes; put exploratory repairs in a separate section.\n'
    for name, content in [('BRIEF.md',brief),('PREREG.md',prereg)]:
        path=directory/name
        if path.exists() and path.read_text()!=content:
            raise RuntimeError(f'existing {path} differs')
        path.write_text(content)
    (directory/'PREREG.sha256').write_text(hashlib.sha256(prereg.encode()).hexdigest()+'  PREREG.md\n')
    print(lane)
