from pathlib import Path
import json
P = Path(__file__).resolve().parent
obs = [json.loads(l) for l in (P / 'VERIFIED_OBSERVATIONS.jsonl').read_text().splitlines()]
base = [json.loads(l) for l in (P / 'VERIFICATIONS.jsonl').read_text().splitlines()]
D = {49: ('VERIFIED_PRIMARY_NUMBERS', ['CADON_'], 'Tables1-3 verify fatigue loads, fitted shape and 70% CAD-on1.5mm runout survival. Step-stress load/cycles and censoring retained; not static crown strength.'), 50: ('VERIFIED_PRIMARY_NUMBERS', ['PRIMER_'], 'Primary abstract verifies8.24±3.21/4.60±2.21MPa for specified primer/cement combinations. Decimal comma converted explicitly. Shear threshold is not peel fracture energy.'), 52: ('QUARANTINED_SOURCE_CONTRADICTION', [], 'Tables1/2 primary values found. Paired mean identity fails in groups A/B by0.43/-0.38K, beyond0.015K rounding allowance; no guessed corrections adopted.'), 54: ('VERIFIED_PRIMARY_NUMBERS', ['STAW_'], 'Tables5/6 six biaxial groups independently verify mean/SD and separately fitted m/sigma0/CI. Do not pool three-point/four-point stress states.'), 59: ('VERIFIED_PRIMARY_NUMBERS', ['CUREUS_'], 'Table2 verifies five material means/SD and five fitted Weibull moduli; n10 per material. Fit uncertainty not identified in table.'), 62: ('CORRECTED_SCOPE', ['ABUTMENT_'], 'Table2 loads/SD verified. Methods show3mm group has1mm occlusal/3mm proximal wall and a prefabricated abutment. the swarm’s uniform thickness1->3mm interpretation is not a measured experiment.'), 67: ('VERIFIED_PRIMARY_NUMBERS', ['MICRO_'], 'Table2 local microgaps by assembly/position/load verified. Methods uncertainty is50% up to2um,2um for larger gaps, not below1um. Keep location and loading; no leakage prediction.'), 70: ('VERIFIED_PRIMARY_NUMBERS', ['RABBIT_BIC_'], 'Table2 means63.74/62.83%BIC at12weeks, nine retained rabbits. TableSD13.61/9.91 retained; SLA proseSD10.89 conflicts, so uncertainty transfer withheld.'), 72: ('CORRECTED_SCOPE', ['BARBED_'], 'Table2 seven Fmax/cycle pairs verified.132.60N at5million cycles is right-censored finite test, not proof of infinite life. Nonmonotonic observed cycles preserved.'), 104: ('VERIFIED_PRIMARY_NUMBERS', ['DIAMETER_'], 'Table1 nine diameter/embedding group failure means/SD verified,n10. Endpoint is static failure after1.2million50N cycles, not same-load fatigue limit.'), 147: ('VERIFIED_PRIMARY_NUMBERS', ['TAN_PRELOAD_'], 'Primary abstract seven calibrated load-cell means/dispersion verified. Manufacturer recommended torque differs by system; not seven measurements at35Ncm.'), 142: ('VERIFIED_PRIMARY_NUMBERS', ['CHUA_'], 'Table2 six cooling/dry pulp-temperature changes/SD verified; eight cuts/condition. Different handpiece models and intermittent cutting retained; no measured post-stop curve adopted.')}
for fn in ['SELECTED_R3.json', 'SELECTED_R3B.json']:
    for r in json.loads((P / fn).read_text()):
        (status, prefixes, note) = D[r['rank']]
        ids = [o['id'] for o in obs if any((o['id'].startswith(x) for x in prefixes))]
        base.append({'inspection_order': len(base) + 1, 'round': 'R3B' if fn.endswith('R3B.json') else 'R3', 'candidate_id': r['candidate_id'], 'original_rank': r['rank'], 'frozen_report': r['path'], 'frozen_report_sha256': r['source_sha256'], 'external_referent_original': r['external_referent'], 'verification_status': status, 'verified_observation_ids': ids, 'note': note, 'review_state': 'PENDING_INDEPENDENT_REVIEW', 'source_numerical_adoption': bool(ids), 'entire_swarm_claim_endorsed': False})
(P / 'VERIFICATIONS.jsonl').write_text(''.join((json.dumps(x, ensure_ascii=False) + '\n' for x in base)))
print('adjudicated', len(base), 'with source numeric facets', sum((v['source_numerical_adoption'] for v in base)))
