import json, hashlib, datetime
from pathlib import Path
R = Path(__file__).resolve().parents[1]

def save(name, x):
    p = R / name
    if p.exists():
        raise RuntimeError('Frozen ' + name)
    p.write_text(json.dumps(x, indent=2) + '\n')
    p.with_suffix('.sha256').write_text(hashlib.sha256(p.read_bytes()).hexdigest() + '  ' + p.name + '\n')
now = datetime.datetime.now(datetime.timezone.utc).isoformat()
save('PREREG_A.json', dict(frozen_utc=now, claim_type='capability', capability='New material-specific tapered virtual preparations and reconstructed contralateral crowns on the unchanged 18 teeth / 6 arches', obstacle='Inherited nonplanar single-apex cone intersects source anatomy; offset infeasible. Native scan boundaries are not preparation margins.', changed_operation='First diagnose native axis geometry. Then replace inherited cone with a tapered, rounded, direction-monotone preparation jointly constrained by native and mirrored exterior clearance; independently certify inclusion and insertion. New virtual shoulder is explicitly constructed, not a recovered clinical margin.', consumer='R4/R6 mirrored outer form -> CAD10X design -> all combined-chain ports', selection='All18 FROZEN_INPUTS_B records, no replacement. Both published material scenarios; source geometry remains read-only.', metrics=dict(shape_p95_mm=dict(anterior=0.24, premolar=0.725, molar=0.437), wall_mm=dict(zirconia=0.5, lithium_disilicate=1.0), internal_gap_mm=0.05, gap_residual_max_mm=0.01, margin_max_mm=0.025, total_convergence_degrees=[10, 20], self_intersections=0, components=1, peak_memory_MiB=3500), decision='Complete digital crown requires every geometry/export/tool gate; physical chain remains UNKNOWN wherever same-case evidence is absent. No selected subset may replace denominator. No universal physical impossibility inferred from finite-family failure.', strongest_equally_informed_control='Independent libigl/trimesh distance parity, exact stored-coordinate CGAL separation, existing normal-cone LP, original R4 shape and CAD10X film/mesh checks; no algorithm superiority claimed.', falsifiers=['Preparation or its required dilation leaves native closed digital support', 'Mirrored exterior wall below material minimum', 'Any reversed facet or false unit/film/wall/port survives fault control', 'Any tool-shank or physical gate labelled PASS without evidence'], external_referent=dict(kind='published_dataset', locator='https://osf.io/xctdy/ ; ../PROOF_LANE_FULL_CROWN_R4/FROZEN_INPUTS_B.json', compared_quantity='Independent original IOS surface distance per tooth; virtual preparation is not measured', refutes_us=True), full_cost=dict(preparation='Source hashing, source support construction and frame search', fit='No learned fit', discovery='All candidate generation including failures', validation='Exact/distance/mesh/film verification plus corruption tests', queries='18teeth x2 material scenarios', fallback='Changed construction preregistered; no case replacement', historical_cost='UNKNOWN'), resolution=dict(geometry='PER_POINT', regional_reduction='PER_SURFACE_REGION', case='PER_TOOTH', cohort='PER_ARCH', material_limits='POPULATION', unmeasured_inputs='PHENOMENOLOGICAL'), time_scale='SIMULTANEOUS', resources=dict(threads=1, max_intermediates_bytes=3 * 1024 ** 3, RLIMIT_AS_MiB=3500)))
save('DECOMPOSITION_A.json', dict(idea='Jointly design preparation/cavity inside two available geometric envelopes', mechanism='Common insertion cone gives direction-monotone sublevel sets. Positive clearance separates preparation from source and cavity from crown exterior.', equations=['K=Q⊕B_g; K⊕B_t=Q⊕B_(g+t)⊆T', 'n_i·d>=0 for all oriented nonbasal facets is necessary; convex monotone construction supplies full isolated-tooth path', 'dist(x,S)>=dist(a,S)-|x-a| by1-Lipschitz; sampled a needs rigorous cover and arithmetic bound'], representation='Tapered rounded core plus explicit triangle exterior and region identities', leaves=[dict(status='DERIVED_UNDER_ASSUMPTIONS', statement='Set addition and Lipschitz inequalities', stopping_argument='Digital Euclidean geometry; exact certificates still bind stored coordinates only'), dict(status='EXTERNALLY_MEASURED', statement='Native IOS triangle surface', stopping_argument='No same-case scanner uncertainty, pulp or finish-line measurement'), dict(status='CONSTITUTIVE_CLOSURE', statement='Manufacturer reduction, convergence and margin scenarios', stopping_argument='Published design rules do not predict case-specific physical performance'), dict(status='UNKNOWN', statement='Actual loaded bite, pulp safety, CAM shank access, seated film and fracture force', stopping_argument='Require same-specimen measurements; no transferable scalar fills these ports')]))
(R / 'CURRENT_WORK_STATE.json').write_text(json.dumps(dict(updated_utc=now, phase='A_FROZEN', latest_gate='Inherited exact obstruction read; own native-frame diagnostic next', next_operation='Measure source frame spans before web verification', review_state='PENDING_INDEPENDENT_REVIEW'), indent=2) + '\n')
