from dental_release.paths import expand as _release_expand
from common import *

def run():
    models = [dict(name='CrownGen', paper='https://arxiv.org/abs/2512.21890', repo='https://github.com/baejustin/CrownGen', code=True, weights=False, license='UNSPECIFIED', blocker='No checkpoint in recursive tree, no release assets, README has training/inference but no checkpoint download; HF model search empty. No claim weights do not exist elsewhere.'), dict(name='MADCrowner', paper='https://arxiv.org/abs/2603.04771', repo='https://github.com/lullcant/MADCrowner', code=True, weights=False, license='Apache-2.0 (repo); submodule SAP MIT', blocker=_release_expand('test.sh points to author-local @DENTAL_EXTERNAL_ROOT@/mounted/disk1/linda/DCrownFormer/checkpoints/CrownDeformer_curvature_6400_final_all_teeth_step_400000.pth; no checkpoints in tree/releases or HF search. Requires pytorch3d/torch-scatter not installed.')), dict(name='DCrownFormer', paper='https://papers.miccai.org/miccai-2024/paper/0638_paper.pdf', repo='https://github.com/suyang93/DCrownFormer', code=False, weights=False, license='UNSPECIFIED', blocker='Author README states technology transfer prevents code sharing; repository only readme.'), dict(name='hk-neo CrownGen reproduction', repo='https://github.com/hk-neo/CrownGen', code=True, weights=False, license='UNSPECIFIED', blocker='README explicitly excludes Data and *.pt weights; training needed. Not author CrownGen checkpoint.'), dict(name='ToothCraft', paper='https://arxiv.org/abs/2603.26588', repo='https://github.com/ikarus1211/VISAPP_ToothCraft', weights_locator='https://huggingface.co/DejvaX/ToothCraft', code=True, weights=True, license='UNSPECIFIED: no top-level licence or HF model card; no redistribution licence assumed', selected=True, weights_bytes=517783660, dependencies='Local torch2.11 CUDA12.8; small hydra/omegaconf; selected normal attention leaves xformers unused; fail-closed shim')]
    d = dict(accessed_utc=now(), scope='targeted public author repositories, recursive trees, releases, README inference paths, HF model name search; no exhaustive field census', models=models, dropout={'screened': 5, 'selected': 1, 'excluded': 4, 'fraction': 0.8, 'reasons': {'missing_shared_weights': 3, 'no_shared_code': 1}}, evidence_files=[p.name for p in (ROOT / 'raw').glob('*tree.json')] + [p.name for p in (ROOT / 'raw').glob('*releases.json')] + [p.name for p in (ROOT / 'raw').glob('HF_search*')])
    dump(ROOT / 'EXTERNAL_MODELS.json', d)
if __name__ == '__main__':
    run()
