"""Freeze construction 1 before executing numerical tests."""
import datetime, hashlib, json
from pathlib import Path
ROOT = Path(__file__).resolve().parent

def save(name, obj):
    p = ROOT / name
    p.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + '\n')
    return hashlib.sha256(p.read_bytes()).hexdigest()
now = datetime.datetime.now(datetime.timezone.utc).isoformat()
prereg = {'id': 'X8_R1', 'frozen_at': now, 'capability': 'Predict per-site clinical neurosensory alteration under a chosen guidance system', 'obstacle': 'Marginal guide magnitudes do not identify a signed pose law; distance-incidence pooling may not transport', 'changed_operation': 'Convolve a guide-error law with a canal-distance hazard and challenge both links against external measurements', 'consumer': 'Research implant/drill planner; no clinical deployment', 'source_exposure': 'Abstracts and tables were read during source discovery. External falsification is exposed, not blind validation.', 'metrics': [{'name': 'literal_zero_above_1mm', 'quantity': 'events in review Table 2 group 1-2mm', 'tolerance': 0, 'pass': 'no nonzero row'}, {'name': 'transfer_of_68percent', 'quantity': 'two-sided binomial compatibility of review rate 0.68 with Kutuk subgroup', 'tolerance': 0.01, 'pass': 'p >= 0.01'}, {'name': 'K3_angle_external', 'quantity': 'absolute mean angular error versus Tahmaseb2018 3.5 degrees', 'tolerance': 1.0, 'pass': 'error <= 1 degree'}], 'decision': 'All three gates must pass before interpreting a convolution as clinical nerve-risk evidence', 'strongest_equally_informed_control': 'Per-study exact-binomial estimates retaining study, denominator, imaging and selection; direct published angular mean with no invented pose covariance', 'practice_control': 'Fixed nominal 2mm rule', 'falsifiers': ['Any actual event at 1-2mm refutes a literal zero-risk rule', 'Incompatible independent subgroup refutes universal transfer of 68%', 'Independent angular mean rejects entry/apex-derived tilt closure'], 'cost': {'preparation': 'Targeted source reads, exact table extraction, hashes', 'fit': 'Existing K3 mean-norm calibration at n=400000', 'discovery': 'Source search and reconstruction logged; human-equivalent cost not measured', 'validation': 'Exact binomial test and one external angular comparator', 'queries': 'Three scalar gates', 'fallback': 'Change to conditional geometric event and explicit uncertainty sets; clinical risk UNKNOWN'}, 'external_locators': ['doi:10.4317/medoral.27125 Table2', 'doi:10.1097/ID.0000000000000160 PMID25365650', 'doi:10.1111/clr.13346 PMID30328191']}
if (ROOT / 'PREREG_R1.json').exists():
    raise SystemExit('Refusing to overwrite frozen preregistration')
h = save('PREREG_R1.json', prereg)
(ROOT / 'PREREG_R1.sha256').write_text(h + '\n')
save('FROZEN_PREDICTIONS_R1.json', {'frozen_at': now, 'prereg_sha256': h, 'predictions': {'distance_1_to_2_mm_incidence': 0.0, 'distance_0_to_1_mm_incidence': 0.68, 'canal_intrusion_incidence': 0.53}, 'exposure': 'Source-exposed falsification; no claim of blinded prediction', 'K3_angle': 'Frozen deterministic function clinical_model(SCHNEIDER_2009,L=11).pred_angle_mean_deg; code source hash recorded in source manifest'})
save('DECOMPOSITION_R1.json', {'chain': 'idea -> guide pose -> tool swept volume -> distance observation -> proximity event -> tissue response -> sensory observation', 'leaves': [{'name': 'distance under rigid pose', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'relation': 'd(T(tool),canal)', 'units': 'mm', 'stop': 'Rigid geometry defines observable; deformation and thermal injury absent'}, {'name': 'entry/apex mean norms', 'status': 'EXTERNALLY_MEASURED', 'source': 'Schneider2009 PMID19663953', 'stop': 'Aggregate magnitude only; signed errors, covariance, clustering unavailable'}, {'name': 'isotropic normal entry and independent tangent tilt', 'status': 'CONSTITUTIVE_CLOSURE', 'relation': 'e~N(0,sigma_e^2 I3); theta~N(0,sigma_t^2 I2)', 'stop': 'Not derivable from aggregate mean norms; external angle can refute'}, {'name': 'canal image offset', 'status': 'EXTERNALLY_MEASURED', 'source': 'GEOM_UNC/REPORT.md', 'stop': 'Label-to-halfmax, not image-to-anatomy'}, {'name': 'true canal boundary and true metal apex', 'status': 'UNKNOWN', 'source': 'LANE_NEXT_N_CANAL_PROXIMITY/HANDOFF.md', 'stop': 'No independent local metrology'}, {'name': 'proximity to sensory injury', 'status': 'UNKNOWN', 'relation': 'P(Y=1|d,procedure,tissue,followup)', 'stop': 'Observational distance groups differ in selection, imaging, denominator and follow-up'}, {'name': 'sensory incidence by distance bin', 'status': 'EXTERNALLY_MEASURED', 'source': 'PenaCardelles2025 Tables1/2; primary Kutuk2014 abstract', 'stop': 'Published values can refute transport but do not calibrate guide-specific per-site causality'}]})
print(h)
