"""Manually curated retrospective reference, before executable extraction checks."""
from pathlib import Path
import json, hashlib, datetime
H = Path(__file__).resolve().parent
C = []

def row(table, r, c, value, sd, key, unit, **kw):
    return dict(table=table, row=r, column=c, value=value, sd=sd, key=key, unit=unit, statistic='reported_mean', **kw)

def add(i, s, title, target, tk, ts, base, scope, limits, records, **kw):
    C.append(dict(id=i, source=s, title=title, consumer=target, target_kind=tk, time_scale=ts, resolution_level='POPULATION', current_practice_without_information=base, scope=scope, limitations=limits, records=records, **kw))
t = 'polymers-15-01737-t00'
a = [[(794.83, 68.52), (1013.31, 140.13), (1067.35, 75.42), (1267, 240.58), (1434.43, 288.52)], [(626.32, 96.41), (1113.47, 61.84), (1102.81, 148.05), (1327.3, 161.96), (1487.58, 179.52)], [(602.03, 82.76), (1041.01, 145.87), (1076.02, 89.74), (1124.87, 121.59), (1203.05, 114.49)]]
b = [[(610.06, 208.95), (980.72, 298.7), (1259.64, 205.8), (1476.99, 71.47), (1683.56, 207.57)], [(532.83, 109.21), (1307.32, 88.89), (1438.88, 209.6), (1437.02, 230), (1507.19, 90.37)], [(503.29, 196.37), (1168.46, 172.91), (1207.51, 151.98), (1237.17, 98.03), (1342.44, 76.05)]]
rr = [row(t + str(tn), r + 3, c + 2, v, sd, dict(material=m, orientation_deg=[0, 45, 90][r], postcure_min=[0, 30, 60, 90, 120][c]), 'N', n=10) for (tn, m, arr) in [(2, 'ASIGA DentaTOOTH', a), (3, 'NextDent C&B', b)] for (r, rv) in enumerate(arr) for (c, (v, sd)) in enumerate(rv)]
add('L01', 'PMC10097162', 'Post curing and direction → breaking load for temporary triangular bridge', 'DENT-MAT-RESTORATIVE-PSP', 'draft_node', 'HANDOVER', 'No source-conditioned interim-FDP benchmark in the previous three information-link files. A material name alone omits printing orientation and postcure.', '300 interim three-unit FDPs, n=10 per material × angle × postcure; 50 um layers, 405 nm/60 C curing, water 24 h and 5000 thermocycles; zirconia die, central pontic loading.', 'Reported loading speed is 1 m/min, retained as published and not silently changed to mm/min. Abstract ranks 45 deg highest generally but table does not do so for every material/time. Not definitive crown strength.', rr, quantity='fracture_load_after_manufacture_and_thermocycling', method_xpath='/article/body/sec[2]', method_terms=['300', '50 µm', '5000', '1 m/min', '60 °C'], unit_table=t + '2', unit_term='(N)')
rr = [row('TB2252138-3', r + 2, c + 2, v, sd, dict(material=m, hydrothermal_aging=bool(c), cyclic_preconditioning='50 N / 240000 cycles'), 'MPa', n=10) for (r, (m, arr)) in enumerate([('Vita YZ T', [(815.47, 43.44), (811.45, 27.8)]), ('Vita YZ ST', [(683.39, 29.34), (652.63, 22.56)]), ('Vita YZ XT', [(431.51, 20.48), (365.06, 19.67)]), ('Prettau Anterior', [(406.36, 23.83), (334.88, 23.41)])]) for (c, (v, sd)) in enumerate(arr)]
add('L03', 'PMC10569846', 'Age history → remaining biaxial strength', 'DENT-MAT-ZRO2-LTD', 'draft_node', 'HANDOVER', 'An as-new zirconia strength input lacks hydrothermal and cycle history. No matched table in previous information links.', '15 mm × 1 mm zirconia discs; 4 commercial materials; 122 C, 2 bar, 8 h aging or air-dry; all specimens 50 N / 240000 cycles / 1.1 Hz in water before destructive biaxial test.', 'Source calls endpoint flexural fatigue strength; it is residual destructive strength after fixed cyclic preconditioning, not endurance limit or S-N curve. No clinical-time conversion; reported p=0.154 does not prove equivalence.', rr, quantity='residual_biaxial_flexural_strength', method_xpath='/article/body/sec[2]', method_terms=['122°C', '240,000', '0.5 mm/min'], unit_table='TB2252138-3', unit_term='(MPa)')
rr = [row('jfb-14-00567-t001', r + 2, 2, v, sd, dict(group=k), 'N', n=7) for (r, (k, v, sd)) in enumerate([('0', 783, 43), ('H', 742, 43), ('L', 757, 86), ('HL', 740, 51)])]
add('L04', 'PMC10743638', 'Previous cycling/aging → two-part implant remaining breaking load', 'DENT-IF-IA-ASSEMBLY-FATIGUE', 'draft_node', 'HANDOVER', 'Previous ISO RAW36 link supplies another assembly S-N test. This two-piece zirconia/PEEK system lacked a condition-keyed residual-strength endpoint.', 'Zeramex XT ATZ 4.2 × 14 mm, zirconia abutment, carbon-reinforced PEEK screw at 25 Ncm; 8/group initially, 1/group cross-sectioned, 7/group destructive tests. L=98 N / 1e7 cycles at 1.3 Hz; H=85 C water; HL simultaneous H+L, then 10 mm/min static fracture.', 'Table HL SD=51 N conflicts with abstract SD=43 N. Both retained in SOURCE_CONFLICTS. No equivalence proof or fatigue-limit estimate. Existing RUNOUT report read; added endpoint is residual static load, not repeated runout rows.', rr, quantity='residual_assembly_static_fracture_load', method_xpath='/article/body/sec[2]', method_terms=['seven of the eight', '98 N', '10 million', '25 Ncm', '85 °C'], unit_table='jfb-14-00567-t001', unit_term='(N)')
rr = [row('jfb-14-00124-t002', r + 2, 3, v, sd, dict(channel_angle_deg=ang, endpoint='cRTV-bRTV'), 'N cm', n=5, baseline_RTV_Ncm=b, baseline_sd=bs) for (r, (ang, v, sd, b, bs)) in enumerate([(0, -2.41, 1.68, 28.84, 0.91), (15, -2.7, 1.44, 28.87, 1.43), (25, -1.38, 1.4, 27.14, 0.8)])]
add('L05', 'PMC10051685', 'Cycle load and screw channel → changed discharge torque', 'IM05', 'chain', 'HANDOVER', 'Initial torque/preload alone has no measured cyclic reverse-torque change. The previous repeated-tightening preload link is a different observable.', 'Nobel Replace Conical Connection 4.3 × 10 mm with ASC zirconia central-incisor crown, same reused screws; 35 Ncm, retightening after 10 min; 0–40 N at 30 deg, 1e6 cycles, 10 Hz; n=5/channel angle.', 'Reverse torque is N cm, never preload in N. No conversion without friction/contact calibration. Angle effect is not established by differing descriptive means; source reports p=0.212. IM05 is an existing brainstorm chain, not a native solver.', rr, quantity='change_in_reverse_torque', method_xpath='/article/body/sec[2]', method_terms=['35 Ncm', '1 million', '10 Hz', 'cRTV-bRTV'], unit_table='jfb-14-00124-t002', unit_term='(Ncm)')
rr = [row('tbl0003', r + 3, c + 2, v, sd, dict(antagonist='human enamel buccal cusp', counterface=mat, measurement=method), 'mm^3', n=4) for (r, (mat, arr)) in enumerate([('Human enamel', [(4.24, 0.115), (4.108, 0.043)]), ('Vita Suprinity', [(5.043, 0.1), (4.658, 0.354)]), ('Lava Esthetic Zirconia', [(5.025, 0.098), (4.985, 0.257)]), ('IPS e.max Press', [(4.915, 0.115), (4.593, 0.229)])]) for (c, (method, (v, sd))) in enumerate(zip(['micro-CT', 'intraoral scanner'], arr))]
add('L06', 'PMC10350602', 'Antagonist materials and measurement method → enamel volume loss', 'K34', 'chain', 'HANDOVER', 'No antagonist-pair/time wear observations in original PROOF_LANE chain matrix K34; an intact or rigid antagonist contains no wear history.', 'Polished flat ceramics or human enamel opposing extracted human maxillary-premolar buccal cusp; n=4/group; 49 N, 250000 cycles, 1 Hz, 1.5 mm sliding, 30% glycerine; paired micro-CT and intraoral scans.', 'Published table endpoint is volumetric loss; raw volumes unavailable, measurement bias UNKNOWN. Paired methods are not independent specimens. Small n; no patient-specific wear rate or clinical year conversion.', rr, quantity='enamel_antagonist_volumetric_loss', method_xpath='/article/body/sec[2]', method_terms=['250,000', '49 N', '13-µm', 'n = 4'], unit_table='tbl0003', unit_term='mm 3')
rr = [row('jfb-14-00395-t003', r, 4, v, sd, dict(support=k, endpoint='LDS sample volume loss'), 'mm^3', n=15, sd_row=r + 1, sd_column=3) for (r, k, v, sd) in [(2, 'rigid cylinder', 0.322, 0.098), (4, 'implant', 0.166, 0.033), (6, 'artificial PDL tooth replica', 0.107, 0.045)]]
add('L07', 'PMC10455685', 'Support design → Lithium disilicate wear', 'K34', 'chain', 'HANDOVER', 'Wear inputs conditioned only on material omit the support construction; no such conditional benchmark in previous links.', 'IPS e.max CAD polished LDS samples and LDS opposing cusps; implant support vs hybrid-ceramic tooth replica with 0.85 mm polyether artificial PDL vs cylinder; n=15/group; 49 N, 120000 cycles, artificial saliva.', 'Artificial PDL is not measured human ligament thickness or its modulus. Group differences include support geometry; cannot isolate a causal stiffness coefficient. No transfer of 0.85 mm to patient anatomy.', rr, quantity='LDS_sample_volumetric_loss', method_xpath='/article/body/sec[2]', method_terms=['0.85 mm', '120,000', 'fifteen'], unit_table='jfb-14-00395-t003', unit_term='mm 3')
rr = []
for (r, cond, wear, vals, cols) in [(3, 'pulp', 'new', [(27.45, 0.66), (21.57, 0.27), (20.71, 0.2)], [4, 6, 8]), (4, 'pulp', 'fifth', [(29.15, 0.67), (21.96, 0.19), (20.74, 0.31)], [3, 5, 7]), (5, 'pulp', 'eighth', [(28.67, 1.18), (21.28, 0.37), (20.35, 0.21)], [3, 5, 7]), (6, 'paste', 'new', [(28.99, 1.5), (21.14, 0.31), (20.29, 0.25)], [4, 6, 8]), (7, 'paste', 'fifth', [(29.77, 0.47), (21.25, 0.17), (20.25, 0.17)], [3, 5, 7]), (8, 'paste', 'eighth', [(29.76, 0.41), (21.53, 0.4), (20.21, 0.17)], [3, 5, 7])]:
    for (t, c, (v, sd)) in zip([0, 1, 3], cols, vals):
        rr.append(row('dentistry-11-00197-t002', r, c, v, sd, dict(pulp_condition=cond, bur_use=wear, time_min=t), 'degC', n=5))
add('L09', 'PMC10453045', 'Drill history and cooling → temperature in the pulp chamber', 'DENT-PROC-PREP-THERMAL', 'draft_node', 'SIMULTANEOUS', 'A no-cooling temperature-rise anchor does not provide the cooled time course or distinguish bur-use history.', '30 extracted upper monoradicular teeth; 6 cells of n=5, repeated measurements at 0/1/3 min; 50 mL/min water at 20±0.5 C, ≥2 mm residual dentin, room ~25 C, k-type thermocouple.', '90 observations are not 90 teeth. Table 3 reports bur p=.005 but abstract says no effect; Table 4 says fourth use while methods/Table2 say fifth. Do not infer causal bur effect or living-pulp injury; no covariance provided for repeated differences.', rr, quantity='pulp_chamber_temperature', method_xpath='/article/body/sec[2]', method_terms=['50 mL/min', '20 °C', 'minimum of 2 mm', 'thirty'], unit_table=None, unit_term='°C')
rr = [row('T3', r + 3, c + 2, v, sd, dict(sintering=s, thickness_mm=th, aging='134 C / 2 bar / 5 h'), 'CIE_TP_unit', n=10) for (r, (s, arr)) in enumerate([('standard', [(16.46, 1.09), (12.7, 0.62)]), ('speed', [(16.61, 1.35), (11.84, 0.45)])]) for (c, (th, (v, sd))) in enumerate(zip([0.5, 1], arr))]
add('L10', 'PMC10088447', 'Sintering schedule and thickness → measured translucence', 'DENT-MAT-TRANSLUCENCY', 'draft_node', 'HANDOVER', 'A zirconia-type-only translucency scalar omits thickness, schedule and aging.', 'Katana HT discs Ø12 mm; n=10/thickness × sintering arm; ST 1500 C/120 min hold, SP1515 C/30 min hold; all aged 134 C/2 bar/5 h; published CIE translucency parameter.', 'Methods reverse black/white L* labels and display an anomalous exponent in TP formula; reported table values are retained, no recalibration from raw spectra. Grain size measured on one separate specimen/arm; not pooled as independent material replicates. No shrinkage law inferred.', rr, quantity='reported_translucency_parameter', method_xpath='/article/body/sec[2]', method_terms=['n = 10', '134°C', '5 h', '1500'], unit_table='T3', unit_term='CIE')
rr = [row('materials-17-01496-t001', r + 2, 2, v, sd, dict(material='Resilab Temp', postcure_min=t), 'MPa', n=9) for (r, (t, v, sd)) in enumerate([(0, 15.9, 3.8), (16, 80.5, 3.2), (32, 76.5, 1.6), (60, 83.2, 2.2)])]
add('L11', 'PMC11012777', 'Post curing → temporary resin bending strength', 'DENT-MAT-RESTORATIVE-PSP', 'draft_node', 'HANDOVER', 'No postcuring-conditioned Resilab Temp benchmark in prior links. A material name lacks the cure state.', 'Resilab Temp lot1582; n=9/group; printed bars25×10×3 mm, span20 mm; 0/16/32/60 min postcure; three-point bend.', 'Flexural methods name W3D printer whereas general methods name Anycubic. Aging of hardness/optics is explicit; flexural table aging state is unresolved. Table shows 16 min >32 min, contradicting blanket monotonic-strength interpretation. No patient-specific or universal resin coefficient.', rr, quantity='three_point_flexural_strength', method_xpath='/article/body/sec[2]', method_terms=['n = 9', 'W3D', '20 mm'], unit_table='materials-17-01496-t001', unit_term='(MPa)')
rr = [dict(xpath='/article/body/sec[3]/p[21]', number_index=i, value=v, sd=None, key=dict(layer_mm=l, orientation_deg=a), unit='MPa', n=4, statistic='reported_mean') for (i, v, l, a) in [(1, 56.8, 0.1, 0), (4, 58.5, 0.05, 0), (6, 58.0, 0.05, 90)]]
add('L15', 'PMC10007339', 'Height and direction → tensile stress in printed resin', 'DENT-MAT-RESIN-3DPRINT', 'draft_node', 'HANDOVER', 'A scalar resin strength omits layer and angle; original L02 flexural endpoint rejected.', 'NextDent C&B MFH BL lotXG283N23; ANYCUBIC Photon Mono X; tensile ASTM D638-14, 4 specimens/condition, loading5 mm/min. Only the 3 exact tensile mean values printed in results paragraph are imported.', 'Not a flexural test. SD/raw tensile curves not extracted from image; other angle groups not numerically established here. Thickness means printing layer, not specimen thickness.', rr, quantity='tensile_break_stress', method_xpath='/article/body/sec[2]', method_terms=['D638-14', '4 specimens', '5 mm/min'], unit_table=None, unit_term='MPa')
conflicts = [{'link': 'L01', 'kind': 'CONDITIONAL_RANKING', 'detail': 'Abstract says 45-degree highest; source table rankings depend on material and cure.'}, {'link': 'L04', 'kind': 'DISAGREE_SD', 'table_value': 51, 'abstract_value': 43, 'unit': 'N', 'policy': 'Table1 used with source conflict flagged.'}, {'link': 'L09', 'kind': 'BUR_EFFECT_AND_USE_INDEX', 'detail': 'Table3 p=.005 vs abstract no effect; Table4 fourth vs Table2 fifth use. No inferential bur claim admitted.'}, {'link': 'L10', 'kind': 'OPTICAL_METHOD_DEFINITION', 'detail': 'Black/white L* labels reversed and formula exponent anomalous. Tabulated empirical TP only.'}, {'link': 'L11', 'kind': 'PRINTER_AND_AGING', 'detail': 'General methods Anycubic vs flexural W3D; flexural aging unresolved; postcure trend not monotonic.'}]
for (name, obj) in [('LINK_CONTRACTS.json', C), ('SOURCE_CONFLICTS.json', conflicts)]:
    p = H / name
    p.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + '\n')
    (H / (name + '.sha256')).write_text(hashlib.sha256(p.read_bytes()).hexdigest() + '\n')
print('Curated', len(C), 'publication contracts;', sum((len(x['records']) for x in C)), 'numeric observation means')
