from pathlib import Path
import json
H = Path(__file__).resolve().parent
cs = json.loads((H / 'LINK_CONTRACTS_V2.json').read_text())
mechs = {'L01': ('Photon/thermal cure and printed interfaces leave a material state subsequently loaded as a three-unit FDP.', 'Q(material,angle,cure)=source mean of observed fracture load; F_fracture=max load before failure.', 'Conversion, defects and residual stress are not measured jointly; no cure-to-strength law identified.'), 'L03': ('Hydrothermal phase/damage history and cyclic preconditioning precede residual biaxial failure.', 'Q(material,aging)=reported biaxial strength after fixed cycle history.', 'Transformations and crack states unknown; destructive strength is not endurance.'), 'L04': ('Assembly loading/thermal history leaves joint and ceramic state for a later static test.', 'Q(history)=observed load at sudden capacity drop.', 'Unknown joint contact/phase state and inconsistent HL SD prevent a universal degradation coefficient.'), 'L05': ('Thread contact, settling and reused-screw history affect measured removal torque.', 'Delta T=T_after-T_baseline; preload conversion would need T=K*F*d.', 'K, friction and seating state not independently calibrated; stop at torque, not preload.'), 'L06': ('Sliding counterfaces remove enamel; registered scans estimate lost volume.', 'Q(pair,method)=reported volume loss; ideal observation V_loss=V_before-V_after.', 'Raw registration/volumes unavailable; bias and removal mechanism not separately identifiable.'), 'L07': ('Support construction changes motion and contacts during sliding, accompanying material loss.', 'Q(support)=source mean volume loss after fixed wear protocol.', 'Artificial PDL and geometric confounding; Periotest value is not a calibrated elastic modulus.'), 'L09': ('Cutting supplies heat while coolant removes it; pulp temperature is a time-indexed observation.', 'Q(pulp,bur,t)=reported thermocouple temperature; energy balance would require C*dT/dt=heat_in-heat_out.', 'No local thermal field, heat partition or living perfusion measured; use observed protocol only.'), 'L10': ('Sintering and aging change the optical/microstructural state before spectrophotometry.', 'Q(schedule,thickness)=reported TP.', 'No raw spectra; source background labels/formula conflict prevents independent optical reconstruction.'), 'L11': ('Cure state precedes three-point flexural response.', 'Source strength is load-derived; slender rectangular beam closure sigma=3*F*L/(2*b*h^2) requires source geometry/protocol.', 'Printer and flexural aging ambiguities retained; cure time is not complete absorbed-dose state.'), 'L15': ('Layer height/orientation create a directional as-printed state, later loaded in tension.', 'Engineering tensile stress=F/A; Q(layer,angle)=reported mean stress at break.', 'No interpolated angles or individual raw tensile responses; no transfer to flexural strength.')}
a = []
for c in cs:
    (m, e, u) = mechs[c['id']]
    a.append({'link_id': c['id'], 'claim_type': 'information_link', 'idea': c['title'], 'mechanism': m, 'equation': e, 'operation': 'Read exact primary cell/paragraph, retain full observation key, answer only matching queries.', 'representation': 'original value + SD/n + full condition key + locator/hash + resolution/timescale', 'assumptions': [c['scope'], c['limitations']], 'leaves': [{'name': 'Published observations', 'status': 'EXTERNALLY_MEASURED', 'locator': 'FACIT.json#' + c['id'], 'stop_argument': 'Furthest local primary data; no hidden raw replicates invented.'}, {'name': 'Exact information-state test', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'stop_argument': 'Finite keyed permutation/count test; exact identity checked.'}, {'name': 'Physical transfer to downstream design', 'status': 'UNKNOWN', 'stop_argument': u}]})
a.append({'link_id': 'L12', 'claim_type': 'information_link', 'idea': 'Retain observable pore tail alongside a family label', 'mechanism': 'Shape-family classification does not specify observed threshold exceedance count', 'equation': 'N_tail=sum_i indicator(d_i>=0.5 mm)', 'operation': 'Read each catalog row with units and identity; count only at consumer', 'representation': 'PER_POINT source pore records, SIMULTANEOUS morphology query; catalog-level aggregates separately tagged POPULATION', 'assumptions': ['Segmented diameters as reported; no physical pore-cause or fatigue transfer', 'Six scoped catalogs; not all process sets'], 'leaves': [{'name': 'EqDiameter per pore', 'status': 'EXTERNALLY_MEASURED', 'stop_argument': 'Original segmented measurement record; segmentation bias unmeasured.'}, {'name': '0.5 mm threshold', 'status': 'CONSTITUTIVE_CLOSURE', 'resolution_level': 'PHENOMENOLOGICAL', 'stop_argument': 'Inherited descriptive query cutoff; replace with paired XCT/fatigue threshold calibration if used for acceptance.'}, {'name': 'Moment-equal diameter triples', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'stop_argument': 'Exact positive dyadic values; same first two moments, different tail count.'}, {'name': 'Keyhole/LoF label and fatigue failure', 'status': 'UNKNOWN', 'stop_argument': 'Neither diameter nor statistical BIC alone supplies physical labels or mechanical pairing.'}]})
(H / 'DECOMPOSITION_PER_LINK.json').write_text(json.dumps(a, indent=2, ensure_ascii=False) + '\n')
