from pathlib import Path
import json, hashlib, datetime
H = Path(__file__).resolve().parent
x = {'lane': 'PROOF_LANE-infolink4', 'claim_type': 'information_link', 'created_at_utc': datetime.datetime.now(datetime.timezone.utc).isoformat(), 'parent': 'PREREG_INFOLINK4_R1.json', 'reason': 'Reading PMC10007339 methods showed tensile/compression tests rather than flexural tests. L02 remains rejected for wrong observable. New L15 asks for the reported tensile means at exact layer/orientation conditions; frozen before numerical extraction or sufficiency calculations.', 'added_candidate': {'id': 'L15', 'source': 'PMC10007339', 'question': 'Tensile break stress conditioned on layer thickness and build angle', 'consumer': 'DENT-MAT-RESIN-3DPRINT', 'source_locator': '/article/body/sec[3]/p[21]', 'unit': 'MPa', 'resolution_level': 'POPULATION', 'time_scale': 'HANDOVER', 'original_publication_already_read': True}, 'metric_tolerance_decision': 'All R1 thresholds unchanged. This is retrospective extraction, not a new physical prediction.', 'baseline': 'A single tensile strength regardless of layer/angle', 'falsifier': 'Paragraph not explicitly a tensile break stress or numerical/unit/context mismatch', 'cost': 'Included in demo timings; no fit or physical measurement', 'decomposition': 'Same leaf typing as DECOMPOSITION.json; tensile stress = load / measured cross-section under source test protocol; group mean does not identify individual strength.'}
p = H / 'PREREG_INFOLINK4_R2.json'
p.write_text(json.dumps(x, indent=2) + '\n')
(H / (p.name + '.sha256')).write_text(hashlib.sha256(p.read_bytes()).hexdigest() + '\n')
rejected = [{'id': 'L02', 'source': 'PMC10007339', 'reason_code': 'WRONG_OBSERVABLE', 'reason': 'No flexural test; tensile/compression study. Replacement L15 retains the new endpoint explicitly.'}, {'id': 'L08', 'source': 'PMC10478297', 'reason_code': 'PRIOR_ESTABLISHED_CONSUMPTION', 'reason': 'Tab3 all eight crown-fracture groups already extracted and independently checked by PROOF_LANE_GENCAD_FOUNDATION/LANE_XREVIEW_PROOF_LANE. No repeated link counted.', 'locator': 'results/LANE_XREVIEW_PROOF_LANE/RESULTS.md:33'}, {'id': 'L13', 'source': 'ohbinding.py', 'reason_code': 'PRIMARY_FACIT_NOT_LOCATED', 'reason': 'Read original old-cell YEN_1979 dictionary (periodontal mouse explants), but no local primary table located in scoped original-paper search. The cell assessment alone is not external reference.'}, {'id': 'L14', 'source': 'retention.py', 'reason_code': 'PRIMARY_FACIT_NOT_LOCATED', 'reason': 'Cell quotes Little/Riedel/Artun 1988 PMID3163221 but local primary full-text witness not located in scoped search; no retention coefficient imported.'}]
for (i, (s, old)) in enumerate([('ISO14801-RAW36', 'L01'), ('PARK2023 thickness', 'L02'), ('CBCT four-scanner sensitometry', 'L04'), ('glass-ceramic lower tail', 'L06'), ('Ti64 porosity-yield', 'L07'), ('lattice exponents', 'L11')], 1):
    rejected.append({'id': f'DUP{i:02}', 'source': s, 'reason_code': 'ALREADY_LINKED', 'reason': 'Already established in PROOF_LANE2; not reconstructed.', 'prior_link': 'DENT-PROOF_LANE2-INFOLINK-' + old})
(H / 'REJECTIONS.json').write_text(json.dumps(rejected, indent=2) + '\n')
print('R2 endpoint correction frozen; 10 explicit exclusions recorded')
