from dental_release.paths import expand as _release_expand
import json, hashlib
from pathlib import Path
from datetime import datetime, timezone
P = Path(__file__).resolve().parent

def save(name, obj):
    p = P / name
    if p.exists():
        raise RuntimeError('Never overwrite preregistration: ' + name)
    obj['frozen_at_utc'] = datetime.now(timezone.utc).isoformat()
    p.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + '\n')
    (P / (name + '.sha256')).write_text(hashlib.sha256(p.read_bytes()).hexdigest() + '  ' + name + '\n')
base = {'lane': 'X17-sleep-apnea', 'parent': 'chains_brainstorm/03_ortho_occlusion.md O16', 'capability': 'A lab can query the minimum annotated pharyngeal cross section and location versus specified incisor advancement, with explicit uncertainty and acquisition requirements.', 'obstacle': 'Expert pharynx labels measure one open-bite scan; tissue transfer, posture, clinical ROI and true condyle landmarks are not measured.', 'consumer': 'Prosthodontic / MAD research lab; geometric research only, no AHI prediction or treatment selection.', 'external_referent': {'kind': 'independent_measurement', 'locator': 'doi:10.1007/s00784-023-05186-w; local europepmc/fulltext/PMC10492877.xml Tables 2 and 4', 'compared_quantity': 'paired group mean minimum cross-sectional area mm2; advancement mm; AP and lateral diameter mm; volume cm3', 'refutes_us': True}, 'source_aware_retrospective': True, 'cost_contract': {'preparation': 'source search, protocol and code time reported separately; acquisition already performed by dataset authors, not free', 'fit': 'none in R1; scenario intervals are constitutive assumptions', 'discovery': 'all tried gates retained', 'validation': 'analytic cuboid volume / pose / zero intervention / injected errors', 'queries': 'profile arrays and LP CPU seconds', 'fallback': 'UNKNOWN if landmarks, crop, or tissue transfer inadequate; no new scans performed', 'memory': 'measured process peak; threads <=4; own intermediate <=3GB; no GPU'}}
if __name__ == '__main__':
    r = dict(base, round='R1', changed_operation='Read untouched expert label-7 masks as measured cross-section profiles; propagate mandibular rotation + translation into an explicit anterior-wall transfer scenario.', cases=[f'ToothFairy2F_{i:03d}' for i in range(1, 13)], metrics={'voxel_volume_relative_error': {'tolerance': 1e-10, 'pass': 'all cases'}, 'zero_motion_area_error_mm2': {'tolerance': 1e-09, 'pass': 'all cases'}, 'pose_incisor_advancement_error_mm': {'tolerance': 1e-09, 'pass': 'all poses'}, 'area_point_reconstruction_relative_error': {'tolerance': 0.2, 'pass': 'each of the two published groups'}, 'usable_scenario_relative_width': {'tolerance': 0.5, 'pass': 'at least 80% of eligible cases at 6 mm'}, 'baseline_strength': 'proportional volume control gets exact same computed final volume; reference comparator gets published final volume; no claim of clinical validation on different TF2 individuals'}, strongest_equally_informed_control='A_control(z)=A0(z)*V_scenario/V0 at fixed sampled length; same label, pose, interval and resultant volume. Standard voxel-slice counting verifies baseline.', falsifiers=['Incorrect volume / zero-motion / commanded pose', 'Published AP-only reconstruction or volume control fails 20% area gate', 'More than 20% of cases have >50% response-interval width; no identifiable prediction', 'Unknown clinical ROI or condyle proxy cannot support clinical area claim'], protocol={'pharynx_label': 7, 'jaw_label': 1, 'lower_incisors': [31, 41], 'upper_incisors': [11, 21], 'case_selection': 'first 12 F IDs without outcome selection; missing inputs retained as exclusions', 'largest_component': '6-neighbour connectivity; retained fraction reported', 'plane': 'scanner array z planes; orientation signs from teeth; unreliable TransformMatrix ignored; anatomical palatal alignment UNKNOWN', 'endpoint_margin_mm': 5, 'endpoint_sensitivity_mm': [3, 5, 8], 'minimum_area_support_mm2': 1, 'advancement_mm': [0, 2, 4, 6, 8, 10], 'rotation_degrees': [0, 2, 4, 6], 'tissue_transfer_fraction': [0, 0.25, 0.5, 0.75, 1], 'anterior_support': 'each occupied lateral column is stretched anteriorly, posterior endpoint fixed; added area = occupied lateral width * effective anterior displacement * transfer', 'pose': 'rotation about array LR axis and posterior-superior bilateral jaw proxy midpoint; anterior translation solved to preserve commanded incisor advancement', 'bounds_status': 'conditional scenario envelope, NOT unconditional physical lower/upper bounds; lateral walls, tongue/hyoid, respiration and sleep posture unknown', 'large_arrays': _release_expand('@DENTAL_WORK_ROOT@/X17-sleep-apnea/; store cropped arrays only')})
    save('PREREG_R1.json', r)
    leaves = [('voxel area/volume', 'DERIVED_UNDER_ASSUMPTIONS', 'A_i=n_i dx dy; V=sum_i A_i dz; exact for voxel-cell representation', 'Stop at acquisition resolution; boundary partial volume and annotation uncertainty not measured.'), ('label geometry', 'EXTERNALLY_MEASURED', 'ToothFairy2 expert labels; local dataset.json CC-BY-SA 4.0', 'Re-segmentation requires original CT / expert validation; masks are input measurement, not new automated segmentation.'), ('plane and extent', 'UNKNOWN', 'TF2 FAQ says direction metadata inaccurate; epiglottis/palatal plane not labeled', 'Array-plane profile and fixed endpoint trims cannot establish clinical CSAmin; require anatomical landmarks.'), ('rigid jaw motion', 'DERIVED_UNDER_ASSUMPTIONS', 'q_new=R_x(theta)(q-c)+c+t; t_AP=m-[R_x(theta)(I-c)-(I-c)]_AP', 'Mandible treated rigid; actual condyle motion is not observed.'), ('condyle location', 'CONSTITUTIVE_CLOSURE', 'posterior-superior bilateral jaw centroids as geometric proxy', 'True condyle / joint axis not labeled; proxy sensitivity does not validate joint mechanics.'), ('tissue transfer', 'CONSTITUTIVE_CLOSURE', 'dA_i=L_i*kappa*d_AP_i, 0<=kappa<=1', 'No tongue, lateral wall, hyoid, pressure or muscle stiffness data identify kappa; bounds conditional.'), ('minimum observable', 'DERIVED_UNDER_ASSUMPTIONS', 'A_min(m)=min_i[A_i+L_i*kappa*d_i(m)]; argmin can switch', 'Min is nonsmooth at bottleneck change; preserve full profile rather than one scalar.'), ('sleep response', 'UNKNOWN', 'No map from waking area to AHI used', 'Requires dynamic mechanics and PSG; local geometry cannot validate AHI.'), ('independent area check', 'EXTERNALLY_MEASURED', 'Shi 2023 Tables 2/4 group means at 9.2 and 8.0 mm', 'Group means are unpaired across dimensions and plane of minimum can move; analytic reconstruction not individual prediction.')]
    (P / 'DECOMPOSITION.json').write_text(json.dumps({'chain': 'idea -> moving boundary mechanism -> voxel/rigid equations -> profile deformation -> profile plus pose representation -> explicit leaves', 'leaves': [dict(name=a, status=b, relation=c, stopping_argument=d) for (a, b, c, d) in leaves]}, indent=2) + '\n')
    (P / 'GOAL_TO_STRESS_POINT.md').write_text('# X17 parent capability\n    Research-grade MAD design would require a patient-specific airway response curve with a defensible error bound, manufacturable jaw pose and independent validation.\n    A single open-bite CBCT supplies the boundary at one pose, but not its motion or compliance. Geometry, clinical ROI and mechanics are separate obstacles.\n    R1 reads new anatomical information and constructs a conditional boundary-motion envelope. Rigid-jaw motion does not determine soft-tissue motion.\n    A wide envelope must lead to acquisition / representation change rather than more parameter sampling. The parent capability remains open.\n    ')
    print('R1 protocol frozen')
