"""Render only measured replay outcomes and exact independent review scope."""
from dental_release.paths import expand as _release_expand
import json
from pathlib import Path
from prepare_replay import HERE, sha, write

def read(p):
    return json.loads(Path(p).read_text())

def time_text(value):
    return f'{value:.3f} s'

def main():
    contract = read(HERE / 'FROZEN_FRONT_X86B.json')
    ledger = read(HERE / 'raw/x86b/FRONT_REPLAY.json')
    runs = {r['demo_id']: r for r in ledger['records']}
    hashes = {r['demo_id']: r for r in ledger['hashes_after']['records']}
    assert set(runs) == set(contract['front_ids']) and len(runs) == 12
    seconds = ledger.get('wall_seconds', ledger['wall_seconds_before_report'])
    original = (HERE / 'raw/x86b/history/FRONT.md').read_text()
    prefix = original.split("## Run 96 demon")[0]
    paragraph = _release_expand(f"## Run them 12 frontdemon med ett kommando\n\n```bash\ncd @DENTAL_IMPLEMENTATIONS@/X86_FRONT12\n./run_demos.sh\n```\n\n**{ledger['pass_count']}/12 PASS · {ledger['failure_count']} run/grind error · {time_text(seconds)} total kommandotid.** Timeout **3 600 s**. not more than four numerical threads. PASS means that the original limits of the specified driving profile are maintained. FAIL and UNKNOWN in the table remains. R3, GENCAD V6 and milling access uses short controls and frozen data; others run their existing packaged profiles. R3:s 72 results are not recalculated. [Precise profiles and times](ALL_DEMOS.md) · [fresh receipts](raw/x86b/FRONT_REPLAY.json).\n\nThe sample is exactly the twelve operations below.3 belongs to history and hash-checked; its R4 is run. The interrupted 97-the round is kept as history. **{ledger['hashes_after']['pass_count']}/{ledger['hashes_after']['checked']} frozen resulthashashashasa tally**, including three new reviewed versions and hunting3Rejected version. **88** demo-/statusversioner har **enbart hashkontroll i denna runda**, no numerical rerun. A hash-PASS applies to retained prey. [Hashkvitton](raw/x86b/RESULT_HASHES.json).\n\nEach run gets a new writeable package instance and shared write-protected local input. Linux, bubblewrap and existing Python environments are required; installation on empty workstation is untested. Four operating R7-bindings are used in the copy; the original numerical requirements are retained.86b-delivery pending independent review.26–27:s INTE_REDO referred to previously unfinished snapshots and does not change here.\n\n## Try the sub-surgical surgery that the lab can use\n\n| Run the operation | Delimited result | Proven / calibrated / modeled / unknown | rerun X86b / profil | Tid |\n|---|---|---|---|---|\n")
    old_table = original.split("## Try the sub-surgical surgery that the lab can use")[1].split("Power issues retain")[0]
    row_text = {}
    for line in old_table.splitlines():
        if line.startswith('| `./run_demos.sh '):
            ident = line.split('`./run_demos.sh ', 1)[1].split('`', 1)[0]
            if ident in runs:
                row_text[ident] = line.rstrip().rstrip('|').rstrip()
    assert set(row_text) == set(runs)
    row_text['GENCAD_V6'] = row_text['GENCAD_V6'].replace("Separate **247 / 1 728** roof questions and **2 / 18** full crown slots with spatial contact.", "If you have a fixed pose, **247 / 1 728** roof questions and **2 / 18** full crown seats. The separate R5 sample over all displacements provides **0/1 728** and **0/18** distinguishing queries and no passed suggestions.")
    for ident in contract['front_ids']:
        r = runs[ident]
        profile = 'snabb kontroll + hash' if ident in ['PROOF_LANE_FULL_CROWN_R3', 'GENCAD_V6', 'X53'] else 'befintlig paketprofil'
        mismatch = '0 mismatch' if r['mismatch_count'] == 0 else 'mismatch UNKNOWN' if r['mismatch_count'] is None else str(r['mismatch_count']) + ' mismatch'
        paragraph += f"{row_text[ident]} | **{r['status']}**, {mismatch}; {profile} | {time_text(r['wall_seconds'])} |\n"
    latest = "\n## Latest reviewed versions — hash checks in this round\n\n| Version | What the Review Decides | X86b / knowledge limit |\n|---|---|---|\n"
    new_rows = {r['demo_id']: r for r in contract['rows'][-3:] + contract['rejections']}
    descriptions = {'PROOF_LANE_FULL_CROWN_DIAG': ("HOLDS_WITH_CORRECTION: **0/72** form+funktion; **10/72** Natural bilateral pair is a digital reference observation.", "Granskning26 recalculated existing measurements at: **694,530 s**, maxavvikelse **0 mm**Five weak controls were corrected. Clinically accepted couples and physical contact **UNKNOWN**."), 'PROOF_LANE_FULL_CROWN_R4': ("HOLDS_WITH_CORRECTION: **0/108** tekniska konjunktioner. Formpass **5/6 molar, 6/6 premolar, 1/6 anterior**; wall **0/6** per typ.", "Original exteriors miss virtual wall requirements **18/18**. Granskning27 ran three fresh exports; copy codedhash was corrected. **No parade improvement against R1–R3** is shown; C/D are adaptive on the same test set."), 'LANE_XBREAK_HUNT_3': ("**REJECT / INTE_REDO** i granskning25, latest existing decisions for hunting3; no replacement review in batch26–27.", "**1,019891 N** reproduces in beam scenario. Exact summary test, independent assembly measurement and agreed demo format are missing."), 'LANE_XBREAK_HUNT_4': ("HOLDS_WITH_CORRECTION i granskning27: source rituals in **7 rundor** supports; robust **5 %** prognoskrav faller.", "**R7 exakt sammanfattning FAIL**: max identitetsfel **2,842170943040401e−14 min**. Category-disaggregated first moment is the minimum extension of the Medieval question. **target_id=null**, graph recording blocked; no clinical recommendation.")}
    for ident in ['PROOF_LANE_FULL_CROWN_DIAG', 'PROOF_LANE_FULL_CROWN_R4', 'LANE_XBREAK_HUNT_3', 'LANE_XBREAK_HUNT_4']:
        r = new_rows[ident]
        h = hashes[ident]
        (desc, limit) = descriptions[ident]
        review = Path(r['independent_review_binding']['review_locator']).relative_to(HERE.parent)
        latest += f"| [{ident}](../{review}) | {desc} | **{h['status']}**, {time_text(h['wall_seconds'])}; **no new rerun**. {limit} |\n"
    suffix = "Power issues retain" + original.split("Power issues retain", 1)[1]
    start = 'De starka kontrollerna reproducerar'
    if start in suffix:
        (before, tail) = suffix.split(start, 1)
        rest = tail.split("## Maintain the divestiture and knowledge boundaries", 1)[1]
        suffix = before + "The strong controls reproduce the height/power responses within the frozen tolerances. No algorithm advantage is claimed. Two administrative state has exactly the same **12 identities, profiles and frozen result expectations**: the summary byte and floating point identity errors are **0**. An injected error receipt changes the original approval with **1**. For this particular couple, the smallest extension is a piece of approval. Identity and hash expectations are therefore not enough without actual validation. It is an administrative witness, no physical conclusion. [Satisfactory tests and misinjections executed](raw/x86b/FRONT_REPLAY.json).\n\n## Maintain the divestiture and knowledge boundaries\n" + rest
    suffix = suffix.replace('Av **8** nya versionsgranskningar', 'I den tidigare batch23–25-utvidgningen: av **8** versionsgranskningar')
    suffix = suffix.replace("![Execution scope, runtime and laboratory queries](PACKAGE_AND_LAB.png)", "![The twelve run profiles and their actual times](PACKAGE_AND_LAB_X86B.png)")
    (HERE / 'FRONT.md').write_text(prefix + paragraph + latest + '\n' + suffix)
    lines = ["# All demos: actual rerun and frozen results", '', f"X86b ran **{ledger['pass_count']}/12 PASS**, {ledger['failure_count']} error in **{time_text(seconds)}** med 60All times are observed. PHENOMENOLOGICAL driving costs. Three new revised versions are included in the hash-bound overview; hunting3 redovisas separat som avvisad.", '', "PASS applies to the application gate of the existing running profile. HASH_PASS means exchange identity without numerical rerun. No physical knowledge status is changed by these labels. Historical attempts are found in raw/prior_runs and raw/x86b/history; their times and outcomes are not used as fresh PASS.", '', "| ID | Question / Results | Knowledge level and resolution | Granskning | X86b faktiskt utfall | Profil / tid |", '|---|---|---|---|---|---|']
    for row in contract['rows'] + contract['rejections']:
        ident = row['demo_id']
        h = hashes[ident]
        r = runs.get(ident)
        if r:
            count = 'UNKNOWN' if r['mismatch_count'] is None else str(r['mismatch_count'])
            status = f"**{r['status']}**; mismatch {count}; {h['status']}"
            profile = 'snabb kontroll + frysta data' if ident in ['PROOF_LANE_FULL_CROWN_R3', 'GENCAD_V6', 'X53'] else 'befintlig paketerad profil'
            timing = f"{profile}; {time_text(r['wall_seconds'])}; [fresh receipt](raw/x86b/FRONT_REPLAY.json)"
        else:
            status = f"**{h['status']}**; {h['mismatch_count']} hashmis match; not overtaken"
            timing = f"endast resultathash; {time_text(h['wall_seconds'])}; [hashkvitto](raw/x86b/RESULT_HASHES.json)"
        review = row['delivery_review_status']
        if row.get('independent_review_binding'):
            rp = Path(row['independent_review_binding']['review_locator']).relative_to(HERE.parent)
            review = f'[{review}](../{rp})'
        lines.append(f"| `{ident}` | {row['label']}; {row['reader_result']} | {row['knowledge_status']}; {row['resolution']} | {review} | {status} | {timing} |")
    lines += ['', "Network's R3 is hashically controlled and maintains its negative completeness gate. NET_R4 is the executed successor. Jakt3 is still rejected. Jakt4 : s exact numerical adequacy requirements fails and graph targets are missing. X86b : s own independent review is PENDING ."]
    (HERE / 'ALL_DEMOS.md').write_text('\n'.join(lines) + '\n')
    result = {'schema': 'dental-sunday-refresh/v2', 'round_tag': 'X86b-sunday-refresh', 'claim_type': 'capability', 'review_state': 'PENDING_INDEPENDENT_REVIEW', 'outcome': ledger['status'], 'capability': 'One command runs exactly12 bounded front profiles in clean writable copies; other frozen results are hash-verified and latest review scopes are bound', 'front_pass_count': ledger['pass_count'], 'front_requested': contract['front_ids'], 'front_failure_count': ledger['failure_count'], 'command_wall_seconds': seconds, 'wall_budget_seconds': 3600, 'hashes_checked': ledger['hashes_after']['checked'], 'hash_pass_count': ledger['hashes_after']['pass_count'], 'hash_mismatch_count': ledger['hashes_after']['mismatch_count'], 'eligible_registry_count': len(contract['rows']), 'eligible_hash_only_count': len(contract['rows']) - 12, 'rejected_version_count': 1, 'physical_measurements': 0, 'scientific_status_promotions': 0, 'status_counts': {'EXIST': 7, 'DELVIS': 39, "REFUTED": 2, 'FORSKNING': 3, 'SAKNAS': 1}, 'external_referent': {'kind': 'external_review', 'locator': [str(HERE.parent / f'LANE_XREVIEW_BATCH{b}/RESULTS.md') for b in [25, 26, 27]], 'compared_quantity': 'Version-specific independent verdicts, correction scope and demo readiness; source numerical claims remain limited to their original referents', 'refutes_us': True}, 'resolution': 'PHENOMENOLOGICAL package counts and runtimes; original scientific levels retained per row', 'time_scale': 'SIMULTANEOUS reader/evidence binding; fabrication-to-measurement remains HANDOVER', 'package': ledger, 'rows': contract['rows'], 'rejections': contract['rejections'], 'frozen_contract': {'path': str(HERE / 'FROZEN_FRONT_X86B.json'), 'sha256': sha(HERE / 'FROZEN_FRONT_X86B.json')}, 'limitations': ['R3 quick profile does not rerun all72 scores or generators; other cache/profile limitations retained', '88 other eligible versions and rejected jakt3 receive only frozen-result hash checks', 'Installed environments and local immutable data required; clean OS untested', 'Whole crown physical function, real patient force and fabricated-vs-predicted calibration unknown', 'Jakt4 exact summary witness FAIL; target coverage missing; no scientific admission'], 'dropout': {'old_registry_not_rerun': {'n': 85, 'total': 97, 'fraction': 85 / 97, 'reason': 'Explicit user scope: only12 front demos'}, 'new_version_not_rerun': {'n': 3, 'total': 3, 'reason': 'Added as reviewed hash-only versions'}, 'rejected_latest_versions': {'n': 1, 'total': 4, 'reason': 'Jakt3 remains REJECT; preserve failures'}, 'execution_failures': ledger['failure_count'], 'hash_failures': ledger['hashes_after']['mismatch_count']}, 'sufficiency': ledger['faults']['sufficiency'] if ledger['faults'] else None}
    write(HERE / 'results.json', result)
    (HERE / 'RESULTS.md').write_text(f"# Tolv labboperationer med versionsbundna granskningsbesked\n\nThe front of the Sunday package has exactly twelve driving profiles and reports review26–27:s helkrona and hunting4 samt jakt3:s fortsatt avvisade granskning25-version. The comparison's external reference observations are the exact independent REVIEW-the files, not your own physical measurements.\n\n| Administrative measure (PHENOMENOLOGICAL) | Faktiskt utfall |\n|---|---|\n| Fresh original profiles | {ledger['pass_count']}/12 PASS; {ledger['failure_count']} fel |\n| Total command time / limit | {time_text(seconds)} /3 600 s |\n| Frysta resultat, inklusive avvisad jakt3 | {ledger['hashes_after']['pass_count']}/{ledger['hashes_after']['checked']} HASH_PASS |\n| Other valid versions | 88 HASH_ONLY; no rerun |\n| Physical measurements/Knowledge Status Changes | 0/0 |\n\nR3 ran existing spatial and squirrel controls, exact summary witness and independent table audit. All998 release entries and29 externa beroenden hashkontrollerades. Dess72 results and three generators were not recalculated. GENCAD V6 and X53 use their packaged short control profiles. The others run their existing packaged profiles; the internal caches documented limitations apply.\n\nTwo permits have byteidentical12 identiteter/profiler/frysta expectations, identity errors exactly0; injected error receipt causes downstream difference1The minimum extension for the couple is a validation piece. Receipt, identity and resulthash controls have run wrong injections. This administrative witness does not give a physical conclusion.\n\nHelkrona DIAG/R4 retains0/72 respektive0/108 fulla pass. Jakt4:s R7-witnesses fall on machine identity despite nominal conformity; target_id is null. Hunting3:s1,019891N is a model scenario with missing mounting facit and demo format. All deflections are preserved.4-improvement against R1–R3 is not established.\n\nAll data are local. The earlier interrupted97-rounding and negative attempts remain; nothing old PASS have been reused as fresh rerun. [Faktiska profiler/tider](ALL_DEMOS.md), [Coated white light](raw/x86b/FRONT_REPLAY.json), [fryst urval](FROZEN_FRONT_X86B.json).\n")
    licenses = "| Local source | License / boundary |\n|---|---|\n| Liu/Hao Demo1 | CC BY 4.0 |\n| Open-Full-Jaw | CC BY-NC-SA 4.0 |\n| Bits2Bites | CC BY - NC - SA ; local version conditions apply |\n| RadRepro | CC BY 4.0 |\n| STS | CC BY 4.0 |\n| ToothFairy2 | CC BY - SA ; local release applies |\n| Mandibeldefekter | CC BY 4.0 |\n| Teeth3DS, Bite2Text, Pulpy3D | UNKNOWN in affected snapshot bindings; check local source ; no new spread state |\n| Publicerade tabellutdrag | Conditions of each article; exact table locators per demo |\n"
    (HERE / 'README_DEMO.md').write_text(_release_expand(f"# Select and try a lab operation\n\nFrom the same anatomical geometry to CAD, model response and production/measuring question: the package allows a prosthetic researcher to test twelve examined sub-operations with a command. [FRONT.md](FRONT.md) shows what each operation can actually determine and the physical measurement that remains.\n\n```bash\ncd @DENTAL_IMPLEMENTATIONS@/X86_FRONT12\n./run_demos.sh\n```\n\n| Utfall | Measured here |\n|---|---|\n| Twelve fresh driving profiles | {ledger['pass_count']}/12 PASS; {ledger['failure_count']} fel |\n| Kommandotid med3 600s limit | {time_text(seconds)} |\n| Frysta resultathashar | {ledger['hashes_after']['pass_count']}/{ledger['hashes_after']['checked']} correct |\n| Egna tillverkade prov mot fryst fysisk prediktion | 0 |\n\nPASS applies to the program approach in the specified profile. R3, GENCAD V6 and X53 run short checks on frozen data. Other versions are hash checked without numerical rerun. All profiles and measurement costs are [redovisade per demo](ALL_DEMOS.md)External reference observations are the version-bound independent reviews and respective demos source measures, never a new physical patient measurement.\n\nWhat doesn't last: the shape of the crown +funktion/tekniska conjunction is fortsatt0/72 respektive0/108Patient force is UNKNOWN. Jakt3 is rejected.4:s exakta R7No physical force calibration or produced crown is validated in this delivery. Rigorous physical and floating-point closure is missing where the original model does not deliver it.\n\nLinux, bubblewrap, local datasets and pre-installed Python environments required; clean OS-installation is untested. Driving uses new printable copies, up to four numerical threads,60-minute limit and3GB eget mellanledstak inklusive bevarad X86-historic. No datasets are retrieved. For an individual profile, for example, `./run_demos.sh X82`; same twelve-identity limit applies.\n\n{licenses}\n![Actual times for the twelve profiles](PACKAGE_AND_LAB_X86B.png)\n"))
    print('FRONT/ALL_DEMOS/README/RESULTS updated:12 profiles,100 eligible versions,1 rejection')
if __name__ == '__main__':
    main()
