'Manually curated semantic mapping; computes no dental physics values.'
from dental_release.paths import expand as _release_expand
import json
from pathlib import Path
ROOT = Path(_release_expand('@DENTAL_INPUT_ROOT@/workspace'))
HERE = Path(__file__).resolve().parent
REG = {}

def ref(key, path, klass, needle=None, kind='independent_review'):
    snap = HERE / 'raw/source_snapshot' / path
    lines = snap.read_text().splitlines()
    line = next((i + 1 for (i, x) in enumerate(lines) if needle and needle in x), 1)
    REG[key] = {'key': key, 'path': path, 'line': line, 'review_class': klass, 'kind': kind}
ref('SPEC', 'notes/NORTHSTAR_SPEC.md', 'INHERITED_UNREVALIDATED', kind='inherited_spec')
ref('LOG', 'tasks/sol_night/REVIEW_LOG.md', 'SCOPED_COORDINATOR_LOG', kind='coordinator_log')
ref('REST', 'results/PROOF_LANE_XREVIEW_RESTORATIVE/XREVIEW.md', 'ACCEPT_WITH_CORRECTION / ACCEPT', '| LANE_X3')
ref('CLIN', 'results/PROOF_LANE_XREVIEW_CLINICAL/XREVIEW.md', 'MIXED_SCOPED', '## X2')
ref('B2', 'results/PROOF_LANE_XREVIEW_BATCH2/XREVIEW.md', 'MIXED_SCOPED', '**X25')
ref('B3', 'results/LANE_XREVIEW_BATCH3/RESULTS.md', 'ACCEPTED / ACCEPTED_WITH_CORRECTION', '| X24')
ref('B4', 'results/LANE_XREVIEW_BATCH4/XREVIEW.md', 'DEMO_READY / DEMO_READY_WITH_CORRECTION', '| PROOF_LANE_GENCAD')
ref('B5', 'results/LANE_XREVIEW_BATCH5/RESULTS.md', 'ACCEPTED / ACCEPTED_WITH_CORRECTION', 'What holds:')
ref('B6', 'results/LANE_XREVIEW_BATCH6/XREVIEW.md', 'DEMO_READY_WITH_CORRECTION', '| LANE_X36')
ref('B7', 'results/LANE_XREVIEW_BATCH7/XREVIEW.md', 'DEMO_READY_WITH_CORRECTION', 'X38 round-trip')
ref('G1', 'results/LANE_XREVIEW_PROOF_LANE/XREVIEW.md', 'ACCEPT_WITH_CORRECTION; original demo NOT_READY', 'R2 six')
ref('G2', 'results/LANE_XREVIEW_GENCAD_V2/XREVIEW.md', 'REJECT / NOT_READY', 'All 360')
ref('AUD', 'results/LANE_AUDIT_3B_SOL/RESULTS.md', 'ACCEPTED / ACCEPTED_WITH_CORRECTION', 'Per lane:')
for (key, job) in [('AH', 'LANE_NIGHT_H_FIELD_T2_PDL'), ('AB', 'LANE_NIGHT_B_PROCESS_ASBUILT'), ('AF', 'LANE_NIGHT_F_REGISTRATION'), ('AI', 'LANE_NIGHT_I_DECISION_CERT'), ('AC', 'LANE_NIGHT_C_TOLERANCE_STACK'), ('AD', 'LANE_NIGHT_D_MUCOSA_SPECTRUM'), ('AK', 'LANE_NIGHT_K_LATTICE_MATERIAL'), ('AM', 'LANE_NEXT_M_SELFCAL_MILL'), ('AA', 'LANE_NEXT_A_CBCT_SELFCAL'), ('AL', 'LANE_NEXT_L_PULP_REALTIME'), ('AL2', 'LANE_NEXT_L2_PULP_COOLDOWN'), ('ANI', 'LANE_NEXT_I_LAB_TO_CLINIC'), ('ANH', 'LANE_NEXT_H_CERTIFIED_RULES'), ('ANG', 'LANE_NEXT_G_MANDIBLE_POSTOP')]:
    p = f'results/LANE_AUDIT_3B_SOL/REVIEW_{job}.json'
    if (HERE / 'raw/source_snapshot' / p).exists():
        d = json.loads((HERE / 'raw/source_snapshot' / p).read_text())
        ref(key, p, d.get('class', 'ACCEPTED'), '"reason"')
for (key, folder, filename) in [('X2', 'PROOF_LANE_XREVIEW_CLINICAL', 'REVIEW_LANE_X2_OCCLUSION_B2B.json'), ('X5', 'PROOF_LANE_XREVIEW_CLINICAL', 'REVIEW_LANE_X5_DECISION_SEG_ERROR.json'), ('X7', 'PROOF_LANE_XREVIEW_CLINICAL', 'REVIEW_LANE_X7_BITE2TEXT.json'), ('X10', 'PROOF_LANE_XREVIEW_CLINICAL', 'REVIEW_LANE_X10_SCANNER_GAP.json'), ('X13', 'PROOF_LANE_XREVIEW_RESTORATIVE', 'REVIEW_LANE_X13_CEMENT_GAP.json'), ('X14', 'PROOF_LANE_XREVIEW_RESTORATIVE', 'REVIEW_LANE_X14_SINTER_POSITION.json'), ('X16', 'PROOF_LANE_XREVIEW_BATCH2', 'REVIEW_JOB_LANE_X16_PULP_PROTECTION.json'), ('X23', 'PROOF_LANE_XREVIEW_BATCH2', 'REVIEW_JOB_LANE_X23_CROWN_WEIBULL_FLOOR.json'), ('X25', 'PROOF_LANE_XREVIEW_BATCH2', 'REVIEW_JOB_LANE_X25_ISO14801_RAW.json'), ('X24', 'LANE_XREVIEW_BATCH3', 'REVIEW_JOB_LANE_X24_CBCT_HU_CALIBRATION.json'), ('X26', 'LANE_XREVIEW_BATCH3', 'REVIEW_JOB_LANE_X26_DECIDABILITY.json'), ('X28', 'LANE_XREVIEW_BATCH3', 'REVIEW_JOB_LANE_X28_HEAT_OSSEO_HANDOVER.json'), ('X30', 'LANE_XREVIEW_BATCH3', 'REVIEW_JOB_LANE_X30_ROOT_CANAL_ATLAS.json'), ('X31', 'LANE_XREVIEW_BATCH3', 'REVIEW_JOB_LANE_X31_CLINICAL_ANSWERS.json'), ('X34', 'LANE_XREVIEW_BATCH5', 'REVIEW_LANE_X34_STL_DESIGN_GATE.json'), ('X36', 'LANE_XREVIEW_BATCH6', 'REVIEW_LANE_X36_META_REGRESSION.json'), ('X37', 'LANE_XREVIEW_BATCH6', 'REVIEW_LANE_X37_ALIGNER_MOVEMENT.json'), ('X38', 'LANE_XREVIEW_BATCH7', 'REVIEW_JOB_LANE_X38_EXPORT_GATE.json'), ('X39', 'LANE_XREVIEW_BATCH7', 'REVIEW_JOB_LANE_X39_MANUSCRIPT_BITE.json'), ('G3', 'LANE_XREVIEW_BATCH4', 'REVIEW_PROOF_LANE_GENCAD_V3.json'), ('IL3', 'LANE_XREVIEW_BATCH5', 'REVIEW_PROOF_LANE_INFOLINK3.json')]:
    p = f'results/{folder}/{filename}'
    d = json.loads((HERE / 'raw/source_snapshot' / p).read_text())
    klass = d.get('class') or d.get('decision')
    if d.get('demo_decision'):
        klass += f"; {d['demo_decision']}"
    ref(key, p, klass, '"decision"')
ROWS = []

def add(k, status, refs, metric, resolution, why, blocker, full_chain=False):
    ROWS.append({'k': f'K{k:02}', 'proposed_status': status, 'evidence_keys': refs.split(), 'main_number': metric, 'resolution': resolution.split(), 'rationale': why, 'remaining_requirement': blocker, 'claim_type': 'information_link', 'full_chain_reviewed': full_chain, 'uncertainty': 'See remaining requirements and reviewed scope; X43 estimates no new physical confidence intervals.'})
add(1, 'PARTIAL', 'LOG SPEC', 'Tooth IoU 0.733; vertex FDI 85.6% in 120 held-out Teeth3DS cases.', 'PER_TOOTH POPULATION', 'X11 adds segmentation of new IOS. Coordinator log reports the result; separate full K01 cross-review absent.', 'Solid closure and gingival surface with validated mm units; target scanner FDI/landmark reference.')
add(2, 'PARTIAL', 'X24 B3 AA', 'X24: two-anchor held-out error 146.507653 HU_ref; self-calibration R1 gave 869.283 MPa.', 'PER_SURFACE_REGION POPULATION', 'RadRepro phantom read as external measurement. Negative calibration gate strengthened; import/PSF components exist.', 'Protocol-matched low-density phantom and independent scanner/attenuation calibration, without reinterpretation as bone modulus.')
add(3, 'PARTIAL', 'X30 B3 B2', 'Atlas: 3449 teeth in 282 CT scans; FDI31 multiple-canal fraction 8/253 = 3.162%.', 'PER_TOOTH PER_SURFACE_REGION POPULATION', 'X12/X30 add outer tooth/pulp pairing and local canal geometry. External anatomy gate fails; labels reference geometry, not true enamel/dentin boundaries.', 'Independent DEJ/pulp/apex annotation and held-out subvoxel walls; retain X12 rejected original hash gate and package correction.')
add(4, 'PARTIAL', 'X5 CLIN', 'P_140: 11 injected voxels; gap 1.967231557 mm; Dice 0.999829682.', 'PER_SURFACE_REGION', 'X5 establishes that global Dice/HD95 cannot guarantee a local canal decision. No improved true nerve/bone boundary measured.', 'Micro-CT or independent local canal wall with scanner/metal error per point; sinus/foramen need separate references.')
add(5, 'PARTIAL', 'AF AUD', 'Hessian covariance: 0/120 covered poses with correlated noise.', 'PER_ARCH POPULATION', 'Reviewed registration operator exists, but IOS-CBCT pairing and CALIBRATED error absent. Registered IOS bites in X2 are another port.', 'Same specimen IOS+CBCT, surface reference and correlated pose/surface uncertainty.')
add(6, 'PRESENT', 'SPEC X5 CLIN', 'Inherited GEOM_UNC: 173 cases and 1.32 million boundary points; X5 local decision can reverse despite Dice 0.999829682.', 'PER_POINT PER_SURFACE_REGION POPULATION', 'Retain PRESENT for executable uncertainty field, not universal local maximum. X5 motivates the decision region.', 'Correlation length remains incomplete; full GEOM_UNC 173-case result is not revalidated here.')
add(7, 'PARTIAL', 'SPEC', 'Inherited SOFT_gingiva: 480 cases; lip contact 93%; result UNDETERMINED.', 'PER_ARCH POPULATION', 'No new reviewed delivery closes the gingival chain.', 'Paired IOS+CBCT with independent gingival thickness and free soft tissue boundaries.')
add(8, 'PARTIAL', 'X2 CLIN X7 X39 B7', '200 registered Bits2Bites pairs; 1600 all-triangle controls give maximum clipped distance error 0 mm.', 'PER_POINT PER_ARCH POPULATION', 'New actual antagonist replaces the sphere in scoped IOS bites. X7/X21/X39 also compare report categories.', 'Calibrated physical contact, independent tooth landmarks/FDI and actual jaw movement; registered scan bite is not loaded contact.')
add(9, 'MISSING', 'AH AUD', 'H4: 199 mixed boundary patches UNKNOWN; H25 control refinement difference 0.587786%.', 'PER_SURFACE_REGION PER_TOOTH', 'Local tooth/PDL carriers and separate native FE exist. Review explicitly states that the new bone collar/full patient field is not closed. X4 negative planning is not a multiregion SDF.', 'DATA: OFJ jaw+teeth+PDL with retained regions. CODE: shared multiregion SDF/ownership field, complete collar-to-bulk bone and region transfer. MEASUREMENT: ownership/interface/volume parity against source tets and physical response refinement; then more cases.')
add(10, 'PARTIAL', 'AH AUD', 'H25 separate native P2 control: maximum refinement difference 0.587786%; new carrier retains 199 boundary patches.', 'PER_SURFACE_REGION PER_TOOTH', 'Late review replaces uncritical H5 zero-identity argument: zero identity hid penetration, and control FE is not the new carrier response.', 'Complete collar/bulk trim, material incidence and thin-layer convergence on the same authoritative surfaces.')
add(11, 'PRESENT', 'SPEC G1', 'Inherited export p99 <=2 micrometres; reviewed GenCAD foundation: 29/29 fixtures after correction.', 'PER_POINT', 'Dental redistancing/offset/Boolean operations retained. GenCAD supplies scoped geometric witnesses; original dimensional errors preserved.', 'PRESENT concerns existing geometry operations, not clinical preparation or all field engine paths; A143 refutation remains.')
add(12, 'PARTIAL', 'X24 B3 AA', 'X24 held-out error 146.507653 HU_ref; CBCT self-calibration 487-869 MPa against external band 26-126 MPa.', 'PER_SURFACE_REGION POPULATION', 'Phantom measurement and self-calibration review strengthen the negative calibration component. Cortex component and executable E field keep overall status PARTIAL.', 'Same bone specimen CBCT/micro-CT/density plus mechanical testing and scanner protocol; HU_ref is not E.')
add(13, 'MISSING', 'AH SPEC', 'N/A: generic dental region-to-material register not established.', 'PER_SURFACE_REGION', 'Local PDL/material atlas is not a complete dental register with units/validity for every region.', 'DATA: version-locked region identities and source for each material law. CODE: total region-to-law/parameter/validity map rejecting missing owner/unit. MEASUREMENT: patch test and specimen-matched response for used laws; define register first.')
add(14, 'PARTIAL', 'X2 CLIN', 'X2 force profile MAE: upper jaw 10.393656 pp; lower jaw 18.249819 pp.', 'PER_TOOTH POPULATION', 'Real registered bite gives load geometry, but X2 support model fails external force distribution. It does not measure muscle direction or chewing phase.', 'Synchronous EMG/jaw movement/regional bite force in the same individual with muscle geometry.')
add(15, 'PARTIAL', 'SPEC X2 CLIN', 'Inherited load frequency band: 250-20000 events/year above 500 N; X2 area control MAE 4.878976/10.820288 pp.', 'POPULATION PER_TOOTH', 'External tooth force references now exist, but a one-time profile is not an annual patient load spectrum.', 'Time-recorded load spectrum, parafunction and separate force/cycle axes; no new measured spectrum in the 48h demos.')
add(16, 'MISSING', 'X2 CLIN X26 B3', 'X2: median 6 independent regional channels required; no MEASURED individual force.', 'PER_ARCH', 'Registered jaws, clinician text and published group forces are different quantities. They do not close patient load.', 'DATA: both jaws IOS/CBCT/bite with same deidentified specimen ID and force time series. CODE: region-bound observation model returning load with shared theta. MEASUREMENT: calibrated regional pressure/force image in same registered bite; total force alone is insufficient.')
add(17, 'PRESENT', 'SPEC AH AUD', 'PDL E 0.694/0.735/0.782 MPa; H25 maximum refinement difference 0.587786%.', 'PER_TOOTH', 'Retain PRESENT for scoped linear PDL law. Reviewed H4 control FE uses the same F1 law.', 'Temporal/nonlinear law and patient transfer remain closures; Keilig ramp is not a universal static modulus.')
add(18, 'PRESENT', 'SPEC AH AUD', 'Inherited FE_REFERENCE: 10.28 million DOF; H25: 1127148 free DOF and 0.587786% refinement difference.', 'PER_TOOTH', 'High-resolution reference solution exists; native control reviewed stable for its load. This does not validate a new carrier or all nonlinear load cases.', 'Linearity, new load cases and newly generated crowns need separate quality gates; original 10.28 M test inherited.')
add(19, 'PARTIAL', 'SPEC', 'Inherited MICRO_motion: prediction 5.9 times too low; no new reviewed CONTACT_law verdict.', 'PER_SURFACE_REGION', 'No relevant 48h result replaces incomplete contact law. Proximity maps and aligner forces are other interfaces.', 'Specimen-matched bone-implant contact with slip/BIC, load and stiffness; complete CONTACT_law with an actual verdict.')
add(20, 'PARTIAL', 'AC X25 B2', 'X25: 36 specimens, 23 failures/13 censored; tolerance stack certificates 593/606 within model.', 'PER_TOOTH PER_ARCH', 'New raw specimens enable assembly/fatigue analysis, but external cyclic load is not screw preload. Spatial stack lacks MEASURED screw mechanics.', 'Specimen-ID-linked screw preload/settling and contact law in jaw FE; no MEASURED preload loss in X25.')
add(21, 'MISSING', 'X2 CLIN X34 B5', 'X2: maximum numeric proximity error 0 mm; X34 contact witness 0.024999464385 mm at given pose.', 'PER_POINT', 'Proximity operator and geometric collision witness delivered. They do not provide deformable friction contact under observed load.', 'DATA: same antagonist/preparation and material/support. CODE: deformable contact/friction on these surfaces with force/moment balance. MEASUREMENT: calibrated loaded contact map and displacement, same pose; demonstrate rejecting stick/slip and penetration faults.')
add(22, 'PARTIAL', 'SPEC', 'Inherited BC_TMJ: 40 cases, eminence 40.1 degrees PASS and contact normal FAIL.', 'PER_ARCH POPULATION', 'No later reviewed delivery measures TMJ contact normal. IOS bite and airway scaling do not change this.', 'Condylar path/TMJ geometry with independent reaction or contact reference in the same frame.')
add(23, 'PARTIAL', 'X16 B2 X31 B3 B4', 'JET15 6.02+/-0.50 degrees C; JET30 2.24+/-0.46 degrees C; possible exceedances [11,20] and [0,0] in stated group specimens.', 'POPULATION', 'X16 gives protocol-bound temperature/event comparison, X31 conditional tissue budget and X33 negative local heat decidability. No own human RDT/pulp measurement.', 'Same specimen RDT/DEJ, tool path, sensor locations and MEASURED temperature/cooling; 5.5 degrees C is a reporting level, not clinical injury risk.')
add(24, 'PARTIAL', 'X28 B3', 'Regional ovine damage about 0.2-1.1 mm; cell viability contrast 37.59 pp and outgrowth ratio 3.483 after culture.', 'PER_SURFACE_REGION POPULATION', 'X28 builds an actual HANDOVER port from drilling history to residual tissue and separate source observations. Old heat magnitude remains refuted.', 'Torque/feed, actual local temperature and same specimen histology; different species/group metrics do not establish human safety or ISQ.')
add(25, 'PRESENT', 'SPEC X31 B3', 'Inherited guide apex error: median 0.55 mm, P95 1.14 mm; X8: 37/2581 class changes.', 'PER_TOOTH POPULATION', 'Retain existing guide error operator. X8/X31/X32 strengthen conditional relevance, but do not measure new sitewise nerve risk.', 'Signed guide/pose and canal error components on the same block; retain X8 original NOT_READY demo as a version.')
add(26, 'PARTIAL', 'SPEC', 'Inherited insertion torque: mean absolute log error 0.35 against area-scaled 0.32; cortex/cadaver 8-13 times too high.', 'PER_TOOTH POPULATION', 'No later reviewed delivery calibrates crushable bone law or actual insertion torque.', 'Same specimen cortex/trabecular bone, hole, torque/feed and crushing/contact response.')
add(27, 'REFUTED', 'SPEC', 'Inherited micromotion: magnitude 5.9 times too low.', 'PER_SURFACE_REGION', 'No reviewed 48h reference overturns refutation or repairs the controlling contact.', 'K19 with specimen-matched slip/stiffness and micromotion data; retest frozen magnitude gate.')
add(28, 'RESEARCH', 'AUD LOG', 'A dental contract uncalibrated; no reviewed pair of orders with same final geometry and measured history.', 'PHENOMENOLOGICAL', 'Dental heat bookkeeping and X28 HANDOVER add partial operations, but procedure order as a reviewed design variable is not delivered.', 'Two real step orders, same final geometry/work, measured heat/cooling; objective order search and consistent initial state.')
add(29, 'RESEARCH', 'SPEC IL3 B5', 'IL3: 30 retest rows among 138 fracture sites/99 physical specimens.', 'PER_POINT POPULATION', 'Fatigue history now has raw data, but is not material memory during preparation/resection. Older scalar history operator remains research.', 'Load -> cut -> new load on same material regions with validated viscoelastic/plastic dental law.')
add(30, 'REFUTED', 'SPEC ANI AUD', 'Inherited biological width result: 2/5 contrasts; three mechanostat variants refuted.', 'POPULATION', 'Cell outgrowth after drilling (X28) is neither marginal bone loss nor a repaired five-year mechanostat.', 'Independent MBL time series and mechanistic cause/load operator; BodyTwin BT-CTX-BIORESP, no surrogate transfer from cell viability.')
add(31, 'MISSING', 'X28 B3', 'X28: 3.483 times cell outgrowth at two weeks of culture; human healing/ISQ UNKNOWN.', 'POPULATION', 'Cultured bone fragment response is not implant BIC(t) or stability(t). New measurement port does not close K31.', 'DATA: implant-ID-linked longitudinal RFA/ISQ and BIC where possible, protocol/contact/bone/surface treatment. CODE: temporal osseointegration law carrying final drilling state. MEASUREMENT: independent held-out time series; culture days cannot substitute for healing days.')
add(32, 'PARTIAL', 'ANI AUD X23 B2', 'X23: held-out bar quantile pinball loss 45.1291507 -> 7.0411470 MPa; change to existing K32 risk 0.', 'POPULATION', 'Material population tail can be read, but older 0.54-0.96% concerned mixed-age lab remakes. Correct Weibull convention does not establish clinical five-year risk.', 'Clinical ceramic fracture per material/exposure, individual load spectrum and contact/SCG closure; total survival is another endpoint.')
add(33, 'PARTIAL', 'X25 B2 X38 B7', '10% risk at 5 million cycles: 99.9295-110.7077 N; 0/3 failures gives upper one-sided 95% risk 63.159685%.', 'PER_TOOTH POPULATION', 'Raw specimen/censoring analysis and explicit specimen count added. Process -> defect -> thread root force remains incomplete; K1B old strength refutation preserved.', 'Measured thread root/hole/defect/hardness/preload/load arm on same specimen and matched held-out risk validation; normalize old PARTIAL/REFUTED to PARTIAL with refuted component separate.')
add(34, 'MISSING', 'SPEC IL3 B5', 'N/A: no reviewed wear/LTD/corrosion operator on a dental antagonist pair.', 'PER_SURFACE_REGION', 'Fracture/fatigue data and first lattice load peak are different quantities; they cannot replace service-time degradation.', 'DATA: local antagonist material/pair, environment and measured time series. CODE: wear/aging/corrosion law with regional/history state. MEASUREMENT: three-body wear or scoped LTD/corrosion on same specimen; one measured pair before generalizing.')
add(35, 'PARTIAL', 'AD AUD', 'Bonded layer/Winkler choose different process profiles in 24/24 synthetic scenarios; LP reduces pressure spike 19%.', 'PER_SURFACE_REGION PHENOMENOLOGICAL', 'Reviewed mucosal operator exists. Later aligner data concern another tissue/construction and do not upgrade removable prostheses.', 'Paired edentulous intaglio/thickness/stiffness field under load, time-dependent support and retention/clasp wear.')
add(36, 'PARTIAL', 'G3 B4 REST LOG', 'X1: 45 variants/90 load cases, 7 Pareto marked; GenCAD R6: 0/8 pass exterior gate 0.35 mm.', 'PER_TOOTH POPULATION', 'Crown loop, actual antagonist and large digital roof benchmark delivered; anatomical full crown and calibrated physical risk remain negative/UNKNOWN.', 'Independent real preparation/finish line, contact load, batch/support and MEASURED fit; retain X1 -> X1B versions without rewriting original REJECT.')
add(37, 'PARTIAL', 'X5 CLIN B3', 'X8/X32: 37/2581 = 1.433553% sites change virtual 2 mm class.', 'PER_SURFACE_REGION PER_TOOTH POPULATION', 'Catalog/placement loop exists; local label and guide errors receive a reviewed decision metric. This is not observed clinical benefit or true support volume.', 'Local anatomy, bone/contact calibration and actual primary stability; mask-based augmentation requirement remains uncertain.')
add(38, 'PARTIAL', 'AC X10 CLIN', 'Stack certifies 593/606 model choices; X10: 150.7633 -> 96.0601 micrometres in composite scenario.', 'PER_ARCH PER_SURFACE_REGION', 'Spatial tolerance stack and signed scanner error were reviewed and executed. Aggregates and cone fixture are not MEASURED full arch misfit/screw mechanics references.', 'Paired signed scan/process/insertion errors and physical preload/contact with shared specimen provenance.')
add(39, 'PARTIAL', 'G3 B4 G1', 'GenCAD v3: 588 test case clusters/family; molar crown scoped LP PASS 0.724 [0.705;0.745].', 'PER_TOOTH POPULATION', 'Dental shape parameterization (affine height fields) with continuous geometric constraints and optimization connected. This changes the old no minimize/adjoint claim.', 'Full shape/topology/contact gradient and anatomical crown absent; v3 uses roofs, not density topology optimization. Requires FE/FD gradient reference, changed contact branch and specimen-matched preparation.')
add(40, 'PARTIAL', 'G1 G3 B4 AB', 'Foundation R2: 6 new milling passes for 2 preparations times 3 materials; lane B: 148/456 search queries abstain when as-built recipe absent.', 'PER_TOOTH PHENOMENOLOGICAL', 'Manufacturing constraints carry data inside scoped search, including access/recipe before selection. This is an actually connected partial operation.', 'V3 milling radius/shaft explicitly unscored; sintering/orientation/full CAM in shared physics search and MEASURED process reference remain.')
add(41, 'PARTIAL', 'AK AUD LOG IL3 B5', 'Gyroid tensor error 3.27/9.64%; Primitive permeability 8.95/10.04%; 0/108 implant design choices after numeric gates.', 'PER_SURFACE_REGION PHENOMENOLOGICAL', 'Shared pore geometry -> elasticity/flow and real bone field executed against external ideal references. No Ti fatigue, implant approval or physical AM transfer established.', 'Converged local contact on identical fixed domain; specimen-bound Ti XCT/statics/low-Re transport/fatigue. IL3 PLA peaks must not transfer to Ti.')
add(42, 'PARTIAL', 'AI X26 B3', 'Decision certificates: 39/39 real sites abstain; X26: 3648/4132 conditional class 1 and 484 class 2, 0 physical certificates.', 'PER_SURFACE_REGION PER_TOOTH', 'Calibration floor and next relevant measurement can be named. Digital CLASS 1 within a scenario is not clinical/physical acceptance.', 'Shared CALIBRATED theta, local wall/load and blind holdout for certificates; denominator and abstention must follow consumer.')
add(43, 'PARTIAL', 'X13 REST X14 B6', '148 measurement cells/11 studies; sintering angle RMSE 0.157848 degrees against 0.558 degrees position-independent control.', 'PER_SURFACE_REGION POPULATION', 'Regional gap and disc position add actual published measurement information. Angle model passes small table; cement transfer/physical seated gap remain.', 'Same design/preparation/process/scanned crown and regional signed seated gap. X14 89.4/56.9 micrometres are derived gaps; X36 cement transfer fails.')
add(44, 'PARTIAL', 'SPEC X13 REST', 'Inherited PC2 prior circular; X13 adds 148 MEASURED gap cells without validating patent inversion.', 'PER_SURFACE_REGION POPULATION', 'New measurements distinguish specified and measured gap but do not review hidden patent CAD gap as a parameter.', 'Independent nominal CAD gap and actual regional measurement, without same source on both sides; preserve patent cluster origin.')
add(45, 'PARTIAL', 'SPEC AD AUD', 'Inherited PC5: 97 -> 12 micrometres in one orientation case; D PC5 angle caused no process change.', 'PER_SURFACE_REGION PHENOMENOLOGICAL', 'Build direction operator exists; no new printed resin crowns or regional staircase measurements reviewed.', 'Printed/scanned crown at frozen angles/azimuth and layer height, same regions/process.')
add(46, 'PARTIAL', 'AB IL3 B5', 'B1 Brier 0.197244 against 0.200803; IL3: 33 accepted pore sets; partial pore/ductility correlation -0.485.', 'POPULATION PER_POINT', 'B1-B8 completed: IN_PROGRESS obsolete. Executable MEASURED process/property subports exist, but held-publication transfer failed.', 'Same specimen pretest XCT/surfaces/history, process/mechanics across build lots; unresolved EBSD provenance and dental transfer remain.')
add(47, 'PARTIAL', 'X38 B7', '11/15 surfaces accepted; 55/55 file paths; maximum geometry error 0 mm; 0/6704 test region errors.', 'PER_POINT PER_SURFACE_REGION', 'STL+3MF with units, prediction hashes and regional sidecar can roundtrip. This changes the old 3MF zero files claim.', '4/15 rejections, synthetic regions, full schema/self-intersection checks and industrial CAM/STEP/slicer plus physical manufacture UNKNOWN.')
add(48, 'MISSING', 'X38 B7 AM', 'X38: 55/55 digital transport tests; M: 0 new physically measured manufactured bodies.', 'PER_POINT', 'Digital roundtrip is not design-to-as-built scan; self-calibration body remains unmeasured. No regional manufactured part validation in these deliveries.', 'DATA: CAD and independent scan of same manufactured part, specimen ID, material/batch/process/date. CODE: reference-guided registration, signed regional distance and trueness/precision over replicates. MEASUREMENT: start with one milled crown+die and separate reference metrology, then replicates/held-out batch.')
add(49, 'PARTIAL', 'X25 B2 X38 B7 LOG', '36 published raw ISO specimens; four full runouts and nine earlier stops; X1B frozen Q=0.474.', 'PER_TOOTH POPULATION', 'Published specimens now actually read; future lab imports/strict relative contract can be rejected. No manufactured part from own crown loop measured.', 'Prospective specimen-matched Q/fit/temperature and fracture origin, predictions frozen before new specimen. Four X25 full runouts are not four independent model validations.')
add(50, 'RESEARCH', 'AM AUD LOG AI', 'M external calibration RMSE ratio 0.889 against frozen 0.5; stronger optimized crown control ratio 1.57556.', 'PER_SURFACE_REGION PHENOMENOLOGICAL', 'M has a dental calibration construction with external aggregate comparison; I has a prediction alarm in simulation. Research exists, but no shared measurement-to-posterior/alarm port validated as connected.', 'Specimen-matched scan/process reference separating scanner from shrinkage; run frozen posterior update and check alarms on held-out batch with observed outcomes.')
add(51, 'PRESENT', 'G3 B4 X38 B7', 'GenCAD isolated replay: same score digest; X38: 130 verified principal fields; batch7: 442 principal fields/injections.', 'PER_TOOTH PER_POINT', 'Receipts, locked local runtime, input hashes and isolated replay actually reviewed. Retain PRESENT for components; not a uniform certificate for every lane.', 'Clean OS installation and uniform receipt through full patient chain unestablished; preserve old REJECT versions and retrospective locks.')
add(52, 'PRESENT', 'SPEC B7 B2', 'Inherited LICENSE_gate: 53/53 CC BY cases GREEN; X39 and Pulpy extension exact redistribution permission UNKNOWN.', 'PER_ARCH POPULATION', 'Retain PRESENT for scoped existing license gate, not license approval for entire demo package. UNKNOWN datasets receive no X43 export authorization.', 'Bite2Text/Pulpy and snapshot-specific Teeth3DS conditions need clarification before distribution; no new licensing determination or publication here.')
MISSING = {'K09': {'data': 'OFJ jaw+teeth+PDL with version-locked regions and common coordinate frame', 'code': 'Multiregion SDF/ownership field; complete bone collar-to-bulk trim; ownership checks on every element', 'measurement': 'Region/volume/interface parity against source tets and physical response refinement on same carrier'}, 'K13': {'data': 'Canonical dental region IDs and source-bound law/parameter/unit/validity', 'code': 'Total material mapping rejecting missing owner/unit; API to field and FE', 'measurement': 'Patch/material test and independent specimen response; definition can start without new patients'}, 'K16': {'data': 'Registered geometry and regional force time series from same deidentified specimen/patient', 'code': 'Calibrated observation model with shared theta and regional force/moment ports', 'measurement': 'Loaded registered bite with calibrated pressure/force image; total force insufficient'}, 'K21': {'data': 'Antagonist/preparation, support/material, observed pose/load', 'code': 'Deformable friction contact with penetration, force, moment and stick/slip checks', 'measurement': 'Same specimen contact pressure and displacement plus independent contact reference'}, 'K31': {'data': 'Implant-ID-linked longitudinal RFA/ISQ/BIC with bone/surface/drilling protocol', 'code': 'Temporal osseointegration law; HANDOVER from MEASURED damage/stability state', 'measurement': 'Held-out time series; culture/cell outgrowth cannot substitute for human BIC(t)'}, 'K34': {'data': 'One antagonist/material pair, environment and measured time series', 'code': 'Scoped wear/LTD/corrosion law with regions/history', 'measurement': 'Three-body wear or specific aging/corrosion test with same specimen identity'}, 'K48': {'data': 'CAD and scan of same manufactured part, batch/process/specimen/date', 'code': 'Reference-guided registration and signed regional trueness/precision; separate scanner/process errors', 'measurement': 'One milled crown+die with independent metrology first, then replicates/held-out batch'}}
for row in ROWS:
    row['timescale'] = 'HANDOVER' if row['k'] in ['K24', 'K28', 'K29', 'K31', 'K45', 'K46', 'K50'] else 'SIMULTANEOUS'
    if 'PHENOMENOLOGICAL' in row['resolution']:
        row['phenomenological_debt'] = row['remaining_requirement']
(HERE / 'raw/CURATED_EVIDENCE.json').write_text(json.dumps({'references': REG, 'chains': ROWS, 'missing_requirements': MISSING}, ensure_ascii=False, indent=2) + '\n')
print(f'Curated {len(ROWS)} K chains; {len(REG)} references. Manual semantic proposals remain PENDING_INDEPENDENT_REVIEW.')
