from dental_release.paths import expand as _release_expand
from common import *
sel = read(X77 / 'PATIENT_SELECTION.json')
work = Path(read(X77 / 'LATEST_RUN.json')['runs'][0]['path'])
files = [X77 / 'PATIENT_SELECTION.json', work / 'SCAN.json', work / 'scene.npz', work / 'TASK_ARRAYS.npz', X69 / 'raw/zenodo_zip_directory.json', X12 / 'raw/R6_pairs.json', X12 / 'raw/R8_calibration.json', Path(_release_expand('@DENTAL_WORK_ROOT@/X12/R8_P1_36_paired.npz')), X73 / 'raw/patients/P1.json', Path(_release_expand('@DENTAL_WORK_ROOT@/X73-canal-wall-full/P1_points.npz'))]
files += sorted((ROOT / 'code').glob('*.py'))
freeze('SOURCE_LOCK.json', dict(frozen_utc=now(), files=[dict(path=str(p), sha256=sha(p), bytes=p.stat().st_size) for p in files], X77_work=str(work), same_patient=sel['patient_id'], validation_patient='Pulpy/ToothFairy P1; never a replacement for Demo1'))
referent = dict(kind='published_dataset', locator='https://doi.org/10.5281/zenodo.8027553', compared_quantity='Released Demo1 modalities and local presence of same-patient pulp/bone/canal observations', refutes_us=True)
cost = dict(preparation='Read targeted prior work, hash small source/member evidence; wall time for reasoning UNKNOWN', fit='No segmentation fitting. Inherit X69 pose; independent error UNKNOWN. P1 has exact CT identity inherited from X12/X73.', discovery='R1 original source recovery, R2 exact discrete tissue query; no clinical selection', validation='Source masks and independent SciPy point-to-box optimizer, all-source gray samples, injected wrong values', questions=0, fallback='Emit UNKNOWN for Demo1 and physical safety; output minimum same-patient measurement port; acquisition and lab costs UNKNOWN')
common = dict(frozen_utc=now(), claim_type='capability', consumer='Prosthodontic laboratory researcher testing same-frame tissue constraints', resolution='PER_POINT', time_scale='SIMULTANEOUS coordinates; HANDOVER virtual preparation -> post-cut state', full_cost=cost)
freeze('PREREG_R1_SOURCE_RECOVERY.json', dict(**common, capability='Add tissue observations to the fixed X77 Demo1 crown patient without identity substitution', obstacle='Only tooth reconstruction and IOS are currently local; raw volume and semantic tissue labels not established', changed_operation='Check archive directory and exact local original paths, bind X77 preparation points to CBCT and require semantic same-patient tissues', metrics=dict(accepted_foreign_patients=0, all_requested_tissues=3, unknown_preserved=True), tolerance=0, decision='Complete only with local Demo1 pulp,bone/canal observations and their frame; otherwise incomplete with UNKNOWN distances', strongest_equal_information_control='X77 strict tissue contract and direct source inventory, no algorithm competition', falsifier='Any cross-patient numeric distance, residual treated as registration truth, or unavailable image intensity inferred from STL', external_referent=referent))
freeze('PREREG_R2_NATIVE_TISSUE_OPERATOR.json', dict(**common, capability='Compute pulp, uncalibrated bone gray profile and canal-revision distances in one verified native CT validation frame, using a reusable pointwise tissue operation', obstacle='No all-tissue executable consumer; full patient claim blocked for Demo1', changed_operation='Exact integer half-voxel point-to-occupied-box distances; retain per-point query and every canal mask instead of regional scalar uncertainty. P1 explicitly separate validation patient.', construction=dict(validation_case='P1', tf2_case='ToothFairy2P_001', fdi=36, prep_depth_mm=0.5, prep_rule='Inherit X12 .5mm uniform erosion; deterministic 96 boundary voxel-centre samples, all pulp retained', bone_rule='Nearest label1 voxel to FDI36 centroid + (0,5,0)mm; axis-index depth -3..3mm at .3mm spacing; virtual probe, not actual implant site', canal_rule='Same 21 bone-profile centres; compare TF1/Maxillo/TF2 voxel unions', point_limit=96), metrics=dict(mask_crop_identity_error=0, exact_squared_distance_identity_error=0, independent_scipy_abs_error_mm=1e-08, gray_sample_identity_error=0, injected_false_acceptances=0, summary_identity_error=0), tolerance=dict(geometry_mm=1e-08, source_bytes=0), decision='Digital capability only if exact source/crop checks, all three operators and real equal-information controls pass. Physical calibration and Demo1 completion remain UNKNOWN.', strongest_equal_information_control='Actual SciPy bounded least-squares projection onto every candidate voxel box, direct source-array gray sampling, original X12 EDT at voxel centres', falsifier='Wrong crop origin/spacing/winding/FDI/frame accepted, wrong source hash, global masks replaced by local horn only, or an injected wrong output passes', external_referent=dict(kind='published_dataset', locator='https://ditto.ing.unimore.it/toothfairy2/ + https://github.com/mahmoudgamal0/Pulpy3D', compared_quantity='P1 external FDI36 occupancy/pulp containment, bone intensities and three published canal revisions; annotation truth only', refutes_us=True), unknowns=['Independent blind annotator spread', 'physical tissue trueness', 'IOS registration error for Demo1', 'real implant placement', 'DEJ', 'gray-to-density/modulus calibration']))
leaves = [('same-subject identity and P1 CT array equality', 'EXTERNALLY_MEASURED', 'Published image arrays verified by X12/X73; byte identity is not physical accuracy.'), ('point-to-box distance', 'DERIVED_UNDER_ASSUMPTIONS', 'Projection onto a rectangular box: squared distance sum max(abs(q-c)-h,0)^2, minimize over occupied voxels. Stops at exact discrete label representation.'), ('mask boundary versus true tissue', 'UNKNOWN', 'No independent histology/microCT or blinded same-specimen readers. Voxel size is not a segmentation-error bound.'), ('bone profile', 'EXTERNALLY_MEASURED', 'Native source gray values at explicit voxel indices; no calibrated attenuation or density.'), ('virtual preparation and bone probe', 'CONSTITUTIVE_CLOSURE', 'Fixed source-index erosion/probe rules; no anatomical finish line or real osteotomy.'), ('IOS pose error', 'UNKNOWN', 'X69 surface residual is not independent TRE; tissue decisions require measured directed spatial displacement.'), ('canal spread', 'EXTERNALLY_MEASURED', 'Released annotation revisions have same image; they do not establish independent inter-reader distribution.'), ('shared pose and rigid invariance', 'DERIVED_UNDER_ASSUMPTIONS', 'A common rigid motion preserves distance, a fixed native tissue requires absolute pose enclosure. Missing empirical bounds remain NULL.')]
freeze('DECOMPOSITION.json', dict(idea='A crown modification must query the actual same-patient tissue field before constraints can be meaningful', mechanism='Native tissue occupancy and intensity plus query-dependent shared registration state', equation='d(q,V)=min_v sqrt(sum_k max(|q_k-c_vk|-h_k,0)^2); |d(q+e,V)-d(q,V)|<=||e||; d(Rq+t,RV+t)=d(q,V)', operation='X77 points -> frame-bound tissue query -> per-point pulp/canal distance and gray profile -> consumer aggregation after uncertainty', representation='Source identity, full 3D voxel sets, halfgrid exact squared distances, raw ordered gray vector, ensemble labels with lineage', leaves=[dict(name=n, status=s, stopping_argument=a, unresolved_deeper_mechanism=a) for (n, s, a) in leaves]))
freeze('FROZEN_PREDICTIONS.json', dict(frozen_utc=now(), prereg_hashes={p.name: sha(p) for p in ROOT.glob('PREREG_*.json')}, patient=sel['patient_id'], predictions=dict(Demo1_pulp_mm=None, Demo1_canal_mm=None, Demo1_bone_gray=None, reason='No matched tissue data; these are premeasurement UNKNOWN, not imputed values'), validation_prediction='P1 independent distance projection and raw gray sampling agree within frozen gates; no numeric biological outcome predicted', physical_measurements_performed=0))
state('PREREG_FROZEN', 'R1/R2 frozen before numerical queries', 'Run source feasibility, then native P1 operator')
