from dental_release.paths import expand as _release_expand
import json, hashlib, zipfile, datetime, subprocess
from pathlib import Path
from common import ROOT, ZIP, DATA, CORPUS, save, sha, utc, state, article, text

def run():
    read = lambda p: json.loads((ROOT / p).read_text())
    r1 = read('raw/R1.json')
    r2 = read('raw/R2.json')
    r3 = read('raw/R3.json')
    v = read('raw/VERIFICATION.json')
    r4 = read('raw/R4.json')
    r2['one_mode_calibration_counterexample'].update(exact_summary_identity_pass=False, status='NOT_AN_EXACT_SUFFICIENCY_WITNESS; R3 supplies a separate dyadic witness with identity error0')
    primal = r1['O18']['external_referent'].copy()
    primal['refutes_us'] = True
    r1['O18']['external_referent'] = primal
    r1['O20']['external_referent']['refutes_us'] = False
    r3['external_referent']['locator'] = 'MIT 2.080J Lecture8 Eq8.15 and symmetric energy bilinear form: https://ocw.mit.edu/courses/2-080j-structural-mechanics-fall-2013/2d0cc95bd3556fdadc28226acabafa51_MIT2_080JF13_Lecture8.pdf'
    r3['external_referent']['compared_quantity'] = 'symmetric virtual-work bilinear form; reciprocity follows under symmetric linear stiffness, not for dissipative bond slip'
    manifest = []
    with zipfile.ZipFile(ZIP) as z:
        for row in read('raw/PATIENT_GEOMETRY.json')['members']:
            b = z.read(row['member'])
            manifest.append(row | dict(sha256=hashlib.sha256(b).hexdigest()))
    save('raw/PATIENT_MEMBER_HASHES.json', dict(zip_path=str(ZIP), zip_sha256=sha(ZIP), members=manifest))
    screening = [dict(locator='PMC10548050 doi:10.1016/j.jds.2023.05.026', status='USED', quantity='measured low-deflection force and nominal test geometry'), dict(locator='PMC10824581 doi:10.1155/2024/5455197', status='USED', quantity='mandibular signed bracket error means/SD and study tolerances'), dict(locator='PMC10441729 doi:10.1186/s12903-023-03268-5', status='DEFERRED', reason='force and displacement at debond failure are not initial elastic stiffness; differing adhesives/materials'), dict(locator='PMC10587025 doi:10.1007/s00056-022-00393-8', status='CONTEXT_ONLY', reason='intraoral geometric positioning; no signed joint deformation/force measurement; cannot calibrate passivity'), dict(locator='PMC10140660 doi:10.4274/TurkJOrthod.2022.2022.34', status='DEFERRED', reason='numeric tables are embedded graphics in local XML; no independent numeric transcription in this round')]
    save('SOURCE_SCREENING.json', dict(primary_candidates=5, quantitative_used=2, not_used_quantitatively=3, dropout_fraction=0.6, rows=screening, scope='five targeted primary full texts; title searches are discovery, not screened evidence'))
    reasons = {'O01': 'X19/X27 already use formed thickness; same-case temperature/strain/thickness measurements missing.', 'O02': 'X19 already tests aligner forces; matched force/torque rig missing for this patient.', 'O03': 'No local same-product formed aligner relaxation experiment on this model; fixed interval not mechanistically identifiable.', 'O04': 'Requires validated attachment contact-force port; no matched moment experiment.', 'O05': 'Already X27 regional-thickness branch; manufactured same-case aligner measurements missing.', 'O06': 'Local weekly-movement dataset has other subjects; no same-patient planned stages/forces for our common model.', 'O07': 'No root/crown trajectory and force-window experiment; inherited PDL-to-rate claim refuted.', 'O08': 'Setup acceptance needs held-out clinician setup; X2/X7 already compute bite geometry/classification.', 'O09': 'Already built by X2/X7; no new contact measurement in this lane.', 'O10': 'X2/NEXT_P already show force nonidentifiability; matched loaded bite-force film missing.', 'O11': 'X18/X54 already connect crown and antagonist; same-case as-built/loaded contact measurement missing.', 'O12': 'Patient jaw trajectories and observed excursions missing; average articulator motion cannot be external patient truth.', 'O13': 'No same-case splint fabrication/fatigue measurement or specimen-specific material law.', 'O14': 'Corpus review alone cannot make a same-patient manufacturing decision; individual measured load history missing.', 'O15': 'Disc support and same-case joint-load reference missing; legacy lever model does not measure local TMJ pressure.', 'O16': 'No pharynx/PSG response paired to this jaw model; awake CBCT not MAD outcome.', 'O17': 'No connector force/fatigue measurement for a declared MAD hardware design.', 'O19': 'No bracket slot/archwire/friction bench dataset matched to this model; an elastic beam alone is incomplete.', 'O21': 'Already X9 IPR negative; unresolved local enamel truth/contact regions.', 'O22': 'Already X15 bone envelope; no longitudinal bone-dehiscence truth on common model.', 'O23': 'Interradicular map is possible in CBCT, but common OFJ model has no measured root-edge uncertainty or matched TAD-guide insertion test; defer to dedicated TAD lane.', 'O24': 'Already X7 report/geometry comparison; missing independent point-level clinician annotations.'}
    save('CHAIN_SELECTION.json', dict(selected=['O18', 'O20'], screened=24, not_selected=22, not_selected_fraction=22 / 24, not_selected_reasons=reasons, meaning='not chosen for this two-chain common-model brief, not universal invalidity', prior_work_reused=[_release_expand('X2'), _release_expand('X7'), _release_expand('X19'), _release_expand('X9'), 'OLD_DENTAL_CELL_INDEX'], distinct_delta='bonded retainer force-state and bracket full-pose/moment-tail acceptance, absent in searched prior chain reports'))
    ports = [dict(producer='local lingual source triangle and crown frame', consumer='six-bond signed displacement and pose reader', resolution='PER_POINT', timescale='SIMULTANEOUS', status='EXECUTED_GEOMETRIC', unit='mm/radian'), dict(producer='published rod force observation', consumer='directional fixture stiffness port', resolution='PER_SURFACE_REGION', timescale='SIMULTANEOUS', status='CALIBRATION_ONLY', unit='N/mm'), dict(producer='directional fixture stiffness', consumer='patient initial retainer force', resolution='PER_SURFACE_REGION', timescale='SIMULTANEOUS', status='UNVALIDATED_TRANSFER_HYPOTHESIS', unit='N', debt='measure patient-shaped retainer, restraints, axial/torsion and bonds'), dict(producer='source tooth-type bracket-error moments', consumer='conditional tolerance-tail reasoning', resolution='PER_TOOTH', timescale='SIMULTANEOUS', status='EXECUTED_CONDITIONAL', unit='mm/degree', debt='joint per-specimen rows; future-patient domain transfer'), dict(producer='future same-model bracket pose scan', consumer='per-vertex finite rigid displacement and joint manufacturing release', resolution='PER_POINT', timescale='SIMULTANEOUS', status='IMPLEMENTED_NOT_MEASURED', unit='mm/degree'), dict(producer='bonding/retention initial mechanical state', consumer='later tooth movement/bone outcome', resolution='PER_TOOTH', timescale='HANDOVER', status='UNKNOWN_NOT_COMPUTED', unit='mm/week', debt='longitudinal movement and biological closure; ORTHO_rate refutation retained')]
    save('CHAIN_PORTS.json', dict(edges=ports, aggregation='consumer only; do not replace local signed state by arch RMS', phenomenological_debts=[dict(quantity='source fixture secant stiffness', replacement='per-span force-displacement and interface compliance on manufactured retainer'), dict(quantity='95% whole-assembly release', replacement='lab-defined acceptance and independent repeated full-pose measurements; not a clinical safety threshold')]))
    outcome = dict(schema='X62-results-v1', lane='X62-ortho', review_state='PENDING_INDEPENDENT_REVIEW', claim_type='capability', external_referent=primal, other_external_referents=[r1['O20']['external_referent'], r3['external_referent']], enabled='two runnable state-aware laboratory consumers on one independent patient mesh; nominal force closure and summary-based release cannot be certified', clinical_or_manufacturing_decision='withhold lab release from scalar/mean summaries; obtain measured stiffness/full pose. No patient clinical recommendation.', chains={'O18': r1['O18'], 'O20': r1['O20']}, rounds={'R1': r1, 'R2': r2, 'R3': r3, 'R4': r4}, verification=v, physical_measurement='NOT_RUN', external_validation_scope='source fixture force consistency and primary printed bracket moments; not physical validation of patient prototype', sufficiency_tests=read('raw/SUFFICIENCY_R1.json') | {'O18_directional_stiffness': r2['stiffness_sufficiency'], 'O18_one_query': r3['sufficiency']}, costs={'threads': 1, 'full_replay_cost': 'raw/FULL_REPLAY_COST.log (created by /usr/bin/time -v ./run_all.sh)', 'preparation_fit_discovery': 'preparation/source search prior to numerical run; exact agent token and total time UNKNOWN', 'fit_data': 'two published force endpoints used only in R2/R3 calibration; both read before R1 prereg', 'query_cost': 'R3 three response experiments instead of twelve only for restricted3-component linear consumer; installed sensor and repeatability costs UNKNOWN', 'fallback': 'same-model12-mode force matrix or direct force on each future state; no measured end-to-end gain', 'intermediate_limit_bytes': 3000000000}, data=[r2['data_file']], source_manifest='raw/SOURCE_MANIFEST.json; raw/PATIENT_MEMBER_HASHES.json', screening='SOURCE_SCREENING.json; CHAIN_SELECTION.json', limitations=['nominal vertical force closure failed', 'R2 calibrated endpoints are not holdout validation', 'patient axial/torsional/bond laws and geometry uncertainty UNKNOWN', 'nominal STL has no whole-path tooth clearance certificate', 'moment summaries do not determine joint tails', 'source sample moments do not guarantee future-patient moments', 'matrix-building and physical force remainder outside exact binary arithmetic enclosure are UNKNOWN', 'rotational frame clinical sign convention not independently verified', 'no biological movement-rate or clinical outcome prediction', 'no clinical or algorithmic10x claim'], generated_utc=utc())
    outcome['other_external_referents'].append(r4['external_referent'])
    outcome['limitations'].append('R1/R2 virtual rotation witness used crown-center stand-in; production pose reader now requires frozen explicit target pivots; actual bracket body center remains unmeasured')
    outcome['verification_aggregate'] = dict(main_gates_passed=v['passed'], main_gates_total=v['total'], main_injections_rejected=v['injected_faults_rejected'], main_injections_total=v['injected_faults_total'], R4_controls=r4['controls'], R4_controls_total=5, R4_new_target_contract_faults_rejected=3, all_pass=v['all_pass'] and r4['gate_pass'])
    cost_record = ROOT / 'raw/MEASURED_REPLAY_COST.json'
    if cost_record.exists():
        outcome['costs'].update(json.loads(cost_record.read_text()))
    outcome['review_scope'] = 'producer package only; scientific acceptance awaits independent coordinator review'
    save('results.json', outcome)
    files = []
    for pattern in ['code/*.py', 'PREREG*.json', 'FROZEN*.json', 'raw/*json', 'exports/*', 'figures/*']:
        for p in sorted(ROOT.glob(pattern)):
            files.append(dict(path=str(p.relative_to(ROOT)), bytes=p.stat().st_size, sha256=sha(p)))
    save('ARTIFACT_MANIFEST.json', dict(files=files, data=outcome['data'], notes='human reports and final result JSON hashes separately recorded in graph feedback'))
    state('PACKAGED_PENDING_INDEPENDENT_REVIEW', 'O18 external vertical FAIL; O20 summaries NOT_CERTIFIED; R3 conditional identity PASS; R4 explicit targets PASS', 'independent review, then manufactured retainer compliance/force and real bracket target-pose measurement')
    print(json.dumps(dict(chains=['O18', 'O20'], rounds=4, external_force_gate=r1['O18']['external_gate'], checks=v['passed'], faults=v['injected_faults_rejected'], R4_controls=r4['controls'], physical_measurement='NOT_RUN')))
if __name__ == '__main__':
    run()
