from common import *
a = read(ROOT / 'raw/ANNOTATED_PAIRS.json')
assert len(a['rows']) == 18
thresholds = {}
for fam in ['molar_crown', 'premolar_crown', 'anterior_crown']:
    rr = [r for r in a['rows'] if r['family'] == fam and r['valid_for_envelope']]
    thresholds[fam] = max((r['metrics']['8192']['p95_mm'] for r in rr)) if len(rr) >= 3 else None
records = []
inputs = {}
for (tag, folder, method) in [('R2', BASE / 'PROOF_LANE_FULL_CROWN_R2', 'outer_first_joint'), ('A', R3, 'spatial_sheet'), ('B', R3, 'explicit_sheet'), ('C', R3, 'explicit_sheet'), ('scalar', R3, 'scalar_control')]:
    src = folder / 'rounds' / ('A.json' if tag == 'scalar' else tag + '.json')
    inputs[str(src)] = sha(src)
    dat = DATA.parent / folder.name / ('A' if tag == 'scalar' else tag)
    for r in read(src)['rows']:
        if r['participant'] != method:
            continue
        p = dat / method / r['key'] / 'mesh.npz'
        rec = dict(tag=tag, key=r['key'], family=r['family'], status=r['status'], source_row_file=str(src), participant=method, mesh_path=str(p) if p.exists() else None, source_score=r)
        if p.exists():
            inputs[str(p)] = sha(p)
        records.append(rec)
freeze(ROOT / 'PREREG_RESCORE.json', dict(claim_type=['capability', 'information_link'], capability='Separate task-critical function, in-situ surface reconstruction and pose-independent shape variation on all frozen R3 designs', obstacle='One p95 conflates shape and placement; planar margin and unsigned proximal distance do not establish fit/contact', changed_operation='Noncompensating metric vector; add oracle rigid shape comparison calibrated to independent annotated bilateral pairs. Placement remains evaluated in original pose by existing function metrics.', consumer='Lab reader deciding why a crown fails and what measurement is absent', records=records, input_hashes=inputs, thresholds_mm=thresholds, metrics=dict(old_p95_mm=0.35, shape_envelope='q8192 after rigid registration <= independent family maximum; report in-situ q separately. Threshold is descriptive, never clinical.', probe_counts=[2048, 8192], function='Original signed static band/support/location/interference gates re-executed at fixed pose. No threshold relaxed.', wall='Reuse hash-bound original facet-cover lower bound>=.5; retain sampled result separately; no new material claim', margin='Finish-line conformance UNKNOWN for every design: actual prepared finish line absent. Retain inherited planarity as technical diagnostic only.', proximal='Retain inherited unsigned patch areas as geometric proxy; signed penetration and physical contact UNKNOWN.', clinical_status='NOT_ESTABLISHED regardless of score; no accepted-pair conditional calibration', numeric_tolerance=1e-09), decision='Count shape envelope and nominal functional feasibility separately, then intersection. Every failed construction retained. No clinical pass can be issued.', strongest_equally_informed_control='R3 scalar_control carries same acquired gaps; rescored through identical vector. Diagnostic parity only.', practice_without_information='Whole in-situ p95<=.35 jointly vetoes otherwise functional construction', falsifiers=['No shape-envelope passes would mean the old threshold alone does not explain anatomy failure', 'Wrong shape1mm/contact1mm/wall0mm values must fail', 'Unknown margin must never become PASS'], full_cost=dict(preparation='Frozen historical mesh and score hashes', fit='Four rigid ICP starts; no generator/training', discovery='two paired-source constructions retained', validation='fresh triangle distances and static contact; inherited wall/prox values explicitly labelled', queries=len(records), fallback='FAILED remains in denominator'), external_referent=dict(kind='published_dataset', locator=['https://osf.io/xctdy/', str(V4 / 'payload/whole_private')], compared_quantity='Natural annotated bilateral p95 envelope; source native shape/gap. Neither is clinical acceptable-pair floor.', refutes_us=True), resolution='PER_POINT -> PER_SURFACE_REGION -> PER_TOOTH', time_scale='SIMULTANEOUS', clinical_floor_status='UNKNOWN'))
freeze(ROOT / 'FROZEN_RESCORE_PREDICTIONS.json', dict(input_hashes=inputs, thresholds_mm=thresholds, threshold_source_sha256=sha(ROOT / 'raw/ANNOTATED_PAIRS.json'), predictions='No predeclared count of passes. Expect p95 insufficiency; clinical acceptance remains unidentifiable. Historical R3 aggregate outcomes already known; this is retrospective diagnostic evaluation, not held-out generator validation.'))
freeze(ROOT / 'DECOMPOSITION_RESCORE.json', dict(parent=['DECOMPOSITION_LOCAL.json', 'DECOMPOSITION_ANNOTATED.json'], leaf=dict(idea='separate morphology from placement and fit', equation='q_shape=min_R,t q(RC+t,S); g(x)=h_ant(x)-h_C(x); t(x)=distance(outer,intaglio)', operation='approximate rigid minimization by four-start ICP; actual static field reused in original frame', representation='noncompensating vector plus UNKNOWN fields', status='DERIVED_UNDER_ASSUMPTIONS', stop='ICP is not a global optimum proof; physiological contact, material-specific wall requirement and actual finish line remain absent'), envelope=dict(status='CONSTITUTIVE_CLOSURE', stop='upper natural teeth do not calibrate lower accepted restorations; only a descriptive screen')))
state('RESCORE_PREREG_FROZEN', thresholds, 'Run existing meshes through task vector and independent shape envelope')
