from dental_release.paths import expand as _release_expand
from common import *
tds = Path(_release_expand('@DENTAL_CORPUS_ROOT@/geometry/Teeth3DS'))
split = tds / 'Teeth3DS_train_test_split/testing_upper.txt'
files = []
for name in split.read_text().splitlines():
    name = name.strip()
    pid = name.rsplit('_', 1)[0]
    for part in range(1, 8):
        p = tds / f'data_part_{part}' / 'upper' / pid / (name + '.obj')
        if p.exists() and p.with_suffix('.json').exists():
            files.append(str(p))
            break
files.sort(key=lambda p: hashlib.sha256(Path(p).parent.name.encode()).hexdigest())
freeze(ROOT / 'PREREG_ANNOTATED.json', dict(claim_type='information_link', capability='Bilateral surface-variability scale using dataset annotations instead of X11 inferred labels', obstacle='R3 paired homologs contain disconnected fragments and unchecked tooth identity; not a clinical calibration sample', changed_operation='Change information source to local Teeth3DS annotation; same rigid fit and triangle-distance operator', consumer='Nonclinical shape-variation screening of frozen R3 designs', selection=dict(paths_in_order=files, need_cases=6, teeth=[11, 14, 16, 21, 24, 26], eligibility='At least100 labelled vertices and30 all-labelled triangles for every tooth; take first6 eligible cases. No outcome-dependent exclusion. Reject individual pairs from calibration if largest-component discarded area >0.05 on either tooth; preserve in denominator.'), metric=dict(samples=[2048, 8192], fit='Same four starts and60 iterations as PREREG_LOCAL', crop='Full annotated tooth crown surface, no axial clipping or invented preparation', threshold='Per tooth family maximum 8192-probe bilateral p95 among eligible pairs. Nonclinical descriptive envelope only; independent source cohort, not clinical calibration. If fewer than3 valid pairs in a family, threshold UNKNOWN.', original_gate_mm=0.35), decision='Report annotation-based pair distribution and .35 exceedances; no clinical acceptable-pair floor established. Freeze computed thresholds before new R3 rescore.', strongest_equally_informed_control='Same conventional rigid ICP and triangle scorer; no algorithm claim', practice_without_information='Universal .35 p95 cutoff against one tooth', falsifiers=['Missing labels or geometry invalidate that pair', 'No valid family threshold when fewer than3 pairs', 'Changed calibration source does not identify clinical acceptance'], full_cost=dict(preparation='Parse up to6 eligible local OBJ meshes and annotations', fit='18 multistart ICP pairs', discovery='Previous contaminated pairs preserved', validation='self-distance and two probe counts', queries=18, fallback='Do not substitute on score'), external_referent=dict(kind='published_dataset', locator='https://osf.io/xctdy/', compared_quantity='Expert-annotated bilateral natural crown surfaces, not same-preparation restoration pairs', refutes_us=True), resolution='PER_POINT -> PER_TOOTH', time_scale='SIMULTANEOUS', split_sha256=sha(split)))
freeze(ROOT / 'DECOMPOSITION_ANNOTATED.json', dict(parent='DECOMPOSITION_LOCAL.json', changed_leaf=dict(status='EXTERNALLY_MEASURED', source='Teeth3DS original vertex labels', operation='group triangles only when all three vertex labels agree', assumptions='FDI identity accepted as dataset annotation; health and acceptability UNKNOWN', stop='No paired restoration or expert acceptance score can be inferred from tooth identity'), unchanged='Rigid alignment and distance derivation; no constitutive parameters', threshold_leaf=dict(status='CONSTITUTIVE_CLOSURE', equation='T_family=max(q_bilateral in retained source cases)', stop='Descriptive envelope; no population coverage or transfer guarantee to lower R3 arches')))
(ROOT / 'history/HANDOFF_LOCAL.md').write_text('18/18 paired R3 sources measured; large disconnected fragments and unverified inferred labels prevent a clinical floor. All data retained in raw/LOCAL_PAIRS.json. Next construction changes label information to original Teeth3DS annotations, never relaxes original R3 gates.\n')
state('ANNOTATED_PREREG_FROZEN', 'R3-label variation is contaminated', 'Measure independently annotated pairs')
