"""One-time, explicitly scoped input capture. Never copy a source tree."""
import json, hashlib, datetime
from pathlib import Path
H = Path(__file__).resolve().parent
D = H.parent.parent

def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()

def write(n, x):
    (H / n).write_text(json.dumps(x, ensure_ascii=False, indent=2) + '\n')
now = datetime.datetime.now(datetime.timezone.utc).isoformat()
write('CURRENT_WORK_STATE.json', {'lane': 'PROOF_LANE-constraint-net-r4', 'status': 'PREREGISTERED_SOURCE_BINDING', 'updated_utc': now, 'latest_gate': 'R3 accepted with source identity correction; HUNT main claims rejected', 'next_operation': 'Frozen local source extraction, exact arithmetic, then external locator verification', 'large_intermediate_limit_bytes': 3000000000})
pr = {'id': 'R4A', 'claim_type': 'information_link', 'capability': 'A lab researcher can distinguish reviewed published observations from unvalidated source-to-target transfer on existing constraint edges.', 'obstacle': 'Correct source numbers were embedded in rejected HUNT conclusions; source identity and estimand can be lost.', 'changed_operation': 'Pin original path/hash/locator/quantity/protocol and bind ONLY a scoped reference facet to an existing edge. Preserve all inherited physical status and residuals.', 'consumer': 'DENT-UNC-PROPAGATION; preload-history, replica-CT, K33; lab acquisition plan', 'metric': {'exact_decimal_difference_tolerance': 0, 'source_identity_mismatches_allowed': 0, 'false_full_edge_promotions_allowed': 0, 'source_replay_tolerance': 0, 'required_audit_source_families': ['Sagheb', 'Cunali', 'Choi']}, 'decision': 'PASS only if all three source families replay and pin correctly, injected faults reject, and unsupported transfer stays blocked. Otherwise preserve failed gate.', 'current_practice': 'Frozen R3: indirect report operands, missing explicit audited primary-table facet; already knows numerical residuals. No new magnitude improvement claimed.', 'strongest_equally_informed_control': 'Direct independent table/cell reading and exact rational subtraction; correctness check, not innovation comparator.', 'falsifiers': ['Wrong source identity accepted even when value equal', 'Internal gap mistaken for marginal gap', 'Fatigue runout treated as exact failure or a universal 40% law', 'Review rejection promoted into full edge validation'], 'cost': {'preparation': 'Read existing R3, audit and primary source snapshots; manual time unknown, bytes measured', 'fit': 0, 'discovery': 'Explicit local schema and operator work; elapsed wall time logged', 'validation': 'Source parsing plus actual mutation controls', 'questions': 'No user requests, no external physical measurement', 'fallback': 'UNKNOWN with acquisition requirement; no imputation'}, 'external_referent': {'kind': 'external_review', 'locator': str(D / 'results/LANE_XHUNT_AUDIT_1/CORRECTIONS.jsonl'), 'compared_quantity': 'Audit-confirmed scoped published preload, internal gap and fatigue values', 'refutes_us': True}, 'resolution_level': 'POPULATION; source table specimens retained when available', 'status': 'FROZEN', 'frozen_utc': now}
write('PREREG_R4A.json', pr)
write('DECOMPOSITION.json', {'goal': 'A laboratory can ask what measured information would make a coupled dental design decision evaluable.', 'chain': ['Trustworthy physical decision', 'Same observable, specimen and protocol plus adequate uncertainty', 'Correct unit cannot distinguish wrong observable or implausible magnitude', 'Source-scoped typed reference and range gate', 'Frozen source binding, then protocol-conditioned numerical admission'], 'leaves': [{'idea': 'Published numbers can constrain an edge without validating its whole operator', 'mechanism': 'Match measurement operator and protocol, not shared unit', 'equation': 'delta = reported_mean_A - reported_mean_B', 'operation': 'Exact decimal subtraction with immutable source identity', 'representation': 'Edge reference facet: quantity, source path/hash, table locator, population, protocol, region, state and censoring', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'assumptions': 'Printed decimals are the intended reported summaries', 'stop': 'Arithmetic is exact; source rounding and physical truth require source/lab evidence.'}, {'idea': 'Empirical magnitudes require measured support', 'mechanism': 'Compare admitted value to a protocol-specific envelope', 'equation': 'L(context) <= x <= U(context)', 'operation': 'Fail closed for missing finite range or incompatible context', 'representation': 'plausible_range for every variable, with UNKNOWN and non-scalar cases explicit', 'status': 'CONSTITUTIVE_CLOSURE', 'assumptions': 'Source-observed envelope is an ingestion screen, never a universal physical bound', 'stop': 'No target-system envelope can be derived from unrelated populations; needs matched observations.'}, {'idea': 'Mean/range loses assignment and dependence', 'mechanism': 'Permuting paired observations preserves summaries but changes differences', 'equation': 'Var(A-B)=Var(A)+Var(B)-2Cov(A,B)', 'operation': 'Exact equal-summary adversarial states', 'representation': 'Keep specimen/state pairing and joint observations', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'assumptions': 'Constructed fixture only', 'stop': 'Pair data absent from published group summaries; no physical covariance inferred.'}, {'idea': 'Target clinical or manufactured-system transfer', 'mechanism': 'Unknown material, geometry, friction and observation effects', 'equation': 'y_target = F(x_target, theta_unknown)', 'operation': 'Abstain and specify matched lab measurement', 'representation': 'Existing physical blockers', 'status': 'UNKNOWN', 'assumptions': 'None replacing observations', 'stop': 'Needs target measurements; source table cannot identify target law.'}]})
(H / 'sources').mkdir(exist_ok=True)
inputs = {'r3_net': D / 'results/PROOF_LANE_CONSTRAINT_NET_R3/CONSTRAINT_NET_DENTAL_R3.json', 'r3_results': D / 'results/PROOF_LANE_CONSTRAINT_NET_R3/results.json', 'r3_review': D / 'results/LANE_XREVIEW_BATCH21/REVIEW_PROOF_LANE_CONSTRAINT_NET_R3.json', 'r3_proposals': D / 'results/PROOF_LANE_CONSTRAINT_NET_R3/PROPOSAL_AUDIT.json', 'r3_stress': D / 'results/PROOF_LANE_CONSTRAINT_NET_R3/CONSTRAINT_STRESS_MAP_DENTAL_R3.json', 'r3_lab': D / 'results/PROOF_LANE_CONSTRAINT_NET_R3/LAB_MEASUREMENT_COVERAGE.json', 'r3_contracts': D / 'results/PROOF_LANE_CONSTRAINT_NET_R3/MEASUREMENT_CONTRACTS.json', 'r3_validation': D / 'results/PROOF_LANE_CONSTRAINT_NET_R3/VALIDATION.json', 'audit_results': D / 'results/LANE_XHUNT_AUDIT_1/RESULTS.md', 'corrections': D / 'results/LANE_XHUNT_AUDIT_1/CORRECTIONS.jsonl', 'sagheb': D / 'results/LANE_XHUNT_AUDIT_1/sources/PMC10033796.extracted.txt', 'cunali': D / 'results/LANE_XHUNT_AUDIT_1/sources/Cunali2017.txt', 'choi': D / 'results/LANE_XHUNT_AUDIT_1/sources/PMC6803993.xml', 'fatigue_counterexample': D / 'results/LANE_XHUNT_AUDIT_1/sources/PMC9680401.xml', 'review_guard': D / 'results/LANE_XREVIEW_BATCH21/patches/PROOF_LANE_CONSTRAINT_NET_R3/source_binding_guard.py'}
rows = {}
for (k, p) in inputs.items():
    b = p.read_bytes()
    name = f'sources/{k}{p.suffix}'
    (H / name).write_bytes(b)
    rows[k] = {'original_path': str(p), 'snapshot': name, 'sha256': sha(p), 'bytes': len(b)}
write('INPUT_LOCK.json', {'frozen_utc': now, 'files': rows, 'copy_policy': 'Explicit small files only; no source tree copied.'})
for name in ['PREREG_R4A.json', 'DECOMPOSITION.json', 'INPUT_LOCK.json']:
    (H / (name + '.sha256')).write_text(sha(H / name) + '\n')
write('FROZEN_PREDICTIONS.json', {'frozen_utc': now, 'kind': 'Software/source-binding predictions, not new physical predictions', 'predictions': ['Sagheb difference reconstructs 76.2 N', 'Cunali internal occlusal contrast reconstructs 60.82 um', 'Choi 285 N TX and 316 N EV are 5-million-cycle runouts, three each', 'No full physical edge status may be promoted'], 'source_observation_status': 'ALREADY_PUBLISHED_AND_AUDITED; not a blinded prospective test', 'prereg_sha256': sha(H / 'PREREG_R4A.json')})
(H / 'FROZEN_PREDICTIONS.json.sha256').write_text(sha(H / 'FROZEN_PREDICTIONS.json') + '\n')
print({'files': len(rows), 'bytes': sum((x['bytes'] for x in rows.values())), 'frozen_utc': now})
