import json, hashlib, datetime
from pathlib import Path
R = Path(__file__).resolve().parents[1]

def wr(n, x):
    (R / n).write_text(json.dumps(x, indent=2, ensure_ascii=False) + '\n')
now = datetime.datetime.now(datetime.timezone.utc).isoformat()
wr('PREREG_R3.json', {'schema': 'x19-prereg-v1', 'frozen_utc': now, 'claim_type': 'capability', 'round': 'R3', 'capability': 'Determine whether minimal sensor calibration transfers across published in vitro conditions, and identify what additional contact-state measurement a physical per-tooth force port needs', 'parent': 'X19-aligner-force; R1 andR2 preserved', 'obstacle': 'R2 interpolates tangentstiffness butF=Kdelta assumes zero forceintercept/contactgap; fixture supportconditions differ', 'changed_operation': 'Carry source condition andcalibrationintercept explicitly; test the stiffness->absolute-force conversion against unfit published forcecells and independent2015 lab', 'consumer': 'Same-arch research6-axis calibration plan; physical patientforce remainsUNKNOWN', 'metrics': {'within_study_force_conversion': 'Relativeabsolute error<=.25 for palatal .5 and.75mm sheet at.25mm; tangentstiffness prediction notfit toforcecells', 'between_study_force_transfer': 'Relativeabsolute error<=.25 for Duran .5 and.75mm palatal translationat.25mm inindependent2015 study', 'implied_deadband': 'g=delta-F/K; pointderived effectiveintercept, not actualmeasuredgeometricgap. If interval varies bythickness>0.02mm aconstantg closure isrejected', 'faultinjection': 'An exactly matchedresponse mustpass;10xwrongforce mustfail the same.25gate'}, 'external_referents': [{'kind': 'independent_measurement', 'locator': 'doi:10.2319/011316-37R.1;Table1 Fy palatalforceat.25mm sheet.5/.75', 'compared_quantity': 'absolute palatalforce N and Kdelta consistency', 'refutes_us': True}, {'kind': 'independent_measurement', 'locator': 'doi:10.1007/s00056-015-0307-3;PMID26446503;Abstract Results Duran .5/.75', 'compared_quantity': 'absolute palatalforce on21 N at.25mm inindependent publishedsensorfixture', 'refutes_us': True}], 'prior_exposure': '2015 abstractvalues3.01/4.49 and2016 .5force8.37 were seen;2016 .75forcecell not read. No blind externaltestclaim. No fittedforceamplitude allowed.', 'strong_numerical_control': 'Closed-form series inverse andnonnegativeleastsquares; samephysicalmodel', 'practice_without_information': 'Source-agnostic material/thickness-to-forcecurve without retaining insertion, support, baseline orcontact-stateconditions', 'full_cost': {'preparation': 'Twoadditional forcecells from2016Table1, independent2015 publishedmeans; boundedliteraturereads', 'fit': 'none; impliedgap isdiagnostic only', 'discovery': 'InheritedR2 stiffnesscurve mismatchflag', 'validation': 'Fourabsolute-force comparisonsandfault injection', 'questions': 0, 'fallback': 'Acquire thicknessand6-axis force-displacement onSAME formedaligner, tooth, seatingloadandtime; two thickness statespluszero/intermediate/target displacement', 'resource_limits': {'threads': 4, 'RAM_GB': 0.1, 'max_intermediates_bytes': 3000000000, 'gpu': False}}})
wr('PREREG_R3.sha256.json', {'sha256': hashlib.sha256((R / 'PREREG_R3.json').read_bytes()).hexdigest(), 'frozen_utc': now})
x = json.load(open(R / 'raw/PREDICTIONS_R2.json'))
f = x['fits']['palatal']
a = f['a_mm4_per_N']
b = f['b_mm_per_N']
p = {'claim_type': 'capability', 'rows': [{'sheet_mm': s, 'activation_mm': 0.25, 'predicted_K_N_per_mm': 1 / (a / s ** 3 + b), 'predicted_absolute_palatal_force_N': 0.25 / (a / s ** 3 + b)} for s in [0.5, 0.75]], 'source_condition': '201637Csaliva30Nhorseshoe; effectivezero-intercept prior', 'code_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}
wr('raw/PREDICTIONS_R3.json', p)
wr('FROZEN_PREDICTIONS_R3.json', {'frozen_utc': now, 'prediction_file': 'raw/PREDICTIONS_R3.json', 'prediction_sha256': hashlib.sha256((R / 'raw/PREDICTIONS_R3.json').read_bytes()).hexdigest(), 'prereg_sha256': hashlib.sha256((R / 'PREREG_R3.json').read_bytes()).hexdigest(), 'blinded_validation': False})
wr('DECOMPOSITION_R3.json', {'idea': 'Insertion/contactstate, thicknessandresponse mustsharethe samephysical specimenport', 'mechanism': 'Tangentstiffness alone cannot determine forceatnominal displacement withoutaninterceptandretentioncondition', 'equations': ['F=K(delta-g) whencontactactive', 'g_eff=delta-F/K', 'Fsource-Ksource delta difference isnot correctedby moreaccuratet'], 'leaves': [{'name': 'stiffness_to_force', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'stopping_argument': 'Requires straightline force-displacementandzerointercept;intercept isexternally constrainedfromsamefixture, notdeduciblefromthickness'}, {'name': 'implied_gap', 'status': 'CONSTITUTIVE_CLOSURE', 'stopping_argument': 'Scalarintercept diagnostic; nonlinearcontactslip/projection/baselinescan allcontribute; not a geometricmeasurement'}, {'name': 'force_measurements', 'status': 'EXTERNALLY_MEASURED', 'locator': '2016Table1 and2015AbstractResults', 'stopping_argument': 'Published medianvsmean, contralateraltooth andfixtureconditionsnotmatched; cannotattributedifferencetoasingleretentionmechanism'}, {'name': 'cross_lab_transfer', 'status': 'UNKNOWN', 'stopping_argument': 'Do notpoolormergebetweenfixtureintercepts to manufactureaninterval;needamatchingexperiment'}]})
print('R3 frozen', p['rows'])
