from pathlib import Path
import json, datetime
H = Path(__file__).resolve().parents[1]
p = json.loads((H / 'PREREG_R1.json').read_text())
selected = [dict(case=r['case'], fdi=r['fdi']) for r in json.loads((H / 'raw/FE_RESULTS.json').read_text())['rows']]
p.update(round='R3', claim_type='capability', frozen_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(), capability='For measured contact geometry, bound the modeled tensile peak when individual contact forces remain unknown; identify force channels required for lab calibration', obstacle='A registered geometric contact map does not contain pressure or force shares', changed_operation='Replace a single area-pressure load by a conservative force simplex and saved stress-tensor basis per observed original proximity patch', consumer='Lab scientist deciding whether a total force measurement alone can calibrate the crown load model', selected_sites=selected, metric='Worst admissible peak tensile stress / area-weighted peak in the same fixed FE roof; stress-tensor linear superposition residual', metrics=dict(superposition_relative_tolerance=1e-08, force_conservation_N_max=1e-06, unobservable_ratio_threshold=1.2), decision='UNKNOWN_FORCE_SENSITIVE if the sharp upper peak/area-weighted peak>1.2; otherwise CONDITIONAL_LOW_SENSITIVITY. Mathematical simplex bound requires all forces>=0 and sum100N, uniform pressure within each patch, fixed linear elastic roof.', external_referent=dict(kind='closed_form', locator='https://web.stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf; convexity of maximum eigenvalue and convex maximum over a finite simplex', compared_quantity='max_alpha max_element max(lambda_max(sum alpha_j sigma_j),0) equals max_j max_element max(lambda_max(sigma_j),0), alpha_j>=0,sum alpha_j=1', refutes_us=True), strongest_equally_informed_control='Explicit direct P1 solves for each patch, plus one mixed load solve compared with stress-tensor superposition; no numerical method contest', physical_referent='No same-case contact pressure/stress measurement exists locally. The bound is conditional on model and geometric proximity patches, not physical stress validation.', falsifiers=['Random mixed load exceeds vertex bound', 'Saved basis fails independent direct solve at1e-8 relative residual', 'Injected2x tensor falsely passes superposition', '100N scalar is claimed to identify patch forces'], cost=dict(preparation='Original geometric contact patches and existing mesh/hash provenance retained', fit='none', discovery='R1,R2 and prior FE costs retained', validation='one direct mixed-force solve per selected tooth plus injected tensor failure', questions='factorization+all patch RHS included', fallback='UNKNOWN if no contact patch, conditional no-pressure bound otherwise', limits=dict(threads=1, disk_bytes=3000000000, ram_gb=3)))
(H / 'PREREG_R3.json').write_text(json.dumps(p, indent=2) + '\n')
d = dict(chain=['idea: calibrated force response from measured geometry', 'mechanism: linear elastic tensors superpose but peak tensile is convex in force shares', 'equation: sigma(alpha)=sum alpha_j sigma_j; max_simplex peak(sigma)=max_vertex peak', 'operation: one factorization and per-patch force RHS; independent mixed solve', 'representation: source patch and tensor-basis columns with force simplex', 'assumptions: fixed linear elastic material/support, finite uniform-pressure patches, known total100N scenario'], leaves=[dict(leaf='measured contact geometry', status='EXTERNALLY_MEASURED', stop='Original STL vertices; threshold-derived patches are a closure'), dict(leaf='uniform patch pressure', status='CONSTITUTIVE_CLOSURE', stop='No pressure image to resolve intra-patch force'), dict(leaf='positive normalized shares', status='DERIVED_UNDER_ASSUMPTIONS', stop='Unilateral normal force with fixed normalized total; tangential force excluded'), dict(leaf='convex tensor peak', status='DERIVED_UNDER_ASSUMPTIONS', stop='Maximum eigenvalue convex; Jensen inequality bounds each mixture by maximal vertex'), dict(leaf='pressure calibration', status='UNKNOWN', stop='N-1 independent patch-force channels required in general after total force; one pressure image can supply them')])
(H / 'DECOMPOSITION_R3.json').write_text(json.dumps(d, indent=2) + '\n')
print(selected)
