"""Freeze source selection and decision contract before running spatial consumers."""
from dental_release.paths import expand as _release_expand
from pathlib import Path
import datetime, hashlib, json, shutil
ROOT = Path(__file__).resolve().parents[1]
W = ROOT.parents[1]
X1 = W / 'results/LANE_X1_CROWN_LOOP'
DATA = Path(_release_expand('@DENTAL_WORK_ROOT@/LANE_X1_CROWN_LOOP/L005_lo_M1_k6/thin'))
CORPUS = Path(_release_expand('@DENTAL_CORPUS_ROOT@/europepmc/fulltext'))

def sha(p):
    h = hashlib.sha256()
    with open(p, 'rb') as f:
        for b in iter(lambda : f.read(1048576), b''):
            h.update(b)
    return h.hexdigest()

def dump(p, j):
    p.write_text(json.dumps(j, indent=2, ensure_ascii=False, allow_nan=False) + '\n')

def main():
    assert not (ROOT / 'PREREG_R1.json').exists(), 'Frozen contracts must not be overwritten'
    selected = {'optical_source': CORPUS / 'PMC10088447.xml', 'cure_source': CORPUS / 'PMC11012777.xml', 'geometry': X1 / 'raw/L005_lo_M1_k6_thin_geometry.json', 'resin_fe': X1 / 'raw/L005_lo_M1_k6_thin_printed_resin_fe.json', 'crown': X1 / 'exports/D1/crown.stl', 'stress': DATA / 'fe/printed_resin/solve_stress.npz', 'model': DATA / 'model.npz', 'geometry_cell': W / 'cells/design/crown_design_fe.py'}
    manifest = {}
    for (key, p) in selected.items():
        assert p.exists(), p
        local = None
        if key not in ('stress', 'model', 'geometry_cell'):
            q = ROOT / 'raw' / p.name
            shutil.copyfile(p, q)
            local = str(q.relative_to(ROOT))
        manifest[key] = {'original_path': str(p), 'local_path': local, 'sha256': sha(p), 'bytes': p.stat().st_size}
    dump(ROOT / 'SOURCE_MANIFEST.json', manifest)
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    common = {'frozen_utc': now, 'claim_type': 'capability', 'capability': 'Use two process/material chains on the same D1 anatomy to nominate laboratory manufacturing tests and identify the smallest missing local measurement', 'consumer': 'Prosthetics lab comparing matched D1 crowns; research screening only', 'patient_model': 'STS L005 lower first molar k6, X1 D1 thin crown, local frame in geometry JSON', 'obstacle': 'Published material means omit process, optical thickness, and strength/stress association; coupon-to-crown transfer is unmeasured', 'changed_operation': 'Bind published conditional rows to local optical rays and actual FE surface demand; test sufficiency before making a scalar process decision', 'source_manifest_sha256': sha(ROOT / 'SOURCE_MANIFEST.json'), 'comparison_design': 'Capability claim: answer with uncertainty and published quantities; same-information controls verify arithmetic, not a method competition', 'practice_without_information': 'Single bulk property and nominal CAD thickness; fixed 60-minute cure or fastest furnace cycle as explicit demo policies, not surveyed clinical practice', 'strongest_equally_informed_control': 'Independent row-wise source lookup and direct all-facet stress ratios; independent ray-triangle check for optical geometry', 'decision_scope': 'All numerical process selections are conditional surrogate screens; physical D1 release remains UNKNOWN without matched measurements', 'full_cost': {'preparation': 'Source discovery and inherited geometry/FE charged and explicitly unmeasured where not logged', 'fit': 'No statistical fitting; two-point optical closure only', 'discovery': 'Local ray sampling and actual surface-stress queries, one CPU process, threads <=4', 'validation': 'Published table agreement, adverse injections, scalar sufficiency witnesses, independent controls', 'questions': 0, 'fallback': 'UNKNOWN and an executable matched measurement request', 'physical_measurement': 'Not executed, laboratory acquisition required'}, 'prohibited_claims': ['clinical recommendation', 'validated crown fracture load', 'failure probability from mean plus SD', 'universal resin kinetics', 'optical TP as light transmittance', 'affine sensitivity without enclosure']}
    p = dict(common)
    p.update({'round': 'R1', 'chains': ['TM02', 'TM05'], 'metrics': {'table_absolute_error_max': 1e-10, 'stress_summary_error_MPa_per_N_max': 1e-06, 'ray_distance_control_error_mm_max': 1e-07, 'summary_identity_error_max': 0.0, 'sufficiency_downstream_difference_min': 1e-06, 'injected_errors_must_be_rejected': True}, 'TM02': {'operation': 'Two-knot log-affine empirical TP(thickness) closure, evaluated on crown normal-ray lengths; no extrapolation for acceptance', 'source': 'PMC10088447, DOI 10.4103/jips.jips_345_22, Tables 2/3; Katana HT, hydrothermal aging 134 C/5h', 'criterion': 'TP >=12 in the declared exposed surface subset, fastest source cycle; TP floor is a lab research target, not clinical', 'TP_floor': 12.0, 'thickness_domain_mm': [0.5, 1.0], 'source_dimensional_tolerance_mm': 0.01, 'ray_sample_max': 700, 'ray_offset_mm': 1e-05, 'visible_mask': 'z > cervical_margin+1 mm and outward local y-normal < -0.2; demo buccal exposure mask', 'resolution_level': 'PER_POINT geometric ray; PHENOMENOLOGICAL optical projection from POPULATION source', 'time_scale': 'HANDOVER: furnace and hydrothermal aging leave material state for optical assay', 'falsifier': 'Source coupon error, ray check error, or equal-mean thickness/TP states reverse visible decision', 'external_referent': {'kind': 'independent_measurement', 'locator': 'doi:10.4103/jips.jips_345_22; PMC10088447 Tables 2/3', 'compared_quantity': 'measured population TP at 0.5/1.0 mm and source furnace duration', 'refutes_us': True}}, 'TM05': {'operation': 'All-positive surface tensile demand from inherited D1 resin FE, compared with each cure-specific mean strength; keep contact and remote zones separate', 'source': 'PMC11012777, DOI 10.3390/ma17071496, Table 1; Resilab Temp 3D Lot1582, n=9 per cure', 'load_N': 150.0, 'loadcases': ['axial', 'offaxis30'], 'strength_screen': 'S_mean >= max_positive_tensile_surface_stress_at150N', 'process_objective': 'shortest source cure time passing each fixed-load surrogate screen', 'criterion': 'Report physical release UNKNOWN irrespective of surrogate acceptance', 'resolution_level': 'PER_SURFACE_REGION stress consumer from PER_POINT FE facets; POPULATION strength source', 'time_scale': 'HANDOVER: cure state precedes mechanical test', 'falsifier': 'Mean-strength scalar states with identical mean reverse local screen; absence of matched modulus/contact/strength validation blocks physical decision', 'external_referent': {'kind': 'independent_measurement', 'locator': 'doi:10.3390/ma17071496; PMC11012777 Table1', 'compared_quantity': 'measured population three-point flexural strength by cure duration', 'refutes_us': True}}})
    dump(ROOT / 'PREREG_R1.json', p)
    (ROOT / 'PREREG_R1.sha256').write_text(sha(ROOT / 'PREREG_R1.json') + '\n')
    leaves = [{'idea': 'Material process decisions are spatial queries', 'mechanism': 'Optical path and tensile-demand locations bind the material state to the geometry', 'equation': 'h(p)=first positive ray exit from the crown; sigma1_tan(p,F)=F*sigma1_tan(p,1N) for the frozen elastic model', 'operation': 'ray-triangle intersection and direct facet tensor evaluation', 'representation': 'point position, normal, path length, stress tensor, process-tagged source', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'assumptions': 'Piecewise planar mesh and fixed linear FE/contact pattern', 'stop_argument': 'This computes the declared mesh/model; segmentation truth and load-dependent contact topology are UNKNOWN'}, {'idea': 'Predict optical response', 'mechanism': 'Empirical thickness-conditioned optical response', 'equation': 'log TP(h)=(1-w)log TP0.5+w log TP1.0; w=(h-0.5)/0.5', 'operation': 'Evaluate two-point closure only within measured thickness support', 'representation': 'two process-specific knots', 'status': 'CONSTITUTIVE_CLOSURE', 'assumptions': 'Normal path substitutes flat coupon thickness; TP is CIE color-difference, not transmittance', 'stop_argument': 'No spectrum, optical scattering coefficients or curved-crown measurements identify this law; matched surface spectrophotometry would replace it'}, {'idea': 'Source optical and strength properties', 'mechanism': 'Published assays', 'equation': 'Reported mean/SD or observed min/max, retained as reported', 'operation': 'XML table lookup', 'representation': 'process x thickness or cure rows with locators', 'status': 'EXTERNALLY_MEASURED', 'assumptions': 'Source protocols only; no independence or individual-probability claim', 'stop_argument': 'Individual measurements unavailable. Source errors and protocol conflicts preserved'}, {'idea': 'Use bar strength on a crown', 'mechanism': 'Stress-to-strength screening', 'equation': 'r(p)=S(p)/(150*sigma1_plus(p)); accept fixed query if min_p r(p)>=1', 'operation': 'Spatial inequality and inverse required strength', 'representation': 'paired local strength and stress field', 'status': 'CONSTITUTIVE_CLOSURE', 'assumptions': 'Uniform strength and transferred modulus; no probability, fatigue or clinical load interpretation', 'stop_argument': 'Surface flaws, size effect, cure gradients, cement, modulus and contact are not identified by population flexural means'}, {'idea': 'Physical D1 release', 'mechanism': 'Predicted vs matched manufactured measurement', 'equation': 'Measured D1 fracture/TP compared with frozen predictions', 'operation': 'Laboratory assay', 'representation': 'batch-tagged surface TP and force/displacement/fracture origin', 'status': 'UNKNOWN', 'assumptions': 'No lab response during this run', 'stop_argument': 'No matched fabricated patient-model specimen exists on disk'}]
    dump(ROOT / 'DECOMPOSITION.json', {'round': 'R1', 'leaves': leaves, 'unresolved_numeric_error': 'No rigorous continuum geometry or FE discretization enclosure; any numerical model enclosure is explicitly scoped to the declared mesh and source boxes'})
    brief = '# X64 manufacturing: D1 spatial process consumer\n\nReuse PROOF_LANE4 L10/L11 sources and X1 D1. Build TM02 optical path and TM05 cure-strength screens, first test scalar sufficiency, then construct interval/inverse matched measurement queries. No scientific admission.\n'
    (ROOT / 'TASK.md').write_text(brief)
    print('R1 frozen', sha(ROOT / 'PREREG_R1.json'))
if __name__ == '__main__':
    main()
