import json, hashlib
from pathlib import Path
from datetime import datetime, timezone
P = Path(__file__).resolve().parent

def put(n, x):
    p = P / n
    p.write_text(json.dumps(x, ensure_ascii=False, indent=2) + '\n')
    return hashlib.sha256(p.read_bytes()).hexdigest()
base = {'lane': 'PROOF_LANE-constraint-net-r3', 'created_utc': datetime.now(timezone.utc).isoformat(), 'claim_type': 'capability', 'capability': 'Trace which verified source quantities serve a constraint, and which matched physical experiment can make its missing observation evaluable.', 'obstacle': 'Numbers are mistaken for residuals and missing experiments are mixed with software/administrative blockers.', 'consumer': 'a partner lab lab planning and DENT-UNC-PROPAGATION', 'no_physical_measurements': True, 'resource_limit': {'threads': 4, 'intermediates_bytes': 3000000000, 'heavy_job_policy': 'tasks/heavy_run.sh for >=4GB; none planned'}, 'cost': {'preparation': 'targeted local reads, hashes and small snapshots; timed in run', 'fit': 'none', 'discovery': 'manual semantic adjudication, elapsed recorded; labour/token cost UNKNOWN', 'validation': 'source checks, independent recount and actual injected faults', 'queries': 'finite edge/set queries timed', 'fallback': 'explicit unresolved blocker; no invented measurement'}}
a = base | {'construction': 'R3A', 'changed_operation': 'Exact file/pointer/value/hash verification plus a semantic admissibility decision for each of 25 proposals and 11 near misses; apply batch20 normalization correction in new validator.', 'metric_tolerance_decision': {'proposal_census': 'exactly all input proposals, missing rows forbidden', 'source_equality': 'exact JSON numeric equality and SHA256; tolerance 0', 'semantic_gate': 'only a response difference with correct unit, support and estimand can become a numeric gap; parameters and predictions stay contextual', 'mutations': 'every declared fault must be rejected by actual validator; zero allowed misses'}, 'strongest_equally_informed_control': 'Independent direct pointer reader and rational arithmetic on frozen source records; no algorithm superiority claim.', 'external_referent': {'kind': 'external_review', 'locator': '../LANE_XREVIEW_BATCH20/REVIEW_PROOF_LANE_CONSTRAINT_NET_R2.json', 'compared_quantity': 'scope, normalization integrity and strict residual coverage', 'refutes_us': True}, 'falsifier': 'Any accepted number has wrong hash/unit/estimand or an injected mutation passes.', 'physical_observation_policy': 'X58 release deltas and X31 published unsigned aggregate moments remain distinguished from anatomical truth and signed individual pose.'}
b = base | {'construction': 'R3B', 'changed_operation': 'Replace unidentified residual by named specimen/measurement/outcome obligation where physically justified; keep computational and administrative exceptions explicit. Group by experiment with AND requirements and specimen compatibility.', 'metric_tolerance_decision': {'coverage': 'Every OPEN/UNKNOWN must have numeric sourced gap OR BLOCKED_ON_PHYSICAL_MEASUREMENT with nonempty exact measurement, specimen and deciding observation. Otherwise strict validator fails.', 'counts': 'Exact edge-ID set cardinalities; distinguish touched vs all-observation-requirements supplied vs empirically closed. Do not equate plan coverage with physical closure.', 'sufficiency': 'Two equal summary states at machine precision, compare matched-edge downstream closure; if differing retain specimen join/state identity.', 'controls': 'actual corruptions of blocker contract, units, sources and planning map must fail'}, 'strongest_equally_informed_control': 'Direct per-edge subset enumeration; compare grouping with X71 original measurement protocol rows.', 'falsifier': 'Any claimed supplied edge lacks a required measurement, compatible specimen or retained prerequisite; any code/license-only blocker is labelled physical.', 'external_referent': {'kind': 'external_review', 'locator': '../LANE_XREVIEW_BATCH20/REVIEW_PROOF_LANE_CONSTRAINT_NET_R2.json', 'compared_quantity': '57 unidentified residuals and required-observation scope, combined with X71 frozen plan', 'refutes_us': False}, 'unknown_policy': 'Strict coverage may honestly fail for software/legal/reproducibility gaps; document rather than relabel to obtain PASS.'}
for (name, x) in [('PREREG_R3A.json', a), ('PREREG_R3B.json', b)]:
    h = put(name, x)
    (P / (name + '.sha256')).write_text(h + '  ' + name + '\n')
put('FROZEN_PREDICTIONS.json', {'frozen_utc': base['created_utc'], 'scope': 'Audit/plan predictions only; no new physical response predicted or observed.', 'predictions': ['All eight measured:false proposals must be refused as measured gaps.', 'Finite generic edge count is insufficient for same-specimen evaluability.', 'Physical closure count remains zero without new observations.'], 'prereg_sha256': {n: hashlib.sha256((P / n).read_bytes()).hexdigest() for n in ['PREREG_R3A.json', 'PREREG_R3B.json']}})
(P / 'FROZEN_PREDICTIONS.json.sha256').write_text(hashlib.sha256((P / 'FROZEN_PREDICTIONS.json').read_bytes()).hexdigest() + '\n')
put('DECOMPOSITION.json', {'idea': 'Map missing information to matched measurements, not invented scalar residuals.', 'mechanism': 'An observation supplies a typed quantity at a location/state on a named specimen; a consumer joins compatible ports.', 'equations': ['gap = observed - predicted, only for identical estimand, unit, specimen and protocol', 'evaluable(e,S) = all(required measurements in S) AND specimen/state compatibility AND computation prerequisites', 'closed(e) requires observed outcome and independent validation; evaluable does not imply closed'], 'operation': 'hash+pointer read, semantic adjudication, typed obligation join, direct set recount', 'representation': 'edge-specific numeric gaps, contextual quantities, measurement obligations, computational exceptions', 'leaves': [{'name': 'file/value identity', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'stop': 'Byte SHA256 and exact JSON comparison suffice for file identity; not source scientific truth.'}, {'name': 'proposal estimand', 'status': 'UNKNOWN', 'stop': 'Inspect original block and source definitions; job review does not validate new quantity binding.'}, {'name': 'external source observations', 'status': 'EXTERNALLY_MEASURED', 'stop': 'Preserve published group/support scope; no individual signed pose inference.'}, {'name': 'lab compatibility and cost', 'status': 'CONSTITUTIVE_CLOSURE', 'stop': 'X71 protocols are planning assumptions; actual instruments/time and measurements missing.'}, {'name': 'physical residual', 'status': 'UNKNOWN', 'stop': 'No same-specimen observation; name precise measurement and retain null.'}], 'rigorous_enclosure': 'Exact finite set counts and rational residual arithmetic only; no affine sensitivity or full physical enclosure claimed.'})
put('CURRENT_WORK_STATE.json', {'milestone': 'PREREG_FROZEN', 'current': 'R3A source verification and semantic adjudication', 'latest_gate': 'R2 strict numerical completeness FAIL preserved; batch20 correction identified', 'next_operation': 'snapshot selected small inputs; adjudicate 25 proposals and classify 57 missing residuals', 'review_state': 'PENDING_INDEPENDENT_REVIEW'})
(P / 'COMMANDS.md').write_text("# Exact commands and failures\n\nInitial reads used cat/sed and targeted rg on the paths in SOURCE_REUSE.md.\n\nFailed discovery: `./graph working rank --query 'uncertainty propagation measurement constraints' --limit 3` exited 2 (this CLI has no --query). Retry uses supported `--kind evidence_definition --limit 3`.\n\n```bash\npython3 initialize.py\n```\n")
(P / 'SOURCE_REUSE.md').write_text('Read R2 HANDOFF, net, acquisition ledger, validator/common; batch20 review and validator patch; BodyTwin PROPOSALS_V1; X71 measurement protocol and plan. Targeted rg on dental/cells, R2/X71 code, bodytwin/results/LANE_*/RESULTS.md and bunny48/dental/*/RESULTS.md found NET-REPLICA-CT and NET-K02 predecessors. No tree copied. OLD_DENTAL_CELL_INDEX inspected for CBCT/XCT/REFUTED cells; no physical constants borrowed or rederived here. Breakthrough §0, direction7 and §4 read; scope is explicitly requested independent audit and lab-obligation construction.\n')
