"""Freeze contracts before each construction; never overwrite a preregistration."""
from dental_release.paths import expand as _release_expand
import datetime as dt
import hashlib
import json
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parent
CORPUS = Path(_release_expand('@DENTAL_CORPUS_ROOT@/europepmc/fulltext'))

def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()

def freeze(name, item):
    path = ROOT / ('PREREG_' + name + '.json')
    item.update(schema='x45-preregistered-construction-v1', construction=name, frozen_utc=dt.datetime.now(dt.timezone.utc).isoformat(), review_state='PENDING_INDEPENDENT_REVIEW', cost_contract={'preparation': 'targeted local XML reads, extraction, independent transcription and code', 'fit': 'all fits and trial parameters timed; no hidden optimization trials', 'discovery': 'source inventory, failed commands and human/model reasoning; token cost UNKNOWN', 'validation': 'held published aggregate points, same-information arithmetic control, injected faults', 'queries': 'all demonstration calls included in replay timing', 'fallback': 'unmatched physical measurement and specimen acquisition NOT_RUN; cost UNKNOWN', 'inherited': 'X43/X44 and old cells read only; their historical acquisition/research cost UNKNOWN'}, data_visibility='Published tables were read during source selection. Historical holdout, NOT blind or newly acquired.', resolution='POPULATION', timescale='HANDOVER', sensitivity_contract='Only exact/interval-enclosed algebra is decisive. Physical interpolation/model remainder is UNKNOWN.')
    item['source_sha256'] = {n: sha(CORPUS / (n + '.xml')) for n in item['source_ids']}
    if path.exists():
        old = json.loads(path.read_text())
        item['frozen_utc'] = old['frozen_utc']
        if old != item:
            raise RuntimeError('Frozen preregistration drift: ' + name)
    else:
        path.write_text(json.dumps(item, indent=2, ensure_ascii=False) + '\n')
    print(name, sha(path))
round_name = sys.argv[1]
if round_name == 'initial':
    freeze('K31_R1', {'chain': 'K31', 'claim_type': 'information_link', 'capability': 'Ask how published implant stability changes through the first 90 healing days, rather than carrying insertion ISQ as a constant.', 'obstacle': 'No temporal observation state; BIC is incorrectly tempting as a substitute for ISQ.', 'changed_operation': 'Load Table 2 as protocol-indexed group observations; fit a decreasing relaxation observation law to days 0,7,14.', 'consumer': 'Research observer for DENT-IF-BONE-IMPLANT; NOT a BIC, stiffness, failure or loading recommendation.', 'source_ids': ['PMC10092180'], 'external_referent': {'kind': 'independent_measurement', 'locator': 'doi:10.1111/cid.13140; PMC10092180 Table 2', 'compared_quantity': 'group-mean ISQ at days 21,28,60,90', 'refutes_us': None}, 'model': 'y(t)=y(0)-A*(1-exp(-t/tau)); A>=0, tau>0; tau grid 0.1..1000 days, 2001 log-spaced points; least squares A for each tau', 'training_days': [0, 7, 14], 'held_days': [21, 28, 60, 90], 'metric': {'name': 'absolute error per held group mean', 'unit': 'ISQ', 'tolerance': 1.0, 'decision': 'all 8 points must pass; no empirical superiority if any fail'}, 'practice_without_information': 'carry initial ISQ unchanged over healing; this is the absent-time state in our project, not a survey of clinical practice', 'strongest_equally_informed_control': 'independent scalar tau-grid and least-squares A; checks correctness, not the information-link comparator', 'falsifier': 'any held error >1 ISQ, non-finite fit, or injected +10 ISQ held prediction must fail', 'sufficiency_test': 'two group trajectories shifted to identical starting ISQ=70 exactly; measure difference at day90; do not claim the shifted groups are actual matched individuals', 'uncertainty': 'published SD is between implants, not prediction sigma; repeated-measures covariance and group-mean CI UNKNOWN; printed rounding +-0.05 ISQ only'})
    freeze('K34_LTD_R1', {'chain': 'K34', 'claim_type': 'information_link', 'capability': 'Query the lower-tail strength of a specified zirconia coupon after the published hydrothermal exposure and cyclic loading.', 'obstacle': 'An unaged nominal strength or a single universal aging multiplier discards changes of distribution shape.', 'changed_operation': 'Exposure-keyed material state retains both Weibull shape m and scale sigma0 from Table4, rather than one nominal strength.', 'consumer': 'A laboratory coupon reliability query and a material-state port toward K13; crown-volume and clinical-year promotion must be refused.', 'source_ids': ['PMC10569846'], 'external_referent': {'kind': 'independent_measurement', 'locator': 'doi:10.1055/s-0042-1755630; PMC10569846 Tables 3,4 and Methods', 'compared_quantity': 'reported aged/unaged m,sigma0 and their conditional coupon-strength quantiles', 'refutes_us': None}, 'protocol': {'temperature_C': 122, 'pressure_bar': 2, 'hours': 8, 'cyclic_load_N': 50, 'cycles': 240000, 'frequency_Hz': 1.1, 'specimen_diameter_mm': 15, 'specimen_thickness_mm': 1, 'antagonist': '2mm stainless-steel stylus; water at room temperature', 'outcome': 'biaxial fracture strength after cyclic exposure, NOT a fatigue-life curve'}, 'model': 'Pf(sigma)=1-exp(-(sigma/sigma0)^m); Qp=sigma0*(-ln(1-p))^(1/m)', 'query_probability': 0.05, 'metric': {'name': 'independent formula/parsing agreement', 'unit': 'MPa; dimensionless', 'tolerance_relative': 1e-12, 'decision': 'all 8 distributions and 8 quantiles match independent arithmetic; 4 incompatible promotions must fail'}, 'practice_without_information': 'unaged Table4 distributions held fixed under hydrothermal exposure', 'strongest_equally_informed_control': 'math.exp/log inverse and numeric inversion of published Weibull CDF', 'falsifier': 'wrong grade/protocol, m change ignored, or injected sigma0*1.1 must fail; unquantified statistical CI prevents a population-strength decision', 'sufficiency_test': 'construct two Weibull states with mean exactly 500MPa to machine precision and m=5 versus15; compare Q0.05; minimum extension is shape plus exposure alongside scale', 'uncertainty': 'Table4 printed rounding enclosed rigorously; m/sigma0 sampling CI and covariance UNKNOWN (n=10 per state); no new significant aging effect asserted'})
    freeze('K34_WEAR_R1', {'chain': 'K34', 'claim_type': 'capability', 'capability': 'Determine whether a constant per-cycle wear coefficient can transfer from early to later published composite wear measurements.', 'obstacle': 'Archard coefficient cannot be calibrated from unnamed antagonist, unmeasured sliding distance and mass mislabeled volume.', 'changed_operation': 'Import dimensioned cumulative mass-loss observations (not volume) and test the constant-rate closure on held cycles.', 'consumer': 'Wear-state observer; geometry/volume consumer must reject absent density and sliding-distance inputs.', 'source_ids': ['PMC10258403'], 'external_referent': {'kind': 'independent_measurement', 'locator': 'doi:10.18502/fid.v20i10.12609; PMC10258403 Table3 and Methods', 'compared_quantity': 'mean mass loss at 40000,80000,120000 cycles, in mg', 'refutes_us': None}, 'model': 'mass_mg=k*cycles; zero intercept, nonnegative least-squares k', 'training_cycles': [5000, 10000, 20000], 'held_cycles': [40000, 80000, 120000], 'metric': {'name': 'absolute held mean mass error', 'unit': 'mg', 'tolerance': 'max(0.1mg,1.96*published_SEM_mg)', 'decision': 'all15 held points must pass; source SEM is a comparison scale, not a validated prediction interval'}, 'practice_without_information': 'no measured service-wear state in dental; no fabricated universal coefficient', 'strongest_equally_informed_control': 'scalar dot-product rate fit; model agreement does not establish transfer', 'falsifier': 'any held point outside frozen tolerance; injected held+10mg must fail; missing rho must reject mass-to-volume', 'sufficiency_test': 'shift FiltekZ250 and Admira measured curves to identical first loss=1mg, compare later increments; an early cumulative loss alone cannot determine future wear', 'uncertainty': 'published SEM pertains to aggregate observations; balance resolution0.1mg; density, wear-tip material, sliding distance and hydration bias UNKNOWN; no clinical-cycle conversion'})
elif round_name == 'successor':
    freeze('K31_R2', {'chain': 'K31', 'claim_type': 'capability', 'parent': 'K31_R1', 'capability': 'Reconstruct dip and recovery as a protocol/time-indexed observation state within the measured healing window.', 'obstacle': 'A monotone relaxation state cannot represent the observed recovery and reversed initial rank.', 'changed_operation': 'Replace one decay state by a measured temporal branch table; piecewise-affine interpolation of days0,14,28,90; block BIC/stiffness and time extrapolation.', 'consumer': 'Temporal observational handover port; not causal bone formation.', 'source_ids': ['PMC10092180'], 'external_referent': {'kind': 'independent_measurement', 'locator': 'doi:10.1111/cid.13140; PMC10092180 Table2', 'compared_quantity': 'held group-mean ISQ days7,21,60', 'refutes_us': None}, 'training_days': [0, 14, 28, 90], 'held_days': [7, 21, 60], 'metric': {'name': 'absolute error per held group mean', 'unit': 'ISQ', 'tolerance': 1.0, 'decision': 'all6 pass; no lower tolerance or change of R1 gate'}, 'practice_without_information': 'static initial ISQ (unchanged R1 project comparator)', 'strongest_equally_informed_control': 'independent barycentric scalar interpolation and interval bounds', 'falsifier': 'any held error >1ISQ; phase/time reversed; injected +10ISQ; clinical/patient/constitutive promotion must refuse', 'sufficiency_test': 'same R1 exact-identical initial state witness; retain full temporal curve, time and protocol as smallest supported observational extension', 'uncertainty': 'rigorous printed-rounding interval for declared affine representation; interpolation/model error between measured times has NO rigorous bound; population covariance/individual predictions UNKNOWN'})
    freeze('K34_WEAR_R2', {'chain': 'K34', 'claim_type': 'capability', 'parent': 'K34_WEAR_R1', 'capability': 'Ask whether retaining a run-in loss plus later wear rate repairs transfer.', 'obstacle': 'Early mass loss need not start with the subsequent steady-state coefficient.', 'changed_operation': 'mass_mg=run_in+k*cycles, run_in>=0,k>=0; training/held cycles and tolerance exactly as R1.', 'consumer': 'Mass-state observer only.', 'source_ids': ['PMC10258403'], 'external_referent': {'kind': 'independent_measurement', 'locator': 'doi:10.18502/fid.v20i10.12609; PMC10258403 Table3', 'compared_quantity': 'held mean mass loss in mg', 'refutes_us': None}, 'training_cycles': [5000, 10000, 20000], 'held_cycles': [40000, 80000, 120000], 'metric': {'name': 'absolute held mean mass error', 'unit': 'mg', 'tolerance': 'max(0.1mg,1.96*published_SEM_mg)', 'decision': 'all15 pass; else abandon single affine transfer'}, 'practice_without_information': 'no measured wear state', 'strongest_equally_informed_control': 'independent closed-form OLS/intercept with boundary candidates for NNLS', 'falsifier': 'any held failure or injected+10mg; no invented density or cycles/year conversion', 'sufficiency_test': 'same identical-first-loss witness as R1', 'uncertainty': 'numerical affine fit enclosed in explicit algebraic interval; physical extrapolation remainder has no rigorous enclosure and is UNKNOWN'})
elif round_name == 'envelope':
    freeze('K34_WEAR_R3', {'chain': 'K34', 'claim_type': 'capability', 'parent': 'K34_WEAR_R2', 'capability': 'Return the smallest conditional cumulative-wear interval supported by bracketing measurements instead of extrapolating a failed rate law.', 'obstacle': 'The new measurements falsify both one-coefficient and run-in+rate transfer; density/sliding information is still absent.', 'changed_operation': 'Measurement-state with ordered cycle/mass knots. Under explicit monotonic cumulative mean assumption, return outward-rounded bracket hull; do not interpolate or extrapolate.', 'consumer': 'Interval mass-budget query, with geometry conversion blocked until same-material density and area are measured.', 'source_ids': ['PMC10258403'], 'external_referent': {'kind': 'independent_measurement', 'locator': 'doi:10.18502/fid.v20i10.12609; PMC10258403 Table3', 'compared_quantity': 'held mean mass loss containment at10k,40k,80k cycles', 'refutes_us': None}, 'training_cycles': [5000, 20000, 120000], 'held_cycles': [10000, 40000, 80000], 'metric': {'name': 'conditional monotone bracket containment', 'unit': 'mg', 'tolerance': 0, 'decision': 'all15 means contained; 5 extrapolation and5 density-less promotions must refuse; report interval widths'}, 'practice_without_information': 'no measured wear state', 'strongest_equally_informed_control': 'independent adjacent-knot min/max hull', 'falsifier': 'any nonmonotone anchor or held mean outside envelope; +10mg injected value fails', 'sufficiency_test': 'same exact-identical initial state witness; smallest supported extension is protocol-indexed ordered cumulative-state observations, not one fitted coefficient', 'uncertainty': 'outward rounding +-0.005mg for source1decimal means; mean monotonicity is a stated closure; sourceSEM is separate and cannot be an absolute uncertainty bound'})
else:
    raise SystemExit('expected initial/successor/envelope')
