"""Write immutable construction contracts. Does not inspect numerical outcomes."""
import datetime, hashlib, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()

def write(name, obj):
    p = ROOT / name
    if p.exists():
        return
    p.write_text(json.dumps(obj, indent=2, ensure_ascii=False, allow_nan=False) + '\n')
    p.with_suffix('.sha256').write_text(sha(p) + '  ' + p.name + '\n')

def main():
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    common = dict(claim_type='capability', frozen_utc=now, consumer='LANE_X1B_CROWN_LOOP/LAB_PROTOCOL.md', review_state='PENDING_INDEPENDENT_REVIEW', full_cost={'preparation': '14 small source snapshots; source reading and implementation time UNKNOWN', 'fit': 'charge every MLE/profile fit', 'discovery': 'all source screening retained', 'validation': 'exact binomial/gamma references and injected faults', 'queries': 'measure wall time', 'fallback': 'UNKNOWN for physical metrology and laboratory testing'}, affine_sensitivity='No empirical affine gap transfer certified; interval guard exact only within declared additive observation model')
    r1 = dict(common, id='X51_R1', capability='Choose fixed lot-test sample counts, distinguish ISO mean criterion from lower-tail risk, retain censored observations', obstacle='Three runouts do not establish a small population failure probability; fitted Weibull shape is not known shape', changed_operation='Invert exact one-sided binomial and known-shape gamma tests; add producer power; unknown-shape profile is explicitly approximate', resolutions={'strength_and_risk': 'POPULATION within fixed specimen/process population', 'implant_cells': 'PER_TOOTH configuration; sample aggregates POPULATION'}, metrics={'x25_cp_absolute_error_max': 1e-10, 'x25_load_absolute_error_N_max': 1e-06, 'hand_control_error_max': 1e-10, 'false_acceptance_max': 0.05, 'power_min': 0.8, 'identity_error_max': 0.0, 'faults_rejected': 'all'}, decision_criterion='Capability PASS only with exact controls passing, finite/approximate claims separated and no ISO conformity asserted', controls=['Independent explicit binomial sum and zero-failure hand formula', 'X25 saved censored AFT fits and quantile inversions', 'SciPy Weibull full-data MLE versus profiled shape solver', 'Closed-form gamma pivot for COMPLETE or prospectively TYPE_II samples only'], strongest_equally_informed_control='Conventional exact binomial/gamma inversion and censored Weibull MLE; implementation check, no method competition', practice={'ISO6872': '2024 clauses 7.3.2.2, 7.3.2.4: >=10, preferably30 bars; mean criterion; Weibull >=15', 'ISO14801': '2016 fixed-cycle load-endurance procedure; >=3 survivors at endured load, not 10% risk bound', 'our_lab_current_protocol': 'X1b 12 crowns per thickness/angle, 72 total, contrast experiment; actual partner QC UNKNOWN'}, falsifiers=['Treat a bar as a crown or mean as a 5% quantile', 'Count early censoring as completed survival', 'Use estimated shape as exact known shape', 'Use Type-I censoring in exact Type-II pivot', 'Change sample count after observing failures'], scenarios={'alpha': 0.05, 'p_bad': 0.1, 'p_good': 0.01, 'producer_power': 0.8, 'mean_threshold_MPa': 300, 'shape_scenarios': [3, 5, 10], 'mean_ratios': [1.05, 1.1, 1.2], 'profile_alpha': 0.05, 'strength_demo_threshold_MPa': 300, 'profile_is_finite_sample_certificate': False}, external_referent={'kind': 'published_dataset', 'locator': 'https://doi.org/10.5281/zenodo.22306621', 'compared_quantity': '36 specimen failure/censor endpoints and X25 risk-load reproduction', 'refutes_us': True})
    r2 = dict(common, id='X51_R2', capability='Quantify weekly detection delay, physical observability and false alarms before a declared marginal-gap rejection', obstacle='Scanner bias and real process drift can cancel in a finished-coupon scan; weekly data cannot preempt arbitrary between-check changes', changed_operation='Add a stable independent reference and signed region observation; separate b and d by y_reference=b, y_coupon=b+d', metrics={'identity_error_max': 0.0, 'downstream_difference_min_um': 1.0, 'false_alarms_expected_per_year_max': 0.05, 'analytic_mc_error_max': 0.005, 'preemption_probability_min': 0.95, 'faults_rejected': 'all'}, decision_criterion='Report conditional detect-before-rejection fraction. Empirical preemption remains UNKNOWN unless matched time-resolved scanner/sinter/gap data exist', strongest_equally_informed_control='Direct two-channel signed Shewhart and matrix inverse with same observations', controls=['NIST Gaussian-tail Shewhart reference', 'Finished-coupon-only channel ablation', 'Instantaneous jump after weekly QC must defeat unconditional claim'], falsifiers=['Rename cross-sectional source differences as measured per-day drift', 'Use RMS as signed marginal-gap bound', 'Report unknown noise as measured', 'Declare first remake time empirically without paired gap data'], scenarios={'weeks': 52, 'days': 364, 'replicates': 5, 'per_scan_sigma_um': 10, 'noise_status': 'PHENOMENOLOGICAL', 'noise_debt': 'Measure independent-reference repeatability and coupon/region covariance in same lab', 'baseline_gap_um': 50, 'rejection_gap_um': 120, 'gap_status': 'PHENOMENOLOGICAL engineering scenario, not clinical recommendation', 'sigma_baseline_known': True, 'monte_carlo_paths': 20000, 'seed': 5102, 'ramp_durations_days': [14, 56, 168], 'source_amplitude': 'X10 Prime SB1/SB2 positional-median difference and X14 micrometer within-material/axis position differences', 'source_time_law': 'NOT_MEASURED: impose ramps explicitly; amplitudes also not identified temporal drift', 'counterexample': {'real_process_drift_um': 80, 'scanner_bias_um': -80}}, external_referent={'kind': 'independent_measurement', 'locator': 'https://doi.org/10.3390/ma18143217 Table2; https://doi.org/10.1186/s12903-025-06584-0 abstract', 'compared_quantity': 'position-dependent shrinkage and scanner pre/post-calibration aggregate; NOT alarm-day validation', 'refutes_us': True})
    write('PREREG_R1.json', r1)
    write('PREREG_R2.json', r2)
    leaves = [('binomial endpoint', 'DERIVED_UNDER_ASSUMPTIONS', 'P(K<=c|p_bad)<=alpha; iid specimens, prospectively fixed n/c/load/configuration. Early censor assignments retained.', 'Counts suffice only for one frozen threshold/horizon; not general strength/lifetime.'), ('Weibull law', 'CONSTITUTIVE_CLOSURE', 'F(s)=1-exp(-(s/eta)^m). Microdefect weakest-link interpretation does not establish a universal lot law.', 'Flaw population/geometry/process must be measured before transfer; atomistic detail cannot identify missing batch parameters.'), ('known-shape gamma', 'DERIVED_UNDER_ASSUMPTIONS', 'Y=S^m is exponential; complete sum Gamma(n,eta^m); TypeII exposure Gamma(r,eta^m).', 'Stop at finite distribution identity; estimated m invalidates this exact pivot.'), ('unknown shape', 'UNKNOWN', 'Profile likelihood cutoff chi2_1(0.90) for one-sided95 is asymptotic; finite-sample coverage not proved.', 'Use conservative endpoint alternative until a separately validated nuisance-uniform confidence construction exists.'), ('ISO observables', 'EXTERNALLY_MEASURED', 'Primary standard text: ISO6872 mean MPa and ISO14801 fixed-cycle maximum endured load.', 'Standard scope and complete protocol matter; statistical tool does not certify other mechanical/chemical requirements.'), ('source measurements', 'EXTERNALLY_MEASURED', 'X23 124 strength rows; X25 36 failure/censor records; X10 signed/scanner summaries; X14 measured shrinkage.', 'Retain source locator and regime; aggregates are not weekly lab observations.'), ('drift observation', 'DERIVED_UNDER_ASSUMPTIONS', '[r,y]^T=[[1,0],[1,1]][b,d]^T + errors. Rank1 coupon-only versus rank2 paired reference.', 'Scalar additive common bias is declared model. Angle/curvature/scale/bending need more independent signatures.'), ('gap transfer', 'CONSTITUTIVE_CLOSURE', 'g(t)=g0+d(t) in signed marginal region, direct d in micrometres. Scale a maps to L*a only for specified dimension and geometry.', 'Empirical 3D seating/intaglio sensitivity remains UNKNOWN; no source positional RMS -> margin shortcut.'), ('time/noise', 'UNKNOWN', '10um iid Gaussian per scan and imposed 14/56/168-day ramps are scenario closures.', 'Require same-body same-lab longitudinal reference/coupon scans and seated gaps; source amplitudes do not identify slopes.'), ('multiple looks', 'DERIVED_UNDER_ASSUMPTIONS', 'Bonferroni 2 channels x 2 tails x52 checks; per-tail alpha/(4*52).', 'Union bound does not need independence, but Gaussian calibrated marginal tails do.')]
    write('DECOMPOSITION.json', {'frozen_utc': now, 'idea': 'lab release backed by enough specimens and observable manufacturing drift', 'mechanism': 'population tail inference plus sensor/process identifiability', 'operation': 'exact test inversion -> fixed plan; paired signed metrology -> chart -> release hold', 'representation': 'specimen records with censor flags and region/date/protocol-bound reference/coupon observations', 'leaves': [dict(name=n, status=s, equation_or_basis=e, stopping_argument=t) for (n, s, e, t) in leaves]})
    write('FROZEN_PREDICTIONS.json', {'frozen_utc': now, 'physical_measurement_performed': False, 'source_exposure': 'retrospective; parent outcomes read before this contract', 'prereg_sha256': {p.name: sha(p) for p in sorted(ROOT.glob('PREREG_R[12].json'))}, 'predictions': {'zero_failure_n10pct': 29, 'joint_four_n10pct': 42, 'zero_failure_n5pct': 59, 'three_runouts_upper95': 1 - 0.05 ** (1 / 3), 'coupon_only_nullspace': '[b,d]=[-80,80] and [0,0] produce identical0; gaps130 and50um', 'weekly_universal_preemption': 'REFUTED by change after a QC check', 'empirical_alarm_day': 'UNKNOWN without time-resolved matched metrology'}})
    print('Contracts frozen; existing contracts preserved')
if __name__ == '__main__':
    main()
