import datetime
from common import ROOT, read, sha
from freeze import write

def main():
    r = {'id': 'X51_R3', 'frozen_utc': datetime.datetime.now(datetime.timezone.utc).isoformat(), 'claim_type': 'capability', 'parent': 'R2 weekly universal preemption REFUTED and14-day ramp gives no advance alarm; all original outcomes retained', 'capability': 'A self-calibrating paired chart plus an explicit latest safe release time within bounded drift/error model', 'obstacle': 'Known baseline variance is unavailable in real lab; chart signal can arrive after rejection and cannot certify next7 days', 'changed_operation': 'Use finite-baseline Student predictive thresholds and interval horizon guard; UNKNOWN slope/error forces HOLD', 'consumer': 'X1b laboratory protocol additions, own-lane JSON release interface', 'metrics': {'false_expected_channel_signals_per_year_max': 0.05, 'MC_absolute_error_max': 0.005, 'bounded_scenario_unsafe_releases_max': 0, 'identity_error_max': 0, 'faults_rejected': 'all'}, 'decision_criterion': 'Conditional guard capability PASS if0 unsafe release intervals over every declared error corner and fault injection rejects missing/understated slope. Real release validation UNKNOWN', 'strongest_equally_informed_control': 'Exact interval endpoint enumeration and ordinary Student prediction interval, same observations and bounds', 'falsifiers': ['Horizon guard releases a crossing inside7 days', 'Return release with missing noise/slope/gap mapping calibration', 'Treat prediction interval as physical hard error bound', 'Treat supplied assumed slope as externally measured', 'Reuse optional test sample plan after looking at results'], 'external_referent': {'kind': 'closed_form', 'locator': 'https://www.itl.nist.gov/div898/handbook/prc/section2/prc22.htm; interval monotonicity of g0+dhat+e+v*t', 'compared_quantity': 'Student predictive pivot and all-corner affine enclosure under declared bounded model', 'refutes_us': True}, 'scenarios': {'baseline_n': 100, 'weekly_replicates': 5, 'weeks': 52, 'per_scan_sigma_um': 10, 'sigma_status': 'PHENOMENOLOGICAL', 'baseline_seed': 5103, 'paths': 20000, 'error_each_observation_um': 10, 'guard_error_d_um': 20, 'horizon_days': 7, 'gap0_um': 50, 'gap_limit_um': 120, 'slope_source': 'R2 scenario amplitude/duration, NOT measured temporal bound', 'ramp_durations_days': [14, 56, 168]}, 'enclosure': 'd in[dhat-20,dhat+20], 0<=increase<=v_bound*dt gives g(t)<=g0+dhat+20+v_bound*dt. Exact within this model; floating point arithmetic not interval-certified.', 'physical_leaves': {'reference_stability': 'UNKNOWN', 'noise_covariance': 'UNKNOWN', 'time_slope_bound': 'UNKNOWN', 'gap_map': 'UNKNOWN'}, 'full_cost': {'preparation': 'baseline100 + weekly5 paired measurements required prospectively; simulation only now', 'fit': 'mean/SD, no iterative fit', 'discovery': 'parents and source screening charged', 'validation': '20000 baseline/week simulations and all deterministic error corners', 'questions': 'release/hold query timed', 'fallback': 'hold and independent rescan/measure; physical cost UNKNOWN'}}
    write('PREREG_R3.json', r)
    write('DECOMPOSITION_R3.json', {'frozen_utc': r['frozen_utc'], 'idea': 'certify a finite horizon instead of waiting for chart alarm', 'leaves': [{'name': 'Student pivot', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'relation': '(newmean-baselinemean)/(s*sqrt(1/n+1/N))~t_(N-1) for iid normal readings', 'stopping_argument': 'finite-sample identity depends on stable independent normal baseline and future samples; covariance/spatial mapping remain empirical'}, {'name': 'horizon enclosure', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'relation': r['enclosure'], 'stopping_argument': 'endpoint maximization exact for affine additive model; actual seated gap map UNKNOWN'}, {'name': 'hard error/slope', 'status': 'UNKNOWN', 'relation': '20um and amplitude/duration chosen stress contract', 'stopping_argument': 'requires traceable bound measurements and operation-triggered recheck; abrupt fault can violate it'}]})
    write('FROZEN_PREDICTIONS_R3.json', {'frozen_utc': r['frozen_utc'], 'prereg_sha256': sha(ROOT / 'PREREG_R3.json'), 'measurement_performed': False, 'predictions': {'missing_calibration': 'HOLD_UNKNOWN', 'fast_ramp': 'Initial hold may be required because7-day uncertainty exceeds available margin', 'finite_baseline': 'nominal annual expected channel-signals<=.05 under Student model', 'without_true_slope_bound': 'NO_GUARANTEE'}})
    print('R3 preregistration frozen')
if __name__ == '__main__':
    main()
