from dental_release.paths import expand as _release_expand
import datetime, json, sys
from planning import HERE, read, write, sha
round_ = sys.argv[1]
path = HERE / f'PREREG_{round_}.json'
if path.exists():
    raise SystemExit('Frozen prereg exists; refusing overwrite')
common = dict(schema='X71-prereg-v1', round=round_, claim_type='information_link', timestamp_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(), ability='Choose the cheapest sufficient first-week acquisition for explicit dental consumer decisions without crediting incompatible specimens or incomplete chains', consumer='Prosthodontic laboratory and X40 measurement plan; proposed graph edges, not native scientific admission', input_lock_sha256=sha(HERE / 'INPUT_LOCK.json'), current_practice='X40 qualitative ranks and current fixed-spacer/perfect-bond/aggregate force defaults, without matched new measurements', strongest_equally_informed_control='Independent subset/Boolean-set enumeration over identical measured ports, costs and non-measurement blockers', tolerance=0, external_referent=dict(kind='external_review', locator=_release_expand('@DENTAL_INPUT_ROOT@/artifacts/LANE_XREVIEW_BATCH14/REVIEW_LANE_X55_METROLOGY.json; batch15 REVIEW_LANE_X59_REPLICA_MICROCT.json'), compared_quantity='Reviewed missing independent as-built reference and same-state paired-film validation obligations', refutes_us=False), cost=dict(preparation='Source inventory; physical manufacture separately priced as interval assumption', fit='No physical model fit', discovery='Curated constraints; researcher effort UNKNOWN', validation='Exact arithmetic controls, primary-table reconstruction, injection tests; physical validation NOT_RUN', queries='Measured software runtime/RSS', fallback='Explicit held-batch/model prerequisites; no silent transfer or hidden specimen reuse', monetary_cost='UNKNOWN', cost_intervals='PHENOMENOLOGICAL planning assumptions requiring quote/time log; not rigorous empirical bounds'), resolution_levels=dict(local_measurement='PER_POINT or PER_SURFACE_REGION as in each consumer', acquisition_count='POPULATION of curated decisions, not patients', cost='PHENOMENOLOGICAL'), affine_sensitivity='Not used; exact integer/finite-set calculation under declared dependencies; physical enclosure absent')
if round_ == 'R1':
    common.update(obstacle='An affected-decision count discards prerequisite identity and duplicate/shared consumers', changed_operation='Test whether equal touched count and equal interval cost uniquely determine evaluation-ready decisions', metrics=dict(summary_identity_error='exact Python integer tuple equality', downstream='number of evaluation-ready decisions'), decision_criterion='Reject count sufficiency if equal touched count/operator endpoints/instrument endpoints/new-specimen count has different ready count >=1. Search all admissible frozen portfolios.', falsifier='No exact-summary pair differs in ready count in entire finite domain; or primary-table/injection gate fails', primary_table_gate='Eight Cunali2017 mean/SD rows reconstructed from local primary text; all mean differences agree within0.011um, tolerance accounts only two-decimal print precision. Inject +10um in one imported mean through same gate.', scope='Scheduling representation counterexample is our own finite construction. Primary regional means independently support keeping measurement state; they do not validate a real schedule.')
elif round_ == 'R2':
    common.update(obstacle='R1 loses the AND dependencies; conditional measurements and actual decisions are conflated', changed_operation='Retain named required ports, other blockers, specimen regimes, destructive exclusivity, and interval cost; enumerate whole portfolios', metrics=dict(value='number of distinct local validation/observation queries evaluation-ready; actual decision count remains0 before measurements', robust_budget='sum high endpoints <=40 operator h and <=40 instrument-slot h', optimistic_budget='sum low endpoints <=40 in each resource', chains='all modeled dependencies closed; any non-measurement blocker prevents credit'), decision_criterion='Maximize evaluation-ready count. Within exact ties minimize new specimens, then high operator hours, then IDs. Report all maximum-count portfolios and all integer capacity regimes20..60h. No universal empirical order is claimed.', falsifier='Set control yields unequal readiness/count; injected missing prerequisite, budget, or mixed-specimen regime receives credit; physical status promoted without data', cost_box_enclosure='Exact minimum/maximum additive cost across declared interval Cartesian product; actual lab cost remainsUNKNOWN. Exhaustive finite optimization, not a linear sensitivity.', baseline='X40 rank1 first is tested on identical frozen ports; report concordance, no artificial method advantage.', sufficiency_test='Exact covered-count tuple vs chain-ready/dependency-aware outcomes from R1 retained.')
elif round_ == 'R3':
    common.update(obstacle='Selecting a set of assays still loses order, state and destructive ownership of specimen IDs', changed_operation='Executable specimen-state ledger and prospective measurement intake requiring independent raw evidence, operator/registration/calibration identifiers, and immutable predictions', metrics=dict(specimen_identity='each of72 planned IDs exactly once in final endpoint allocation', false_promotions='0 simulated/unmeasured/incomplete records become physical validation', mutations='every nominal accepting gate must reject a live changed record under identical function'), decision_criterion='Preserve72 fracture endpoint slots with non-destructive pilot first; explicitly reject X47 retention24 as simultaneous reuse. Same summary72 specimens/6design-angle cells must be exactly identical yet terminal fracture readiness differ24. Reject real measured values absent independently verified raw artifacts.', falsifier='A specimen is used destructively twice; wrong-state film is compared as same state; unknown origin passes mechanism; own fixture mislabeled measured passes evidence check; missing before-outcome freeze passes', scope='Ledger and port verification are executable. No instruments, actual specimens, measured costs, or prospective physical results exist here.')
elif round_ == 'R4':
    common.update(obstacle='The nominal optimum presumes ready matched specimens and instruments; a ranked list cannot identify whether these resources actually exist', changed_operation='Pull availability and protocol ownership into the acquisition predicate; compute a crown72-only plan and keep real readiness UNKNOWN', metrics=dict(value='Same R2 named evaluation-ready queries', cost='Same frozen operator and instrument intervals', physical_readiness='Only explicitly verified availability permits a candidate; unknown is excluded, not imputed available'), decision_criterion='Enumerate crown72-only, matched-extra-fixture-ready, scratch-manufacture and entirely unknown readiness profiles at40h. Retain unchanged original72 fracture allocation, so retention24 cannot count in that profile. Report all profile conditions and actual guaranteed decisions0.', falsifier='An unavailable/unknown instrument or specimen creates a physical-ready plan; X47 alternate ownership is treated as unchanged72 protocol; cost intervals claimed measured', baseline='X40 scanner/dry/film then fracture prefix and the same R2 complete enumeration; no new algorithm claim', scope='Readiness-sensitive scheduling capability; hypothetical profiles are explicitly not real inventory observations.')
elif round_ == 'R5':
    common.update(obstacle='A global available-port label loses whether measurements cover the same specimen and the whole required cohort. Pilot12 geometry/film cannot satisfy original72 setup.', changed_operation='Index each port by specimen identity, observation state and support; consumers require the intersection of covered specimen sets and complete original-protocol coverage', metrics=dict(summary_identity='Identical port names and observation counts, exactly', downstream='number of jointly observed pilot specimens', protocol='Full72 requires registered geometry/film/setup for all72, not only12'), decision_criterion='Construct same-count scan/film/force records with identical global port summary but downstream joint coverage12 versus0. Reject full72 protocol with only pilot12 geometry/film. No credit for unpriced extension from12 to72.', falsifier='No joint-coverage difference under exact summary; mismatched specimen sets or wrong-state rows pass consumer; full72 is considered ready from pilot12 observations', control='Direct specimen-set intersection with the same metadata and source X1B setup obligations', scope='Prospective information-carrier sufficiency under real protocol constraints. Own counterexample records are fixtures, never independent measurements.')
else:
    raise SystemExit('Unknown round')
write(path.name, common)
write(f'DECOMPOSITION_{round_}.json', dict(idea=common['ability'], mechanism=common['changed_operation'], equation='A_d(S)=1{R_d subset union ports(S)} *1{other blockers empty}; value=sum distinct A_d; cost=sum c_m; chain=AND all local and model obligations', operation='Finite sets, exact subset predicates, interval endpoint sums, specimen state transitions', representation='Named per-consumer ports with units, spatial support, time, provenance and owner; no scalar replacement', assumptions=['Frozen curated queries are the finite universe, not whole corpus', 'Measurement response must meet its existing consumer gate; evaluable is not necessarily decided', 'Actual access, physical calibration and labour require lab confirmation/data', 'Budget box is stated scheduling closure'], leaves=[dict(name='Boolean prerequisites and identity', status='DERIVED_UNDER_ASSUMPTIONS', stop='Exact finite contract; no deeper physics inferred'), dict(name='Reviewed missing physical quantities', status='EXTERNALLY_MEASURED', stop='External review supports existence/scope of gaps, not completed physical experiment'), dict(name='Published paired-region measurements', status='EXTERNALLY_MEASURED', stop='Cunali Table1 only; no raw pair covariance or local lab truth'), dict(name='Cost intervals and model transport', status='CONSTITUTIVE_CLOSURE', stop='Lab quote/timing and matched validation would replace estimates'), dict(name='Actual data, instruments and thresholds crossing', status='UNKNOWN', stop='No laboratory measurement occurs in this lane; cannot derive unknown empirical outcome')]))
write(f'PREREG_{round_}.sha256', dict(sha256=sha(path)))
print('Frozen', path.name, sha(path))
