from common import *

def run():
    DATA.mkdir(parents=True, exist_ok=True)
    cohort = read(V4 / 'payload/private/COHORT.json')
    selected = sorted([r for r in cohort if r['split'] == 'test'], key=lambda r: r['case_key'])[:8]
    selected += sorted([r for r in cohort if r['split'] == 'auxiliary'], key=lambda r: r['case_key'])[:4]
    referent = dict(kind='independent_measurement', locator=['doi:10.4047/jap.2021.13.5.269 Table1 nonfatigued G0.5/G0.8/G1.0/G1.5', 'doi:10.3390/ma17020365 Table2', str(V4 / 'FROZEN_PREDICTIONS.json')], compared_quantity='Published protocol-specific characteristic fracture force and Weibull modulus; withheld registered IOS geometry', refutes_us=True)
    p = dict(round='R1', claim_type='capability', capability='Determine whether published crown calibration supports an absolute lower fracture quantile for a new optimized crown, and whether scalar thickness/volume is sufficient', obstacle='No matched generated-crown fracture protocol; scalar thickness loses spatial elastic response', changed_operation='Protocol refusal plus 3D linear tetrahedral elasticity and an explicit volume-Weibull spatial functional', consumer='K39 crown optimization and prosthetics laboratory experiment', external_referent=referent, metrics={'protocol_fields': 'All 9 GenCAD v4 PROTOCOL_FIELDS must match two measured anchors; source-mismatched force is UNKNOWN', 'published_interpolation': 'Reuse v4 +/-0.20 log gate unchanged for every interior target', 'adjoint_relative_error': 0.0001, 'elastic_patch_max_error': 1e-09, 'sufficiency_identity_error': 0.0, 'sufficiency_downstream_relative_difference_min': 0.01}, decision='Absolute claim allowed only if complete protocol matches and all heldout force gates pass; conditional model remains distinct', strongest_equally_informed_control='Independent finite-difference gradient and sparse equilibrium residual; v4 direct log-anchor solver', falsifiers=['wrong force x1.6 fails frozen .20 log gate', 'wrong-tail quantile rejected', 'any protocol mismatch blocks absolute force', 'linear gradient has no whole-design-box enclosure and cannot certify robustness'], cost=dict(preparation='Hash selected local inputs, no source trees copied', fit='Two source endpoints only; no generated-crown fit', discovery='Implementation wall time recorded, tokens UNKNOWN', validation='Primary rows, patch identity, adjoint FD', queries='all numerical queries counted by FEM', fallback='UNKNOWN for unmatched protocol; errors retained', resource='4 threads max, no GPU, 3GB intermediates'), assumptions=['Small strain isotropic elasticity E=201400MPa nu=.30 from inherited X1 3Y material card, not a new measurement', 'Rigid basal support, fixed geometry-derived load port; not X1 compliant die or real antagonist contact', 'Independent volume flaws with m=2.89 borrowed from Prott G0.8 force distribution; geometry transfer is unvalidated'], resolution='PER_POINT mechanics; PER_TOOTH model quantile; POPULATION measured Weibull parameter', retrospective=True)
    freeze(ROOT / 'PREREG_R1.json', p)
    dump(ROOT / 'PANEL_SELECTION.json', dict(selected=selected, source_records=len(cohort), selected_records=len(selected), selection_exclusions=len(cohort) - len(selected), selection_is_not_observation_dropout=True, families=['molar_crown', 'premolar_crown', 'anterior_crown', 'bridge3'], levels=['easy', 'normal', 'hard', 'boundary']))
    files = [V4 / 'FROZEN_PREDICTIONS.json', V4 / 'payload/literature/CROWN_CURATED.json', V4 / 'code/quality.py', V4 / 'code/literature.py', V4 / 'payload/participant_code/legacy/checks.py', V4 / 'payload/participant_code/legacy/geometry.py', X1 / 'raw/MATCHED_R2.json', X1 / 'FROZEN_PREDICTIONS.json', X1 / 'inputs/geometry/D1_model.npz', X1 / 'inputs/geometry/D1_grid.json', X1 / 'inputs/fe/L005_lo_M1_k6_thin_3Y.npz', X23 / 'vendor/crown_design_weibull.py']
    for r in selected:
        path = V4 / 'payload/public/tasks' / f"{r['case_key']}.json"
        files.append(path)
        for t in read(path):
            if t['family'] in ['molar_crown', 'premolar_crown', 'anterior_crown', 'bridge3'] and t['status'] == 'READY':
                files.append(V4 / 'payload/public' / t['geometry_file'])
        files.append(V4 / 'payload/private/references' / f"{r['case_key']}.npz")
        for name in ['population', 'parametric', 'X1B_morphology', 'X18_antagonist', 'constraint_optimizer', 'field_generator', 'x42_shape', 'x42_contact_branch']:
            files.append(V4 / 'payload/predictions' / name / f"{r['case_key']}.npz")
    freeze(ROOT / 'INPUT_LOCK.json', dict(files={str(f): dict(sha256=sha(f), bytes=f.stat().st_size) for f in sorted(set(files))}))
    dump(ROOT / 'DECOMPOSITION.json', dict(goal='Manufacturable locally optimized crown with calibrated low fracture quantile and measured validation', chain=['spatial coordinates -> tetra Jacobian -> strain B -> equilibrium K u=f -> positive principal stress -> volume hazard -> conditional force quantile -> geometry gates -> lab measurements'], leaves=[dict(name=n, status=s, stop_argument=a) for (n, s, a) in [('tetra gradient and adjoint', 'DERIVED_UNDER_ASSUMPTIONS', 'P inverse, K=sum V B^T C B; differentiate exactly for fixed topology and load'), ('elasticity and support', 'CONSTITUTIVE_CLOSURE', 'Inherited isotropic 3Y card and rigid basal constraint; no new material measurement'), ('Weibull force parameters', 'EXTERNALLY_MEASURED', 'Prott Table1 reports force-law fit and 90CI, not spatial flaw population'), ('force-law to volume flaws', 'UNKNOWN', 'Requires matched batch, flaw origin, support and contact plus thickness/shape measurements'), ('physical film and milling', 'UNKNOWN', 'v4 checks certify only affine roof ideal-tool regime; full axial/sinter/seating process absent'), ('whole-design sensitivity enclosure', 'UNKNOWN', 'Exact derivative at evaluated coordinates, no interval arithmetic enclosure'), ('benchmark geometry', 'EXTERNALLY_MEASURED', 'Registered IOS reference; scanning/registration uncertainty uncalibrated'), ('summary sufficiency', 'DERIVED_UNDER_ASSUMPTIONS', 'Two permuted spatial thickness fields have exactly the same multiset and volume; elastic hazard may differ')]], ports=[dict(source='coordinates and fixed load', consumer='equilibrium/hazard', resolution='PER_POINT', time_scale='SIMULTANEOUS'), dict(source='frozen digital design', consumer='manufacture/metrology/fracture', resolution='PER_POINT', time_scale='HANDOVER')]))
    (ROOT / 'GOAL_TO_STRESS_POINT.md').write_text('Desired capability: a whole crown whose local geometry is optimized against an externally calibrated lower fracture-load quantile and simultaneously passes insertion, wall, cement, CAM and antagonist checks.\nConflict: changing local geometry changes elastic stress/contact while source force tables concern other specimens and supports. GenCAD roof proof excludes axial walls and shaft access.\nR1 opens spatial sufficiency and refuses unsupported absolute transfer. R2 uses an actual elastic adjoint and unchanged geometry checks. R3 moves to the whole STS crown and a batch-cancelling paired measurement, retaining the unresolved manufacturing/physical gates.\n')
    state('R1_PREREGISTERED', 'Input hashes and criteria frozen before numerical work', 'Implement and run calibration refusal, elastic patch, spatial sufficiency and adjoint check')
if __name__ == '__main__':
    run()
