"""Append the two late harvests after manual primary-source reading.

This is a one-time curation operation. run_all.sh uses the frozen output only.
Source-number occurrence is not semantic verification; the contracts await review.
"""
from dental_release.paths import expand as _release_expand
import datetime, hashlib, json, shutil
from pathlib import Path
R = Path(__file__).resolve().parent

def read(n):
    return json.loads((R / n).read_text())

def write(n, x):
    (R / n).write_text(json.dumps(x, ensure_ascii=False, indent=2) + '\n')

def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()
assert not (R / 'raw/R4_CURATION_RECEIPT.json').exists(), 'Already curated; use offline replay.'
for n in ['VERIFIED_OBSERVATIONS.json', 'SOURCE_AUDIT.json', 'SOURCE_ADMISSION.json', 'CONSUMER_IMPACTS.json', 'results.json', 'raw/RELEASE_COST.json']:
    dst = R / 'raw' / ('R4_PREVIOUS_' + Path(n).name)
    if not dst.exists():
        shutil.copyfile(R / n, dst)
OBS = read('VERIFIED_OBSERVATIONS.json')
AD = [x for x in read('SOURCE_ADMISSION.json') if x['job'] not in {'GUIDE-ACCURACY', 'MILLING-DEFLECTION'}]
META = {}
for p in sorted((R / 'sources').glob('metadata_*.json')):
    for x in json.loads(p.read_text())['resultList']['result']:
        META[x['id']] = dict(x, metadata_file=str(p.relative_to(R)))
GUIDE = 'GUIDE-ACCURACY'
MILL = 'MILLING-DEFLECTION'
GC = [_release_expand('X87'), _release_expand('X96')]
MC = [_release_expand('X89')]

def audit(job, label, mid, status, reason, ids=(), doi=None, title=None):
    m = META.get(str(mid), {})
    a = dict(job=job, label=label, verified_pmid=str(mid) if mid and str(mid).isdigit() else None, verified_doi=doi or m.get('doi'), title=title or m.get('title'), identity_status=status, decision_reason=reason, verified_observation_ids=list(ids), numeric_bundle_exported=bool(ids), new_matched_physical_calibration=False)
    if not ids:
        a['non_admission_reason'] = reason
    AD.append(a)

def obs(id, job, mid, quantity, values, unit, loc, pop, proto, reason, region='PER_TOOTH', level='primary_measurement', conflicts=(), support=None, doi=None, url=None, units=None, stat='POPULATION', verification=None, transfer='CONTEXT_ONLY', title=None):
    m = META.get(str(mid), {})
    pmc = m.get('pmcid')
    d = doi or m.get('doi')
    file = support or ('sources/' + pmc + '.xml' if pmc and (R / 'sources' / (pmc + '.xml')).exists() else m['metadata_file'])
    url = url or ('https://doi.org/' + d if d else 'https://pubmed.ncbi.nlm.nih.gov/' + str(mid) + '/')
    source = dict(pmid=str(mid) if mid and str(mid).isdigit() else None, doi=d, pmcid=pmc, title=title or m.get('title'), url=url)
    meta = {k: dict(unit=(units or {}).get(k, 'degree' if 'angle' in k else unit), observation_resolution=region, statistic_resolution=stat, time_scale='SIMULTANEOUS', available_raw_individual_observations=False) for k in values}
    OBS.append(dict(id=id, job=job, claim_type='information_link', source=source, quantity=quantity, values=values, unit=unit, table_locator=loc, population=pop, protocol=proto, source_file=file, source_sha256=sha(R / file), evidence_level=level, verification=verification or ('independently_read_fulltext' if file.endswith('.xml') else 'independently_read_indexed_abstract'), observation_resolution=region, statistic_resolution=stat, edge_resolution=region, time_scale='SIMULTANEOUS', consumers=GC if job == GUIDE else MC, transfer_status=transfer, transfer_reason=reason, conflicts=list(conflicts), review_state='PENDING_INDEPENDENT_REVIEW', value_metadata=meta, external_referent=dict(kind='independent_measurement' if level == 'primary_measurement' else 'published_dataset', locator=url + ' ; ' + loc, compared_quantity=quantity, refutes_us=bool(conflicts) or transfer == 'REJECT_TRANSFER')))
write('sources/Eldabe2026_primary_browser_notes.json', {'source_url': 'https://link.springer.com/article/10.1186/s12903-026-08969-1', 'access': 'Primary full article read via web tool. urllib HTML/PDF yielded a proof-of-work challenge, not article bytes.', 'locator': 'Statistical analysis; Results, Tables 2-5', 'statistical_unit': 'Patient-level averages; 31 patients, 86 implants', 'groups_patient_implant_counts': {'bilateral': [10, 24], 'unilateral': [14, 23], 'mucosa': [4, 20], 'stackable': [3, 19]}, 'fields_mean_SD_order_entry_apex_vertical_angle': {'bilateral': [1.32, 0.54, 1.22, 0.3, 0.04, 0.03, 4.35, 1.47], 'unilateral': [1.42, 0.71, 1.59, 0.58, 0.09, 0.05, 4.89, 2.42], 'mucosa': [1.99, 0.62, 1.89, 0.56, 0.2, 0.13, 5.96, 1.61], 'stackable': [1.7, 0.28, 1.72, 0.34, 0.26, 0.06, 5.42, 1.16]}, 'warning': 'Hash binds our transcription. Offline replay cannot authenticate inaccessible publisher bytes.'})
write('sources/Azcarate2015_primary_index_notes.json', {'source_url': 'https://www.sciencedirect.com/science/article/pii/S2386401X15000225', 'doi': '10.1016/j.maxile.2015.07.001', 'access': 'Indexed primary abstract read; direct publisher access 403. No Table fulltext admitted.', 'cadaver_mandibles': 11, 'hemimandibles': 22, 'levels_from_mental_foramen_mm': [5, 15, 25], 'canal_wall_average_discrepancy_mm': 1.15, 'nerve_average_discrepancy_mm': 0.3, 'warning': 'Hash binds our transcription, not original article. Numbers retain weaker indexed-only support.'})
obs('G03_Tahmaseb', GUIDE, 30328191, 'Pooled implant placement means and mean confidence intervals', {'entry_mean_ci': ['1.2', '1.04', '1.44'], 'apex_mean_ci': ['1.4', '1.28', '1.58'], 'angle_mean_ci': ['3.5', '3.0', '3.96']}, 'mm', 'Primary abstract Results', '20 studies;2238 implants;471 patients', 'Static guided surgery random-effects meta-analysis', 'Pooled CI is not individual SD or a 95th individual deviation.', level='published_review_aggregate')
audit(GUIDE, 'A1', 30328191, 'CHECKED_ABSTRACT', 'Angular CI is available; no SD or joint local pose.', ['G03_Tahmaseb'])
obs('G04_Wei', GUIDE, 33540465, 'Pooled dynamic navigation means and mean CIs', {'entry_mean_ci': ['1.02', '.83', '1.21'], 'apex_mean_ci': ['1.33', '.98', '1.67'], 'angle_mean_ci': ['3.59', '2.09', '5.09']}, 'mm', 'Abstract Results', '10 studies;1298 implant placements/drillings;5 clinical/5 model studies', 'Mixed clinical/model dynamic navigation', 'Not an implant-level SD or local signed wall-loss distribution.', level='published_review_aggregate')
audit(GUIDE, 'A2', 33540465, 'CHECKED_ABSTRACT', 'Values and mixed population checked.', ['G04_Wei'])
obs('G05_2024meta', GUIDE, 38509530, 'Pooled group global deviations with mean CIs', {'overall_entry': ['1.11', '1.02', '1.19'], 'overall_apex': ['1.40', '1.31', '1.49'], 'overall_angle': ['3.51', '3.27', '3.75'], 'static_entry': ['1.11', '1.00', '1.20'], 'dynamic_entry': ['1.18', '1.02', '1.34'], 'robot_entry': ['.81', '.37', '1.25'], 'static_apex': ['1.44', '1.34', '1.54'], 'dynamic_apex': ['1.36', '1.18', '1.54'], 'robot_apex': ['.77', '.43', '1.11'], 'static_angle': ['3.58', '3.33', '3.83'], 'dynamic_angle': ['3.51', '2.90', '4.12'], 'robot_angle': ['1.71', '.04', '3.38']}, 'mm', 'Results, global coronal/apical/angular deviations', '67 studies;5673 implants;overlapping method study counts', 'Meta-analysis; static/dynamic/robot comparisons', 'Missing entry columns are recoverable; pooled mean CI does not identify local risk.', level='published_review_aggregate')
audit(GUIDE, 'A3', 38509530, 'CHECKED_WITH_FILLED_GAPS', 'Entry values read from primary Results, not inferred.', ['G05_2024meta'])
audit(GUIDE, 'A3bis', 38509530, 'NO_INDEPENDENT_NUMERIC_FACIT', 'Pilot-guided discussion is secondary qualitative text; duplicate source, no new measurement.')
obs('G06_Vinnakota', GUIDE, 37690856, 'Dynamic-minus-static in-vitro angular mean difference', {'angle_difference_ci': ['-.51', '-.90', '-.13']}, 'degree', 'Abstract Results in-vitro comparison', '14 studies,9 in-vitro;static1633/dynamic902 implants overall', 'Subgroup mean difference, not absolute deviation', 'Do not substitute a signed group contrast for a positive individual pose error.', level='published_review_aggregate')
audit(GUIDE, 'A4', 37690856, 'CHECKED_ABSTRACT', '-0.51 degrees is only in-vitro subgroup difference.', ['G06_Vinnakota'])
v = {}
for (group, data) in {'free': [['1.36', '.62'], ['1.73', '.66'], ['5.82', '2.79'], ['.74', '.49'], ['.76', '.49']], 'static': [['.92', '.36'], ['1.06', '.47'], ['2.52', '1.18'], ['.61', '.47'], ['.61', '.47']], 'dynamic': [['.99', '.52'], ['1.14', '.56'], ['3.66', '1.64'], ['.55', '.54'], ['.56', '.54']]}.items():
    for (k, z) in zip(['entry', 'apex', 'angle', 'entry_depth', 'apex_depth'], data):
        v[group + '_' + k] = z
obs('G07_2024clinical', GUIDE, 38745297, 'Group mean/SD of global implant placement and unsigned depth deviations', v, 'mm', 'Table 1 arm counts;Table 2 global/depth deviations', '65 patients;free23/30implants,static23/30,dynamic19/34', 'Retrospective clinical groups, mixed arch; planned/achieved registration', 'Separate source scenario permitted; groups are not mandible-only or signed cutting-depth losses.')
audit(GUIDE, 'A5', 38745297, 'CHECKED', 'Actual group counts and Table2 mean/SD verified.', ['G07_2024clinical'])
audit(GUIDE, 'A6', 41068430, 'REJECTED_ATTRIBUTION', 'Review includes13 studies, not25. .73/1.00/1.42 apical values are Sun2020 study rows, not pooled estimates. Varga rows attributed to Block; Younes rows attributed to Smitkarn. No secondary study row admitted as primary measurement.')
obs('G08_Nava_network', GUIDE, 41714848, 'Network-ranked mean global deviations and standard errors', {'robot_angle_mean_SE': ['.48', '.34'], 'dynamic_angle_mean_SE': ['1.53', '.22'], 'half_angle_mean_SE': ['2.02', '.42'], 'full_angle_mean_SE': ['2.32', '.24'], 'free_angle_mean_SE': ['4.15', '.31'], 'dynamic_entry_mean_SE': ['.55', '.06'], 'robot_entry_mean_SE': ['.57', '.09'], 'full_entry_mean_SE': ['.72', '.06'], 'half_entry_mean_SE': ['.95', '.09'], 'free_entry_mean_SE': ['1.26', '.06'], 'robot_apex_mean_SE': ['.45', '.20'], 'dynamic_apex_mean_SE': ['.56', '.127'], 'half_apex_mean_SE': ['.65', '.25'], 'full_apex_mean_SE': ['1.06', '.22'], 'free_apex_mean_SE': ['1.87', '.187']}, 'mm', 'Table 6 rankings;Table 5 contrasts', 'Network of clinical trials; dependent pooled groups', 'Network estimated means with SE, not observed implant SD', 'SE must not enter Cantelli as individual SD; half-guided is not pilot-guided.', level='published_review_aggregate')
audit(GUIDE, 'A7', 41714848, 'CHECKED_WITH_STATISTIC_RESTRICTION', 'Ranking means/SE verified; Table5 coefficients are contrasts.', ['G08_Nava_network'])
obs('G09_Varga_allarch', GUIDE, 31958166, 'All-arch implant deviation mean/SD', {'free_entry': ['1.82', '.94'], 'free_apex': ['2.43', '.98'], 'free_angle': ['7.03', '3.44'], 'pilot_entry': ['1.57', '.91'], 'pilot_apex': ['1.86', '1.09'], 'pilot_angle': ['5.71', '3.68'], 'partial_entry': ['1.37', '.79'], 'partial_apex': ['1.59', '.86'], 'partial_angle': ['4.30', '3.33'], 'full_entry': ['1.40', '.54'], 'full_apex': ['1.59', '.59'], 'full_angle': ['3.04', '1.51']}, 'mm', 'Accepted manuscript Table 3 all groups;published Table 3', 'Free55,pilot49,partial51,full52 implants;all arches', 'Clinical RCT planned/achieved implant registration', 'Do not replace recipient mandibular moments with all-arch moments.', support='sources/Varga2020.txt')
audit(GUIDE, 'A8', 31958166, 'CHECKED_WITH_FILLED_PILOT_GAP', 'Pilot values available; mandible and all-arch groups differ.', ['G01_Varga', 'G09_Varga_allarch'])
obs('G10_Gargallo', GUIDE, 33270056, 'Fully guided minus comparator weighted mean deviation differences', {'full_minus_half_entry': '-.51', 'full_minus_half_apex': '-.75', 'full_minus_half_angle': '-3.63', 'full_minus_free_entry': '-1.18', 'full_minus_free_vertical': '-.17', 'full_minus_half_vertical': '-.23'}, 'mm', 'Abstract Results', '10 randomized trials', 'Meta-analytic weighted group differences', 'A signed group contrast is not signed local drilling overshoot.', level='published_review_aggregate')
audit(GUIDE, 'A9', 33270056, 'CHECKED_ABSTRACT', 'WMD signs and units verified; no individual-error distribution.', ['G10_Gargallo'])
audit(GUIDE, 'A10', 40756940, 'PRIMARY_BODY_UNAVAILABLE', 'Article exists; PMC12316628 XML HTTP500. Abstract lacks quoted outcome numbers; no numeric admission.')
obs('G11_umbrella', GUIDE, 41206337, 'Umbrella standardized effect and survival risk ratios', {'SMD_ci': ['-.97', '-2.27', '-.32'], 'survival_RR_ci': ['1.02', '.98', '1.06'], 'success_RR_ci': ['.88', '.74', '1.04']}, 'dimensionless', 'Abstract Results', '13 systematic reviews', 'Umbrella synthesis, heterogeneous primary cohorts', 'SMD has no millimetre conversion without source-specific scale.', level='published_review_aggregate')
audit(GUIDE, 'A11', 41206337, 'CHECKED_ABSTRACT', 'PII resolves DOI; dimensionless SMD/RR, not mm.', ['G11_umbrella'])
obs('G12_positional', GUIDE, 38036932, 'Implant positional guide versus freehand global mean/SD', {'guide_entry': ['.48', '.26'], 'free_entry': ['1.07', '.44'], 'guide_apex': ['.97', '.39'], 'free_apex': ['1.44', '.63'], 'guide_angle': ['2.36', '1.70'], 'free_angle': ['4.31', '3.37'], 'guide_vertical': ['.60', '.52'], 'free_vertical': ['1.18', '.77']}, 'mm', 'Table3;Methods participant counts', '48 healthy single-tooth-gap patients,24 implants/patients per arm;12 anterior/12 posterior each', 'Patient-chosen positional-first-drill guide versus freehand, single surgeon', 'Unsigned global implant placement, not full-guided protocol or local canal-wall loss.')
audit(GUIDE, 'A12', 38036932, 'CHECKED_WITH_DENOMINATOR_CLARIFIED', 'Abstract wording ambiguous; Methods confirms total48, not48 each arm.', ['G12_positional'])
obs('G13_Werny', GUIDE, 40314873, 'Pooled protocol deviation means', {'free_entry': '1.56', 'free_apex': '2.22', 'free_angle': '7.46', 'pilot_entry': '1.13', 'pilot_apex': '1.43', 'pilot_angle': '5.94', 'full_entry': '.72', 'full_apex': '.88', 'full_angle': '2.57', 'dynamic_entry': '1.01', 'dynamic_apex': '1.36', 'dynamic_angle': '3.67'}, 'mm', 'Abstract Results pooled protocol profiles', '55 studies', 'Systematic-review pooled protocol means', 'Pilot profiles available; no individual SD for risk margin.', level='published_review_aggregate')
audit(GUIDE, 'A13', 40314873, 'CHECKED_WITH_FILLED_PILOT_GAP', 'Primary abstract supplies four protocol profiles.', ['G13_Werny'])
audit(GUIDE, 'A14', 42824664, 'NO_QUOTED_NUMERIC_OUTCOME', 'Publication verified; abstract qualitative; no quoted outcome to admit.')
obs('G14_support', GUIDE, 41464555, 'Support-group entry/apex mean/SD and arch means with CIs', {'mandible_bone_entry': ['.371', '.090'], 'mandible_bone_apex': ['.408', '.128'], 'mandible_soft_entry': ['1.395', '.364'], 'mandible_soft_apex': ['1.945', '.487'], 'maxilla_soft_entry': ['.596', '.188'], 'maxilla_soft_apex': ['.795', '.309'], 'maxilla_bone_entry': ['.445', '.083'], 'maxilla_bone_apex': ['.531', '.113'], 'maxilla_entry_mean_CI_SD': ['.443', '.399', '.487', '.214'], 'mandible_entry_mean_CI_SD': ['.755', '.598', '.912', '.554'], 'maxilla_apex_mean_CI_SD': ['.562', '.499', '.625', '.308'], 'mandible_apex_mean_CI_SD': ['.981', '.751', '1.211', '.814']}, 'mm', 'Tables6-8 preferred over conflicting narrative', '140 implants;maxilla92/mandible48;mandible bone14/soft18;maxilla bone6/soft40', 'Static surgery stratified by support and arch', 'Support type does not identify pilot/partial/full degree of guidance.', conflicts=['Narrative CIs differ from Tables7/8:mandible entry .592-.918 vs table .598-.912;maxilla apex .501-.623 vs .499-.625;mandible apex .758-1.204 vs .751-1.211. Both retained; no CI->SD conversion.'])
audit(GUIDE, 'A15', 41464555, 'CHECKED_WITH_SOURCE_CONFLICT', 'Table CIs differ from harvested narrative. Support type is not guidance degree.', ['G14_support'])
v = {}
for (g, ds) in read('sources/Eldabe2026_primary_browser_notes.json')['fields_mean_SD_order_entry_apex_vertical_angle'].items():
    for (i, k) in enumerate(['entry', 'apex', 'vertical', 'angle']):
        v[g + '_' + k] = [str(x) for x in ds[2 * i:2 * i + 2]]
obs('G15_Eldabe_patient', GUIDE, 42343372, 'Patient-average global pose deviations, means/SD', v, 'mm', 'Statistical analysis, Results Tables2-5', '31 patients/86 implants;patient averages used for analysis', 'Fully guided bilateral/unilateral/mucosal/stackable support;postoperative scanbody STL registration', 'Patient-average SD is not implant-level SD. Vertical distance unsigned.', support='sources/Eldabe2026_primary_browser_notes.json', doi='10.1186/s12903-026-08969-1', verification='primary_full_article_read_browser_transcription_only', region='PER_ARCH', conflicts=['Sample-size paragraph calls implant unit; statistical-analysis paragraph averages implants at patient level. Preserve statistical unit.'])
audit(GUIDE, 'A16', 42343372, 'CHECKED_BROWSER_PRIMARY', 'Primary body read through web; saved urllib challenge is not fulltext. Patient-average SD cannot enter implant-pose model.', ['G15_Eldabe_patient'], doi='10.1186/s12903-026-08969-1')
obs('G16_models', GUIDE, 42005219, 'Static/dynamic model deviation moments and method agreement ICC', {'static_entry': ['.52', '.17'], 'dynamic_entry': ['1.24', '.22'], 'static_apex': ['1.15', '.48'], 'dynamic_apex': ['1.43', '.24'], 'overall_ICC_ci': ['.997', '.995', '.998'], '2D_ICC_ci': ['.949', '.899', '.975'], '3D_ICC_ci': ['.886', '.654', '.966'], 'volume_ICC_ci': ['.912', '.505', '.987']}, 'mm', 'Table1 mean/SD;ICC results', '20 laboratory models,10/group', 'Static/dynamic placement;alternative registration/measurement methods', 'Model placement ICC is not canal annotation error.', units={k: 'dimensionless' for k in ['overall_ICC_ci', '2D_ICC_ci', '3D_ICC_ci', 'volume_ICC_ci']}, conflicts=['The swarm dates article2017; metadata2026. Table1 shared CI seems contrast CI; no arm-specific CI admitted.'])
audit(GUIDE, 'A17', 42005219, 'CORRECTED_DATE_AND_CI_SCOPE', '2026 publication. Mean/SD/ICC verified; duplicated table CI not admitted as arm CI.', ['G16_models'])
obs('G17_GuideMia', GUIDE, 41657546, 'Clinical guide-software and free-end subgroup placement mean/SD', {'GuideMia8_entry': ['1.16', '.34'], 'GuideMia8_apex': ['1.79', '.66'], 'GuideMia8_angle': ['3.60', '1.92'], '3shape8_entry': ['.88', '.46'], '3shape8_apex': ['1.27', '.51'], '3shape8_angle': ['3.96', '2.20'], 'GuideMia12_angle': ['5.23', '2.77'], '3shape12_angle': ['3.13', '2.16'], 'free_end_entry': ['1.31', '.64'], 'no_free_end_entry': ['.91', '.44'], 'free_end_apex': ['1.51', '.72'], 'no_free_end_apex': ['1.09', '.48'], 'free_end_angle': ['5.37', '3.08'], 'no_free_end_angle': ['3.51', '1.90']}, 'mm', 'Tables3/4 length and free-end subgroups', '75 implants;59 mandible/16 maxilla;free-end22/non-free53;8mm groups7/9;12mm groups5/5', 'Clinical static guide groups,GuideMia versus3Shape', 'Subgroup associations, not signed local wall loss.', conflicts=['Correct PMCID12872909, not12872907. Table3 GuideMia12 angle5.23, not Bunny5.25.'])
audit(GUIDE, 'A18', 41657546, 'CORRECTED_VALUE_AND_PMCID', '5.23 degree mean and correct PMC12872909 verified.', ['G17_GuideMia'])
audit(GUIDE, 'A19', 29707180, 'SECONDARY_CONTEXT_ONLY', 'Review ranges .67-2.19 apex,.60-1.68 entry,2.60-4.67deg span different studies; not one joint profile or independent primary measurement. Underlying studies not read.')
obs('G18_novice', GUIDE, 25318961, 'Supervised inexperienced operator global placement means/SD', {'entry': ['.9', '.5'], 'apex': ['1.1', '.5'], 'coronal_depth': ['.5', '.5'], 'apical_depth': ['1.1', '.5'], 'angle': ['2.8', '1.5']}, 'mm', 'Abstract Results', '75 implants;17 edentulous jaws;16 patients', 'Inexperienced but supervised surgeons;computer-guided placement', 'Not pilot-specific or signed bore-depth error.')
audit(GUIDE, 'A20', 25318961, 'CHECKED_ABSTRACT', 'Counts/global deviations verified; operator regime retained.', ['G18_novice'])
obs('G19_canal_centerline', GUIDE, 36329051, 'Interobserver/DL canal centreline distance summaries', {'expert_highest_median_IQR': ['.77', '.25'], 'expert_highest_mean_SD': ['.84', '.28'], 'DLS_highest_median_IQR': ['.74', '.28'], 'DLS_highest_mean_SD': ['.81', '.41'], 'older_DLS_reevaluated_median_IQR': ['.78', '.33'], 'older_DLS_reevaluated_mean_SD': ['.91', '.63']}, 'mm', 'Results Interobserver variability,Fig4;DLS comparison on current test set', '150 CBCT scans;300 canals;4 experts;2022 test cohort', 'Symmetric mean centreline distance;current/new and older algorithm evaluated on current cohort', 'Centreline mean is not canal-wall contour error or local signed gap loss.', region='PER_POINT')
audit(GUIDE, 'B1', 36329051, 'CHECKED', 'SMCD statistics verified; retain centreline observable.', ['G19_canal_centerline'])
audit(GUIDE, 'B2', 32245989, 'CORRECTED_SOURCE_OF_NUMBERS', '.78/.33 and .91/.63 are2022 reevaluation of old model in B1, not original2020 cohort primary results. Export only current-study comparison in G19.', ['G19_canal_centerline'])
obs('G20_cadaver_index', GUIDE, None, 'Average CBCT canal-wall/nerve localization discrepancy', {'wall_average_discrepancy': '1.15', 'nerve_average_discrepancy': '.3'}, 'mm', 'Indexed primary abstract;Table body inaccessible', '11 cadaver mandibles;22 hemimandibles;sections5/15/25mm from mental foramen', 'CBCT versus cadaver dissection;average discrepancy', 'Average absolute discrepancy is not local signed-error quantile; weaker indexed-only access.', region='PER_SURFACE_REGION', support='sources/Azcarate2015_primary_index_notes.json', doi='10.1016/j.maxile.2015.07.001', verification='indexed_primary_abstract_direct_access_blocked', title='Reliability of cone beam computed tomography in locating the mandibular canal')
audit(GUIDE, 'B3', None, 'CHECKED_INDEXED_PRIMARY_ABSTRACT', '1.15/.3 indexed primary abstract verified;Table4 .73±.95 and3.91±1.62 not admitted without body.', ['G20_cadaver_index'], doi='10.1016/j.maxile.2015.07.001')
audit(GUIDE, 'B4 Qassim anonymous', None, 'REJECTED_UNRESOLVED_IDENTITY', 'No authors/DOI/primary locator; kappa.80 cannot be verified.')
audit(GUIDE, 'C1', 20122425, 'CHECKED_IDENTITY_CONTEXT_ONLY', 'Correct full title/DOI;10 dry mandibles,6 caliper measures,voxel.40/.25mm,ICC>.99. No local canal-wall error statistic; quoted generalized precision not transportable.')
obs('G21_CBCT_repeatability', GUIDE, 36135164, 'Observer-specific repeatability coefficients and method biases', {'observer1_axial_RC': '.14', 'observer1_sagittal_RC': '.18', 'observer2_axial_RC': '.20', 'observer2_sagittal_RC': '.13', 'cast_observer2_RC': '.20', 'cast_observer3_RC': '.21', 'axial_bias_CI': ['.176', '.136', '.217'], 'sagittal_bias_CI': ['.186', '.145', '.226']}, 'mm', 'Results repeatability;Table2 biases', '30 enrolled,27 analyzed patients with adjacent posterior implant plans', 'Linear inter-tooth distance on CBCT versus plaster,not canal contour', 'Neither RC nor study.4mm decision threshold supplies local canal-wall support.', conflicts=['Narrative repeatability<=.20 conflicts with printed castRC.21.'])
audit(GUIDE, 'C2', 36135164, 'CHECKED_WITH_CONFLICT', 'RC and bias source read;cast.21 conflicts with summary≤.20.', ['G21_CBCT_repeatability'])
obs('G22_ceph_ICC', GUIDE, 34943528, 'B-to-A-point arch parameter interobserver ICC and 95% CIs', {'3D_ICC_CI': ['.653', '.136', '.866'], '2D_magnified_ICC_CI': ['.960', '.887', '.985'], '2D_unmagnified_ICC_CI': ['.957', '.839', '.985']}, 'dimensionless', 'Table2 Bpoint-Apoint Arch row', '20 full-cranium CBCT datasets;2 examiners;63 parameters(28linear,35angular)', 'Cephalometric tracing;children/adults;3D versus extracted2D', 'ICC lacks mm scale and measures cephalometric tracing, not canal wall.', conflicts=['The swarm reads CI lower.136 as ICC. Correct ICC.653.'])
audit(GUIDE, 'C3', 34943528, 'CORRECTED_STATISTIC_COLUMN', 'ICC=.653,CI=.136-.866; .136 is not estimate.', ['G22_ceph_ICC'])
obs('G23_dryskull', GUIDE, 25029593, 'Synthetic lateral cephalometry difference bias and limits of agreement', {'bias_LOA': ['.47', '-.31', '1.25'], 'conventional_bias_LOA': ['.17', '-.75', '1.10'], 'orthogonal_bias_LOA': ['-.16', '-1.14', '.83']}, 'mm', 'Results/Fig6 and synthetic comparison', '12 dry skulls,metal markers;single examiner,repeat3weeks', 'Projected linear skull distances versus physical calipers', 'Not interannotator canal-boundary variability.', region='PER_POINT')
audit(GUIDE, 'C4', 25029593, 'CHECKED', 'Signed biases/LOA verified; preserve dry-skull/projected measurement scope.', ['G23_dryskull'])
gurl = 'https://www.dentsplysirona.com/content/dam/master/education/documents/upload/S/Study%201%20Accuracy%2C%20reproducibility%2C%20and%20efficiency.pdf'
values = {}
units = {}
for (table, groups) in {'repeatability': {'plaster': ['.048', '-.304', '.400', '.704', '.035'], 'emodel': ['-.028', '-.410', '.355', '.765', '.039'], 'SureSmile': ['-.011', '-.231', '.209', '.440', '.013'], 'Anato': ['.006', '-.487', '.500', '.987', '.063']}, 'accuracy': {'emodel': ['.285', '-.176', '.746', '.922', '.134'], 'SureSmile': ['-.130', '-.604', '.344', '.947', '.073'], 'Anato': ['.191', '-.57', '.952', '1.521', '.181']}}.items():
    for (group, vs) in groups.items():
        values[table + '_' + group + '_bias_LOA_width'] = vs[:4]
        values[table + '_' + group + '_MSE'] = vs[4]
        units[table + '_' + group + '_MSE'] = 'mm^2'
obs('G24_Grunheid', GUIDE, 24485729, 'Tooth-width within-operator repeatability versus accuracy against plaster', values, 'mm', 'Printedp160/PDFp4 TablesII(repeatability) andIII(accuracy),visually read', '30 patients;3 operators;digital models and plaster', 'Mesiodistal tooth width,not canal localization', 'Mean bias≈.05mm is not an agreement bound or local wall uncertainty.', region='PER_TOOTH', support='sources/Grunheid2014.pdf', url=gurl, units=units, verification='primary_pdf_tables_visually_read_plus_original_pdf_hash', conflicts=['The swarm labels TableIII values as TableII;several minus signs lost. MSE is squared-length,not mm.'])
audit(GUIDE, 'C5', 24485729, 'CORRECTED_TABLE_SIGNS_UNITS', 'TableII/III visually read. Negative biases/LOA restored;MSEmm².', ['G24_Grunheid'])
audit(GUIDE, 'SUPPLEMENT Wu', 33230662, 'CHECKED', 'Previously used primary profile confirmed;not an extra The swarm A-item.', ['G02_Wu'])
obs('M02_equivalent_diameter', MILL, 'PMC6190321', 'Assumed equivalent-diameter ratio of fluted beam', {'equivalent_diameter_ratio': '.8'}, 'dimensionless', 'Section2.1 Eq2', '0.5mm carbide tool,Al7075 workpiece;30krpm;ap.05mm,ae.3mm,fz15um', 'Equivalent cantilever force/deflection model', '0.8D is constitutive geometric closure, not a measured stiffness ratio.', level='constitutive_closure', region='PHENOMENOLOGICAL', doi='10.3390/mi8060188', transfer='REJECT_TRANSFER')
audit(MILL, 'S1', 'PMC6190321', 'CHECKED_MODEL_CLOSURE', '0.8D source model; no empirical tool stiffness implied.', ['M02_equivalent_diameter'], doi='10.3390/mi8060188')
obs('M03_runout_fit', MILL, 30400420, 'Tool diameter, channel widths and runout fits', {'tool_diameter': '802.2', 'channel_widths': ['807.2', '806.2', '806.5', '805.5'], 'test0_r0_four_fit_methods': ['8.77', '10.78', '8.43', '10.95'], 'test0_alpha_four_fit_methods': ['182.4', '183', '182.3', '183'], 'test0_gamma_four_fit_methods': ['-74', '-77.3', '-73.3', '-77.6']}, 'um', 'Tables4/5 Test0 row', 'Ti6Al4V workpiece;single Test0,4 fitting methods', 'Channel-wall-based runout inference,not mounted force-displacement measurement', 'Runout is rotating eccentricity,not bending;4 fits are not4 independent specimens.', region='PER_POINT', units={'test0_alpha_four_fit_methods': 'degree', 'test0_gamma_four_fit_methods': 'degree'}, conflicts=['The swarm tool unit .802um is wrong:802.2um=.8022mm. Alpha range omits182.3deg. WorkpieceE113.8GPa is not tool modulus.'])
audit(MILL, 'S2', 30400420, 'CORRECTED_UNIT_AND_SAMPLE_COUNT', 'Primary date24July2017 confirmed. Diameter802.2um;Test0four method fits,not independent measured tools.', ['M03_runout_fit'])
obs('M04_wear_force', MILL, 36363826, 'Test-wise inferred runout, measured flank wear,force-model errors and wear-related changes', {'test_runout': ['1.531', '1.423', '.761', '1.805', '.378', '1.617', '.220', '.671', '.336'], 'flank_wear_cut1_cut10': ['37.10', '74.15'], 'MAE_reduction_xyz': ['.12', '.22', '.15'], 'peak_force_increase_percent_xyz': ['48.2', '48.39', '209']}, 'um', 'Tables3/5;Results Figs11/13', '0.5mm carbide tool;AISI4340 workpiece;nine tests;wear cutting sequence', 'Force dynamometer/model comparison;runout estimated per test', 'Runout/wear/model-error improvements do not identify pure bending at1N.', region='PER_POINT', units={'MAE_reduction_xyz': 'N', 'peak_force_increase_percent_xyz': '%'}, conflicts=['Nine rows are tests,not nine independent tools. MAE reductions are >printed thresholds,not actual force magnitudes.'], title='Micro-milling force modeling considering tool wear')
audit(MILL, 'S3', 36363826, 'CHECKED_WITH_QUANTITY_RESTRICTIONS', 'Runout/test rows and wear verified;force-error reductions are lower bounds,not cutting forces.', ['M04_wear_force'])
OBS[-1]['value_metadata']['MAE_reduction_xyz']['relation'] = 'strict_lower_bound_on_reduction'
obs('M05_bur_wear', MILL, 41680061, 'Cutting-edge dimension and horizontal gap change over wear', {'cutting_edge_dimension_initial_final': ['776.4', '797.5'], 'horizontal_gap_initial_final': ['17.9', '52.3'], 'dimension_rho': '.802', 'horizontal_gap_rho': '.664'}, 'um', 'Abstract Results', 'Zirconia implant-supported premolar crowns;1mm milling tool', 'Tool measurement0.2mm from tip;sequential manufacture and wear', 'Correlated wear/process gap is not pure deflection or a force-displacement calibration.', region='PER_SURFACE_REGION', units={'dimension_rho': 'dimensionless', 'horizontal_gap_rho': 'dimensionless'})
audit(MILL, 'S4', 41680061, 'CHECKED_ABSTRACT', 'Dimension/gap/rho match;0.2mm datum retained.', ['M05_bur_wear'])
obs('M06_PICN', MILL, 42325545, 'Milled PICN intaglio/outer process deviations', {'PM7_intaglio_mean_SD': ['22.21', '4.31'], 'MCX5_outer_mean_SD': ['17.89', '2.76']}, 'um', 'Primary Results machine comparisons', '121 PICN premolar crowns', 'PM7 versusMCX5;manufactured crown scan comparison', 'Workpiece PICN is not polymer cutting tool;process surface deviation is not bending.', region='PER_SURFACE_REGION')
audit(MILL, 'S5', 42325545, 'CHECKED', 'Values verified;keep intaglio versus outer observation operators.', ['M06_PICN'])
audit(MILL, 'S6', 25957240, 'NO_QUOTED_NUMERIC_WEAR', 'Primary abstract identifies1/1.05mm tools,materials LavaUltimate,MarkII,Enamic. No wear/deflection outcome quoted. The swarm joins two distinct material names.')
obs('M07_Mamedov_deflection', MILL, None, 'Measured laser displacement extrapolated to tool-tip deflection range', {'X_tip_measured_range': ['-38.99', '39.34'], 'Y_tip_measured_range': ['-41', '41.81'], 'runout': '5', 'laser_distance_from_tip': '1'}, 'um', 'Printedpp149-150/PDFpp3-4 Table1,Section3.2 paragraph besideFig5', '1.5mm two-flute WC micro-endmill;Al7050 workpiece', 'MoriSeikiNMV5000DCG;20krpm;ap300um;feed20um/tooth;laser1mm from tip,extrapolated to tip', 'A genuine tool-deflection experiment now exists;different diameter/material/force regime from recipient. No pointwise force-displacement pair or1N calibration inferred.', region='PER_POINT', support='sources/Mamedov2013.pdf', doi='10.1016/j.procir.2013.06.080', url='https://cdm21054.contentdm.oclc.org/digital/api/collection/IR/id/8108/download', units={'laser_distance_from_tip': 'mm'}, verification='primary_pdf_paragraph_and_figure_visually_read_plus_original_hash', title='Machining forces and tool deflections in micro milling', conflicts=['The swarm source unverified/no PDF;primary PDF recovered. Al7050E71.7GPa belongs to workpiece,not WC tool. Third author S.EhsanLayeghK. omitted in The swarm.'])
audit(MILL, 'S7', None, 'RECOVERED_PRIMARY_MEASUREMENT', 'Primary PDF pp149-150 reports X[-38.99,39.34],Y[-41,41.81]um under specific cut;not isolated1N stiffness.', ['M07_Mamedov_deflection'], doi='10.1016/j.procir.2013.06.080', title='Machining forces and tool deflections in micro milling')
audit(MILL, 'Located ijmecsci', None, 'NO_QUOTED_NUMERIC_FACIT', 'Title located;no numerical claim quoted or primary body admitted.', doi='10.1016/j.ijmecsci.2017.12.019')
audit(MILL, 'Located inverse dynamics', None, 'NO_QUOTED_NUMERIC_FACIT', 'Dynamic/FRF stiffness is not quasistatic mounted stiffness;no quoted measurement.', doi='10.1016/j.procir.2016.04.114')
obs('M08_crown_gaps', MILL, 34771872, 'Zi/ZLS marginal/internal/absolute marginal discrepancy mean/SD', {'Zi_MG': ['37.71', '11.73'], 'Zi_IG': ['141.61', '20.92'], 'Zi_AMD': ['224.92', '7.33'], 'ZLS_MG': ['39.49', '7.42'], 'ZLS_IG': ['144.85', '21.07'], 'ZLS_AMD': ['128.13', '49.09'], 'Zi_axial_occlusal': ['68.38', '214.84'], 'ZLS_axial_occlusal': ['66.08', '225.58']}, 'um', 'Table2 materials-14-06346-t002;Results regionalgap paragraph', '32 crowns,16/material;Zi and zirconia-reinforced lithium silicate', 'Manufactured crown fit,not force-displacement', 'Fulltext fills harvest abstract gap;distinct MG/AMD/intaglio gaps retained.', region='PER_SURFACE_REGION')
audit(MILL, 'Located fit2021', 34771872, 'CHECKED_WITH_FILLED_TABLE', 'Primary fulltextTable2 numerical gaps available;do not identify bending.', ['M08_crown_gaps'])
audit(MILL, 'Located fit2025', 40274499, 'NO_QUOTED_NUMERIC_FACIT', 'Article exists;no quoted micrometre outcome in available abstract.')
audit(MILL, 'SUPPLEMENT PMMAprocessRMS', 34442120, 'CHECKED', 'Existing primaryTable1 RMS confirms recipient source;not tool deflection.', ['M01_RMS'])
write('VERIFIED_OBSERVATIONS.json', OBS)
write('SOURCE_AUDIT.json', [{k: v for (k, v) in a.items() if k not in {'verified_observation_ids', 'numeric_bundle_exported', 'new_matched_physical_calibration', 'non_admission_reason'}} for a in AD])
write('SOURCE_ADMISSION.json', AD)
write('SOURCE_ADMISSION_LOCK.json', {'sha256': sha(R / 'SOURCE_ADMISSION.json'), 'review_state': 'PENDING_INDEPENDENT_REVIEW'})
write('CURATED_SOURCE_LOCK.json', {'timestamp_utc': datetime.datetime.now(datetime.timezone.utc).isoformat(), 'sha256': {n: sha(R / n) for n in ['VERIFIED_OBSERVATIONS.json', 'SOURCE_AUDIT.json', 'PREREG_R1.json', 'PREREG_R2.json', 'PREREG_R3.json', 'PREREG_R4.json']}, 'review_state': 'PENDING_INDEPENDENT_REVIEW', 'previous_lock': 'raw/R4_PREVIOUS_CURATED_SOURCE_LOCK.json'})
dp = R.parent.parent / 'notes/expansion/src_verified_20261004.jsonl'
assert sha(dp) == read('raw/DRAFT_RECEIPT.json')['sha256'], 'External draft changed; refuse overwrite.'
shutil.copyfile(dp, R / 'raw/R4_PREVIOUS_src_verified_20261004.jsonl')
dp.write_text(''.join((json.dumps(x, ensure_ascii=False, sort_keys=True) + '\n' for x in OBS)))
write('raw/DRAFT_RECEIPT.json', {'path': str(dp), 'sha256': sha(dp), 'rows': len(OBS), 'publication': 'DRAFT_ONLY_PENDING_REVIEW'})
(R / 'raw/RELEASE_COST.json').unlink()
write('raw/R4_CURATION_RECEIPT.json', {'timestamp_utc': datetime.datetime.now(datetime.timezone.utc).isoformat(), 'observations': len(OBS), 'source_items': len(AD), 'fields': sum((len(x['values']) for x in OBS)), 'previous_observations': 51, 'new_observations': len(OBS) - 51, 'previous_versions': 'raw/R4_PREVIOUS_*'})
print(read('raw/R4_CURATION_RECEIPT.json'))
