from pathlib import Path
import json, datetime, hashlib
P = Path(__file__).resolve().parents[1]

def freeze(name, v):
    p = P / name
    if p.exists():
        raise ValueError('Already frozen')
    v['frozen_utc'] = datetime.datetime.now(datetime.timezone.utc).isoformat()
    p.write_text(json.dumps(v, indent=2) + '\n')
    p.with_suffix('.json.sha256').write_text(hashlib.sha256(p.read_bytes()).hexdigest() + '\n')
freeze('PREREG_R2.json', dict(round='R2', claim_type='information_link', capability='Calibrated observation -> absolute tooth-load interval without support stiffness', obstacle='An instrument readout labelled N need not equal applied tooth reaction', changed_operation='Carry calibration gain/offset, reference-tooth/load scope and held-out residual into absolute-force port before source identity binding', consumer='Patient FDI36 static load request and fixed100N FEM question', metrics={'relative_error_tolerance': 0.1, 'all_external_rows_required': True, 'balance_tolerance_N': 1e-07, 'injected_signal_offset_N': 100, 'decision': 'PASS only if published gain/offset correction predicts all independent applied loads within10%; otherwise preserved FAIL'}, praxis_without_new_information='Treat scanner readout labelled N as applied reaction (identity observation); engineering baseline, not claimed current clinical practice', strongest_equal_information_control='Direct affine inverse using same published gain0.48/offset-0.06; no algorithm advantage', falsifier='One applied-load row outside10%; missing patient identity/error accepted; ratio conversion incorrectly assigns source patient gain to Demo1', external_referent={'kind': 'independent_measurement', 'locator': 'https://doi.org/10.2186/jjps.38.835; Table1 p837, Eq y=0.48x-0.06 p838', 'compared_quantity': 'Applied load N versus color-scanner readout N in one subject cast, 8 lower teeth', 'refutes_us': True}, resolution='PER_TOOTH', time_scale='SIMULTANEOUS', cost={'preparation': 'transcribe48 calibration rows from primary PDF', 'fit': 'zero: use published coefficients', 'discovery': 'UNKNOWN', 'validation': '48 applied-load comparisons + injected offset', 'query': 'force port', 'fallback': 'Same-patient calibrated interval acquisition, not population gain', 'RAM_GB': 1, 'intermediates_GB': 0.01}))
freeze('DECOMPOSITION_R2.json', dict(idea='Read force through the measurement mechanism', mechanism='y=aF+b+e; solve all feasible F>=0 rather than relabel y', equation='F in hull((y+/-epsilon-b)/a) for measured a>0,b,epsilon intervals', operation='Calibration reference -> channel error -> interval inverse -> patient ID and acquisition state -> consumer', representation='PER_TOOTH channel with source-local calibration; population quantities stay POPULATION', leaves=[dict(name='y,a,b', status='EXTERNALLY_MEASURED', provenance='Hattori1994 Table1 and fitted published equation; subject cast, not Demo1', stop='Numeric table is external reference ; no demographic link available'), dict(name='residual e bound', status='UNKNOWN', stop='A reported correlation is not a uniform error bound; need repeated heldout reference loads'), dict(name='inverse interval', status='DERIVED_UNDER_ASSUMPTIONS', stop='Affine positive gain closure; analytic endpoint division, formal float enclosure not claimed'), dict(name='patient transfer', status='UNKNOWN', stop='Only matched same-subject calibration/operator and loaded pose may enter Demo1')]))
