import json, hashlib, datetime, pathlib
P = pathlib.Path(__file__).resolve().parents[1]

def save(p, x):
    p.write_text(json.dumps(x, indent=2, ensure_ascii=False, allow_nan=False) + '\n')

def freeze(name, x):
    p = P / name
    if p.exists():
        raise RuntimeError('Frozen file exists: ' + name)
    x['frozen_utc'] = datetime.datetime.now(datetime.timezone.utc).isoformat()
    save(p, x)
    p.with_suffix(p.suffix + '.sha256').write_text(hashlib.sha256(p.read_bytes()).hexdigest() + '\n')
freeze('PREREG_R1.json', dict(round='R1', claim_type='capability', capability='Patient-bound crown FDI36 candidate contact/load port in LiuHao2023Demo1 CBCT coordinates', obstacle='Bite pose, physical metric scale, uniform directed cross-jaw error, stiffness and force unmeasured', changed_operation='Reuse continuous affine all-pair minimum on this source-declared same-patient pair; retain per-face witnesses and separate virtual axial closure from acquired closed bite', consumer='FDI36 crown height +/-0.05mm and static load case', metrics={'geometry_control_tolerance_mm': 1e-07, 'injected_gap_error_mm': 0.001, 'height_edits_mm': [-0.05, 0, 0.05], 'scenario_total_force_N': [205, 1963], 'exact_summary_identity_error': 0, 'physical_PASS': 'Same-patient closed-bite pose and independently calibrated per-tooth force with finite errors must be present; otherwise UNKNOWN'}, strongest_equal_information_control='Independent six-barycentric-coordinate LP on every winning triangle pair, plus unpruned all-triangle check on FDI36 incident pairs', falsifier='LP discrepancy >1e-7mm; injected error accepted; inferred CBCT pose described as measured closed bite; population force ceiling described as patient measurement', cost={'preparation': 'read/hash27 local STLs and transforms', 'fit': 'reuse X69 no refit; upstream UNKNOWN', 'discovery': 'research reading and coding UNKNOWN', 'validation': 'all winner LP + FDI36 unpruned', 'query': '3 edits and conditional force intervals', 'fallback': 'UNKNOWN if pose/units/force absent', 'memory_limit_GB': 3, 'intermediate_limit_bytes': 3000000000}, external_referent={'kind': 'published_dataset', 'locator': 'https://doi.org/10.5281/zenodo.8027553', 'compared_quantity': 'source-paired IOS crown surfaces and CBCT reconstruction; no force truth', 'refutes_us': True}, resolution='PER_POINT', time_scale='SIMULTANEOUS'))
leaves = [('geometry', 'EXTERNALLY_MEASURED', 'Released source-derived IOS facets and FDI filenames; model file is a processed measurement, label truth UNKNOWN', 'Digital facet evaluation is sufficient for geometric query; no atomistic layer would settle bite pose'), ('coordinate map', 'CONSTITUTIVE_CLOSURE', 'X69 separately fitted rigid transforms; no independent directed error', 'Stops at missing independent correspondences, not surface-fit residual'), ('gap minimum', 'DERIVED_UNDER_ASSUMPTIONS', 'g(x,y)=z_upper(x,y)-z_lower(x,y); affine minimum on convex triangle overlap lies at a polygon vertex', 'Barycentric LP provides independent arithmetic test; float enclosure missing'), ('closure', 'CONSTITUTIVE_CLOSURE', 'upper translated -d along CBCT z; first touch d=min g; this is virtual closure only', 'Actual 6DOF bite pose is UNKNOWN; axial direction is declared scenario'), ('force', 'DERIVED_UNDER_ASSUMPTIONS', 'lambda>=0, sum(lambda)=T per jaw; incidence maps edge forces to teeth', 'Without measured T, force scale is undetermined; positive support does not give finite bounds'), ('support and sensor', 'UNKNOWN', 'PDL axial compliance, preload, observation gains, loaded jaw pose and contact map are not available for Demo1', 'Measure same-patient force and pose; population anchors cannot replace them')]
freeze('DECOMPOSITION_R1.json', dict(idea='Patient geometry must not manufacture patient force', mechanism='Contact incidence constrains load paths but leaves force scale and distribution unidentified', equations=['g_e=min_overlap(z_U-z_L)', 'g_e(h)=g_e-h for lower action tooth36', 'F_i=sum_incident lambda_e', 'sum_e lambda_e=T per jaw', 'Without T, lambda -> c lambda leaves geometry unchanged'], operation='Source-lock -> transformed faces -> continuous all-pair gap -> virtual closure -> force feasibility and height guard', representation='PER_POINT witnesses + PER_TOOTH coupled force port, unknown physical closures', leaves=[dict(name=n, status=s, provenance=p, stopping_argument=t) for (n, s, p, t) in leaves], assumptions=['Source-declared same patient; actual closed bite not established', 'STL scale interpreted mm conditionally', 'Fixed rigid axial projected contact only; no friction, rotation or 3D mechanics']))
save(P / 'CURRENT_WORK_STATE.json', dict(lane='X84-patient-bound-load', status='R1_PREREG_FROZEN', latest_gate='Physical bite/force UNKNOWN in parents', next_operation='First own continuous patient geometry measurement', updated_utc=datetime.datetime.now(datetime.timezone.utc).isoformat()))
