import json, datetime, hashlib
from pathlib import Path
P = Path(__file__).resolve().parents[1]
v = dict(round='R4', claim_type='capability', capability='Mechanically admissible exact-summary adversaries on Demo1 contact incidence', obstacle='R1 balance-only force states do not themselves establish contact equilibrium', changed_operation='Keep fixed real digital gaps and one virtual closure; construct positive independent normal contact compliances from two strictly positive force vectors, then check exact rational complementarity', consumer='Minimum measurement needed for tooth force and tooth wrench', metric=dict(summary_identity_error_N=0, exact_equilibrium_error=0, decision='Both positive compliant states have identical summary exactly; downstream difference nonzero'), strongest_equal_information_control='Exact closed-form scalar compliant-contact equations and rational residual; no algorithm contest', falsifier='Nonpositive compliance, unequal exact totals, nonzero complementarity or identical downstream observable', external_referent=dict(kind='closed_form', locator='lambda=(d-g)/c for independent positive linear normal contact compliances; source digital g from DOI10.5281/zenodo.8027553', compared_quantity='Conditional mathematical equilibrium only; no patient force facit', refutes_us=True), cost=dict(preparation='27 archived source gap witnesses', fit='None; construct two compliant worlds', discovery='UNKNOWN', validation='Exact Fraction residual and injected error', query='Two observable pairs', fallback='Measured same-patient force and centroid'), resolution='PER_POINT', timescale='SIMULTANEOUS', frozen_utc=datetime.datetime.now(datetime.timezone.utc).isoformat())
p = P / 'PREREG_R4.json'
if p.exists():
    raise ValueError('Already frozen')
p.write_text(json.dumps(v, indent=2) + '\n')
p.with_suffix('.json.sha256').write_text(hashlib.sha256(p.read_bytes()).hexdigest() + '\n')
d = dict(idea='A contact equilibrium counterexample is stronger than reaction balance alone', mechanism='Independent positive compliant normal ports; the unknown constitutive closures may differ, geometry and virtual closure stay identical', equation='g_e-d+c_e lambda_e=0, c_e=(d-g_e)/lambda_e>0', representation='Fractions of the stored binary64 gaps and integer forces; all contacts positive', leaves=[dict(name='digital gaps', status='EXTERNALLY_MEASURED', stop='Derived from released IOS geometry under candidate transform; physical gap UNKNOWN'), dict(name='positive diagonal contact compliance', status='CONSTITUTIVE_CLOSURE', stop='Hypothetical independent contact-port model; not calibrated PDL and no claim about its physiological feasibility'), dict(name='exact residual', status='DERIVED_UNDER_ASSUMPTIONS', stop='Rational arithmetic proves this scalar model only'), dict(name='patient correspondence', status='UNKNOWN', stop='No measured force/stiffness world for Demo1')])
p = P / 'DECOMPOSITION_R4.json'
p.write_text(json.dumps(d, indent=2) + '\n')
p.with_suffix('.json.sha256').write_text(hashlib.sha256(p.read_bytes()).hexdigest() + '\n')
