from common import *
p = read(P / 'PREREG_R1.json')
p.pop('frozen_utc')
p.update(round='R2', parent_prereg_sha256=sha(P / 'PREREG_R1.json'), diagnosis='First 3 R1 shells: projecting marginal vertices collapsed triangles; local closest exterior may lie behind a concave normal, making its signed distance unsuitable as wall thickness. Preserve R1. Remesh an implicit solid and measure thickness along actual normal rays.', changed_operation='Union filled voxelized complete candidate envelope with a narrow preparation-based cervical collar; subtract preparation implicit normal-corrected offset and cut at exact virtual margin, extract new shell. Normal ray casting measures outward wall intersection. Geometry is generated from public preparation and frozen participant only.', representation='Conforming implicit Boolean shell + mesh; positional normal gap and thickness rays; no projected mesh folds', cohort='Same full scored complete-crown panel, including all external-model variants and all source failures; no quality selection', uncertainty='R1 conditional physical uncertainty remains; .125 mm remeshing and trilinear preparation are numerical closures. Recompute post-adaptation source resemblance. No continuous signed-distance or physical-transfer enclosure.')
p['parameters'] = dict(p['parameters'], remesh_step_mm=0.125, collar_width_mm=0.35, collar_height_mm=0.5, gradient_floor=0.1, ray_limit_mm=20, source_shape_probes=512)
p['metrics'] = dict(p['metrics'], positive_thickness_ray_coverage_fraction=0.95, postadapt_shape_worsening_p95_mm=0.35)
p['decision'] = 'Per-crown R2 geometric pass: closed oriented positive surface, nonnegative sampled gap, p95 offset error <=.025mm, virtual finish-plane <=1e-6mm, positive rays >=.95 and postadapt resemblance worsening <=.35mm. Outer exact identity is retired because changed operation resamples the exterior; all displacement/resemblance changes reported. Do not transfer R1 label. Physical calibration remains gated by published validation and matched provenance.'
p['falsifiers'] = p['falsifiers'] + ['Ray miss is UNKNOWN, never replaced by nearest Euclidean distance or chosen thickness', 'Manufactured cement film and force are not measured by this remesh', 'Independent half-resolution/facet sampling errors are not a physical uncertainty band']
freeze(P / 'PREREG_R2.json', p)
freeze(P / 'DECOMPOSITION_R2.json', dict(parent='DECOMPOSITION_R1.json', changed_leaves=[dict(name='closed envelope', equation='phi_outer = signed EDT(fill(voxelize(candidate)))', status='CONSTITUTIVE_CLOSURE', stop_argument='Remeshing changes exterior at chosen grid; measure its effect against original source'), dict(name='cavity', equation='phi_cavity=trilinear(phi_p)-g*norm(grad trilinear(phi_p)); phi_shell=max(min(phi_outer,phi_collar),-phi_cavity,zmargin-z)', status='DERIVED_UNDER_ASSUMPTIONS', stop_argument='First-order normal offset is a construction, with no rigorous approximation enclosure; discrete closest-triangle gap gate must test it'), dict(name='wall', equation='t(x)=min{s>0:x+s*n_p intersects exterior}', status='DERIVED_UNDER_ASSUMPTIONS', stop_argument='Only sampled rays, miss retained; continuous minimum remains UNKNOWN')]))
(P / 'history/HANDOFF_R1_PILOT.md').write_text('R1 first three shells fail: collapsed marginal faces and >25um p95 gap error; closest signed exterior distance is not normal wall thickness. R1 full panel continues for retained denominator. R2 changes representation to a closed implicit Boolean solid and ray thickness, retaining the same gap tolerance. No physical model admission.\n')
state('R2_PREREG_FROZEN', 'R1 pilot geometry failed', 'R2 implicit Boolean adaptation and normal-ray wall thickness')
