from common import *
from cohort import crowns
rows = crowns()
files = set()
for r in rows:
    if r['mesh_path']:
        files.add(Path(r['mesh_path']))
    files.add(V4 / 'payload/whole_private' / r['key'] / 'reference.npz')
    files.add(V4 / 'payload/whole_private' / r['key'] / 'PROVENANCE.json')
    files.add(V4 / 'payload/whole_inputs' / r['key'] / 'preparation.npz')
files.update([V4 / 'payload/whole_inputs/RECORDS.json', V4 / 'PREREG_R3.json', V5B / 'raw/R7_CHECKPOINT.json', FC / 'rounds/R2.json', FC / 'rounds/R3.json'])
freeze(ROOT / 'PREREG_R2.json', dict(claim_type='capability', capability='Spatial contact and uncertainty query on actual complete generated crowns and measured antagonists/neighbours', obstacle='R1 roofs omit axial surfaces and nominal answers omit pose uncertainty', changed_operation='Replace roofs with final exterior triangles; derive guaranteed/possible PL band sets for +/-0.05mm gap uncertainty; compute neighbouring-surface proximity patches', consumer='Crown selection and tooth incidence/load sets', cohort=rows, metrics={**read(ROOT / 'PREREG_R1.json')['metrics'], 'grid_mm': 0.25, 'gap_uncertainty_mm': 0.05, 'neighbour_distance_band_mm': 0.1, 'numerical_control_area_mm2': 1e-07}, decision='Same spatial gates as R1, complete-shell geometry required; robust PATTERN PASS if upper symdiff<=1, FAIL if lower>1, otherwise UNKNOWN. Robust count/location not certified. Primary full-crown item is one tooth/site; common four frontier methods separately counted.', strongest_equally_informed_control='Unmodified v4 clip integration at common support; actual native tooth as self-identity check; denser .125mm panel on first site for all four frontier participants', falsifier='No complete-crown disagreement; all useful spatial comparisons disappear under uncertainty; denser sampling changes stated classification', external_referent=REFERENT, cost=read(ROOT / 'PREREG_R1.json')['cost'], limitations=['PL enclosures derived but rigorous floating-roundoff and source-mesh enclosures missing', 'Neighbour proximity unsigned; cannot certify nonpenetration', 'Native scan is reconstruction referent, not optimum', 'No manufactured crown measurement'], resolution='PER_POINT -> PER_SURFACE_REGION -> PER_TOOTH; aggregate POPULATION', time_scale='SIMULTANEOUS'))
freeze(ROOT / 'DECOMPOSITION_R2.json', dict(leaves=[dict(name='Outer shell and neighbour surfaces', status='EXTERNALLY_MEASURED', stop='Neighbour input measured; generated shell simulated. Segmentation and frame unvalidated'), dict(name='D={delta<=g<=b-delta}, P={-delta<=g<=b+delta}', status='DERIVED_UNDER_ASSUMPTIONS', stop='For any bounded additive PL gap error, D subset C subset P; not scanner accuracy'), dict(name='symmetric difference enclosure', status='DERIVED_UNDER_ASSUMPTIONS', equation='|Dp\\Pr|+|Dr\\Pp| <= |Cp xor Cr| <= min(S,|Pp|+|Pr|-2|Dp intersect Dr|)', stop='Set inclusion exact; floating integration not outward rounded'), dict(name='closest-surface neighbour distance', status='DERIVED_UNDER_ASSUMPTIONS', stop='Unsigned Euclidean geometry, no loaded pressure'), dict(name='physical observed contacts', status='UNKNOWN', stop='Same-specimen foil/pressure and pose needed')]))
freeze(ROOT / 'INPUT_LOCK_R2.json', dict(files={str(p): dict(sha256=sha(p), bytes=p.stat().st_size) for p in sorted(files)}))
freeze(ROOT / 'FROZEN_PREDICTIONS_R2.json', dict(prereg_sha256=sha(ROOT / 'PREREG_R2.json'), input_lock_sha256=sha(ROOT / 'INPUT_LOCK_R2.json'), physical_measurement='NOT_RUN', retrospective=True))
state('R2_FROZEN', 'Complete crowns, spatial gates and gap uncertainty frozen', 'Execute actual mesh geometry and neighbour queries')
