from dental_release.paths import expand as _release_expand
from common import *
import csv, gzip
state('PREREGISTRATION', 'Parents and correction reviews read', 'Freeze spatial-contact questions before executing v6 numerics')
pr = dict(claim_type='capability', capability='Determine which frozen generator proposals preserve measured-context contact pattern, beyond shared feasibility', obstacle='A binary feasibility flag and scalar contact area discard contact location and connectivity', changed_operation='Reference-owned clipped contact polygons, components, centroid and paired item decisions', consumer='DentalGenCAD level 2 and subsequent tooth-load incidence consumer', parents=[_release_expand('GENCAD_V5'), _release_expand('GENCAD_V5B'), _release_expand('FULL_CROWN'), _release_expand('FALT_TANDLAST')], cohort='Same 1728 test items and four frontier participants as v5; all failures retained. Roof tasks are not complete crowns.', metrics={'contact_band_mm': 0.1, 'symdiff_max_mm2': 1.0, 'component_count_error_max': 1, 'centroid_distance_max_mm': 0.5, 'negative_gap_area_max_mm2': 0.1, 'common_reference_support_fraction_min': 0.95, 'floating_comparison_tolerance': 1e-09}, decision='Primary L2 PASS iff L1 PASS and all nominal spatial gates pass; both empty maps have centroid distance 0, one empty map fails location; unknown support remains UNKNOWN. Count per-item disagreements, never marginal pass-rate range.', strongest_equally_informed_control='Unmodified v4 polygon contact_map and independently recomputed sampled integration; not an algorithm comparison', falsifier='No paired L2 decision differs, or independent area control fails, or coordinate/provenance mismatch', external_referent=REFERENT, uncertainty='Nominal supplied scan pose. +/-0.05 mm continuous pose enclosure is reserved for next construction. No physical confidence interval or continuous source geometry enclosure.', cost={'preparation': 'timed current input hash/read; prior preparation UNKNOWN', 'fit': 'none', 'discovery': 'wall elapsed recorded; human-equivalent cost UNKNOWN', 'validation': 'timed controls', 'queries': 'timed all rows', 'fallback': 'UNKNOWN/unscored rows retained', 'resources': '<=4 threads; CPU only; <=3GB intermediates'}, resolution={'gap': 'PER_POINT', 'polygon': 'PER_SURFACE_REGION', 'decision': 'PER_TOOTH', 'discrimination': 'POPULATION'}, time_scale='SIMULTANEOUS')
freeze(ROOT / 'PREREG_R1.json', pr)
decomp = dict(chain='idea -> preserve spatial contact -> intersect signed-gap bands -> clip barycentric triangles -> indexed polygons -> same registered frame', leaves=[dict(name='scan coordinates and archived predictions', status='EXTERNALLY_MEASURED', note='Only original coordinates measured; predictions simulated; source FDI inferred', stop='No scanner pose/contact calibration present'), dict(name='g=ceiling-roof and 0<=g<=0.1mm', status='DERIVED_UNDER_ASSUMPTIONS', stop='Vertical single-valued projection; undercuts and deformation excluded'), dict(name='band and acceptance tolerances', status='CONSTITUTIVE_CLOSURE', stop='Engineering reconstruction queries, no clinical norm'), dict(name='polygon area/centroid and connected regions', status='DERIVED_UNDER_ASSUMPTIONS', stop='Piecewise affine represented gap; floating arithmetic has no formal roundoff enclosure'), dict(name='physical loaded contact', status='UNKNOWN', stop='Needs registered loaded foil/pressure observation on same specimen')])
freeze(ROOT / 'DECOMPOSITION_R1.json', decomp)
rows = list(csv.DictReader(gzip.open(V4 / 'raw/QUALITY_ROWS.csv.gz', 'rt')))
keys = sorted({r['case_key'] for r in rows if r['split'] == 'test'})
paths = [V4 / 'raw/QUALITY_ROWS.csv.gz', V4 / 'code/quality.py', V5 / 'review_artifacts/R1B_BOUNDARY.json']
for key in keys:
    paths.extend([V4 / 'payload/public/tasks' / f'{key}.json', V4 / 'payload/private/references' / f'{key}.npz', V4 / 'payload/private/provenance' / f'{key}.json'])
    paths.extend((V4 / 'payload/predictions' / m / f'{key}.npz' for m in FRONTIER))
    paths.extend((V4 / 'payload/public/scenes').glob(key + '*.npz'))
freeze(ROOT / 'INPUT_LOCK_R1.json', dict(files={str(p): dict(sha256=sha(p), bytes=p.stat().st_size) for p in paths}))
freeze(ROOT / 'FROZEN_PREDICTIONS.json', dict(role='Existing upstream predictions frozen before new v6 scoring; retrospective data, no new physical measurement', input_lock_sha256=sha(ROOT / 'INPUT_LOCK_R1.json'), prereg_sha256=sha(ROOT / 'PREREG_R1.json')))
state('R1_FROZEN', 'Spatial thresholds and exact 1728-item cohort frozen', 'Implement and execute spatial scoring')
