from common import *
from cohort import crowns
sel = read(V4 / 'PREREG_R3.json')['selection']
files = [TAND / 'code/model.py', TAND / 'QUANTITY_LICENSE.md', TAND / 'RESULTS.md', ROOT.parent / 'LANE_X21_CONTACT_MAP/code/contact.py', ROOT.parent / 'LANE_X21_CONTACT_MAP/code/certificates.py', ROOT.parent / 'LANE_X2_OCCLUSION_B2B/raw/EXTERNAL_REFERENTS.json']
for r in sel:
    files.append(Path(r['metadata']))
    m = read(r['metadata'])
    files.extend((Path(m['arches'][j]['labels']['path']) for j in ['upper', 'lower']))
freeze(ROOT / 'PREREG_R3.json', dict(claim_type='capability', capability='For each whole crown, answer which teeth must/can/never carry axial load after replacing only that tooth in its registered full arch', obstacle='Local area/contact counts cannot identify global incidence or necessity; physical support is unknown', changed_operation='Continuous projected triangle-pair minima with rational upper witnesses and conservative box lower bounds; replace incident edges; call TANDLAST exact quantifiers on all 32 FDI slots', consumer='Crown design -> per-tooth load-set port', cohort=crowns(), selection=sel, metrics={'gap_uncertainty_mm': 0.05, 'kernel_nominal_control_mm': 1e-07, 'minimum_class_discriminating_sites': 1, 'force_total_N': [205, 1963], 'force_support': 'all k in (0,+infinity) N/mm'}, decision='Report nominal-rounded-mesh gap boxes and expanded +/-0.05mm boxes separately. For each site compare all four frontier class vectors directly. Never infer zero patient load from absent projected pair. Share hull 0..100% is not a point prediction.', strongest_equally_informed_control='Actual TANDLAST classifier and exact KKT QP replay; unpruned intersection control; independent rational witness. Standard area-share practice compared descriptively to external population force profile.', external_referent={'kind': 'independent_measurement', 'locator': ['https://doi.org/10.7144/sgf.2.111', 'https://doi.org/10.11138/ads/2017.8.2.079'], 'compared_quantity': 'Published per-tooth force-share profiles, unmatched cohorts and sensors; not individual validation', 'refutes_us': True}, falsifier='No method class-vector differences, missing/corrupt source hashes, QP KKT failure, narrow claimed physical force intervals unsupported', cost=read(ROOT / 'PREREG_R1.json')['cost'], resolution='PER_SURFACE_REGION pair minima -> PER_TOOTH load classes; POPULATION descriptive referent', time_scale='SIMULTANEOUS', physical_transfer='UNKNOWN; no rotation/friction/preload/nonlinear periodontal support'))
freeze(ROOT / 'DECOMPOSITION_R3.json', dict(leaves=[dict(name='local crown -> common arch transform', status='DERIVED_UNDER_ASSUMPTIONS', equation='Xarch=(Xlocal Rsite^T+bsite-barch) Rarch', stop='Rounded coordinates treated as exact mathematical input; anatomical orientation unknown'), dict(name='contact pair minimum', status='DERIVED_UNDER_ASSUMPTIONS', equation='min(zupper-zlower) over projected triangle intersections; lower from AABB vertical extrema, upper from exact rational witness', stop='Finest mesh triangles, no deformation or physical validation'), dict(name='axial load feasibility', status='CONSTITUTIVE_CLOSURE', equation='w=g-d+B^T C B lambda>=0; lambda>=0; lambda*w=0; sum(lambda)=T', stop='Positive finite unknown diagonal tooth compliance; friction/rotation absent'), dict(name='universal necessity', status='DERIVED_UNDER_ASSUMPTIONS', equation='min(upper gaps on incident edges)<=min(lower gaps on nonincident edges)', stop='Reuse TANDLAST proof for the same axial model; force hull infimum zero may not be attained'), dict(name='support and measured force', status='UNKNOWN', stop='Requires same-tooth loaded displacement/force acquisition; population profiles cannot substitute')]))
freeze(ROOT / 'INPUT_LOCK_R3.json', dict(files={str(p): dict(sha256=sha(p), bytes=p.stat().st_size) for p in files}))
freeze(ROOT / 'FROZEN_PREDICTIONS_R3.json', dict(prereg_sha256=sha(ROOT / 'PREREG_R3.json'), mesh_lock_sha256=sha(ROOT / 'INPUT_LOCK_R2.json'), source_lock_sha256=sha(ROOT / 'INPUT_LOCK_R3.json'), status='Predicted class fields generated subsequently before any new physical measurement; retrospective geometry comparison only'))
