import json, hashlib, datetime, pathlib
P = pathlib.Path(__file__).resolve().parents[1]

def put(name, obj):
    p = P / name
    if p.exists():
        raise RuntimeError('Frozen artifact already exists: ' + name)
    p.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + '\n')
    p.with_suffix(p.suffix + '.sha256').write_text(hashlib.sha256(p.read_bytes()).hexdigest() + '\n')
now = datetime.datetime.now(datetime.timezone.utc).isoformat()
base = dict(lane='PROOF_LANE-combine-implant-site', timestamp_utc=now, claim_type=['information_link', 'capability'], capability='A single source-bound research plan for each existing X8 site, with joint digital canal and regional envelope constraints and explicit unidentified physical outputs.', obstacle='Separate results do not share validated patient-level physical calibration. Guide sample moments and release revisions do not identify true anatomy or injury probability.', changed_operation='Join by exact case, FDI, source hash and pose; keep a vector of evidence-supported feasible sets instead of aggregating unlike risks into a score.', consumer='Prosthetics researcher selecting a falsifiable laboratory experiment; no clinical recommendation', practice='Fixed 2 mm clearance to the TF2 mask at the inherited virtual dentate pose', strongest_equally_informed_control='Independent dictionary join, direct scalar table lookup and voxel-box geometry; informational equivalence is a correctness test, not the headline comparator', falsifier='Any case/pose/hash mismatch, imputation of uncalibrated physical outputs, numerical discrepancy >1e-7 mm, or apparently complete recommendation without required joint observations.', cost=dict(preparation='record paths, bytes, hashes; manual time uninstrumented', fit='none; inherited calibrations charged and stated', discovery='timed executable phases; reasoning time UNKNOWN', validation='independent scalar/geometry controls and injected corruption', questions=0, fallback='explicit null per unavailable endpoint', threads=1, gpu=False, max_intermediates_bytes=3000000000))
r1 = base | dict(round='R1', operation='Compose all 2581 inherited sites and the dense-release/gray-profile intersection. Recompute 90/95% conditional guide-budget decisions on observed release unions, retaining per-image clusters.', metrics=dict(identity_tolerance=0, pose_tolerance_mm=1e-10, scalar_tolerance_mm=1e-10, bootstrap_replicates=2000, bootstrap_seed=20261004, CI='percentile image-cluster bootstrap, conditional descriptive dataset CI; not clinical prevalence', physical_endpoint_gate='No finite patient risk/diameter/bore/material recommendation unless matched physical reference exists', counts='unique image-group + FDI; any-pose disagreement within duplicate image aliases; retain numerator and denominator'), decision='Useful link if exact source-supported join exists; full physical plan fails if any required calibration absent; all failures preserved', external_referent=dict(kind='published_dataset', locator='../LANE_X73_CANAL_WALL_FULL/raw/LINEAGE_SITES.json', compared_quantity='Clearance to multiple published canal masks on byte-identical CBCT, not independent anatomy', refutes_us=True), sufficiency_test='Exact equal scalar clearance and guide magnitude moments with opposite signed error directions; compare downstream 2 mm event. Add directional clearance loss as smallest sufficient statistic for this fixed geometry question.')
put('PREREG_R1.json', r1)
put('FROZEN_PREDICTIONS_R1.json', dict(timestamp_utc=now, prereg_sha256=hashlib.sha256((P / 'PREREG_R1.json').read_bytes()).hexdigest(), prior_exposure='Parent aggregate reports and schemas inspected; current join not calculated; retrospective source reuse', predictions=[{'quantity': 'Patient-specific insertion torque, heat dose, interface micromotion, fatigue survival and biocompatibility', 'prediction': 'UNKNOWN without matched independent calibration'}, {'quantity': 'Digital fixed-2mm classification changes under guide budgets', 'prediction': 'Compute without claiming injury risk; no numerical success target invented'}]))
leaves = [('digital_canal', 'EXTERNALLY_MEASURED', 'Published mask occupancy, local point files and exact source hashes; stop at digital boundary, true anatomy UNKNOWN.'), ('distance', 'DERIVED_UNDER_ASSUMPTIONS', 'Minimum distance between closed finite cylinder and occupied voxel boxes; numerical bracket, formal floating-point enclosure missing.'), ('guide_error', 'CONSTITUTIVE_CLOSURE', 'Exact-population-moment assumption applied to published sample moments. No within-subject directions or tail validation.'), ('mask_spread', 'EXTERNALLY_MEASURED', 'Release revisions of the same image, not independent readers. Observed union covers these releases only.'), ('gray_to_density', 'UNKNOWN', 'Uncalibrated CBCT scale; need matched phantom and regional tissue measurement.'), ('bore_to_torque', 'UNKNOWN', 'X68 calibrated only within published PU regimes; patient transfer not identified.'), ('drill_to_heat', 'UNKNOWN', 'Mechanical work, thermal capacity, cooling operator and local history needed.'), ('load_to_fatigue', 'UNKNOWN', 'Connection-specific laboratory endpoint requires exact assembly and loading; patient force history absent.'), ('torque_to_micromotion', 'UNKNOWN', 'Net torque does not identify local contact pressure/stiffness or paired bone slip.'), ('material_to_biology', 'UNKNOWN', 'Titanium fixture, zirconia abutment and alloy discs are different components/observations.')]
put('DECOMPOSITION_R1.json', dict(idea='A joint plan is an intersection of supported constraints, not a weighted sum of reported risks.', mechanism='Local geometry determines distances; surgical pose changes geometry; drilling changes thermal/contact state; subsequent loads probe that inherited state.', equations=['d(C,U)=min_{x in C,y in U}||x-y||', 'd(C_actual,U)>=d(C_plan,U)-H(C_actual,C_plan)', 'F_joint=intersection_k F_k; if F_k unidentified, a physical joint acceptance is unidentified', 'd(C,union_i U_i)=min_i d(C,U_i)'], operation='Source/pose-bound intersection with explicit UNKNOWN ports', representation='PER_POINT voxel occupancy and gray coordinates -> PER_TOOTH queries; only consumers aggregate to POPULATION', time_scales=['Geometry/clearance SIMULTANEOUS', 'Bore/contact and heat history to healing HANDOVER', 'Load/elastic response SIMULTANEOUS', 'Wear/release to tissue response HANDOVER'], leaves=[dict(name=n, status=s, stop_argument=t) for (n, s, t) in leaves], linear_sensitivity='None reported; conditional inequalities separate from empirical calibration.'))
(P / 'CURRENT_WORK_STATE.json').write_text(json.dumps(dict(lane=base['lane'], updated_utc=now, stage='R1_FROZEN', latest_gate='Parent calibration gaps preserved', next_operation='Run identity join and first local calculation before web search'), indent=2) + '\n')
(P / 'GOAL_TO_STRESS_POINT.md').write_text('# Shared site plan\n\nA plan for length , diameter, guide, drilling , connection and material requires at the same time local anatomy, real placement errors, leg calibration, the state of the procedure and patient load. The parents share a partial picture and pose but lack common physical calibration . The stress point is that a numerically dense connection would otherwise create apparent patient measurements. First design preserves sources and support levels; the next inverts the truly observed geometrical conditions for alternative dimensions on the same pose.\n')
