"""Prepare selected existing data and freeze contracts before executing experiments."""
from dental_release.paths import expand as _release_expand
from pathlib import Path
import datetime, hashlib, json, shutil, sys
R = Path(__file__).resolve().parents[1]
D = R.parent

def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()

def save(p, x):
    p = R / p
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(x, indent=2, ensure_ascii=False, allow_nan=False) + '\n')

def freeze(p, x):
    if (R / p).exists():
        raise RuntimeError('Already frozen: ' + p)
    save(p, x)
    (R / p).with_suffix('.sha256').write_text(sha(R / p) + '\n')

def main():
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    records = []
    source = D / _release_expand('X1B')
    selected = [(source / 'FROZEN_PREDICTIONS.json', 'inputs/X1B_FROZEN_PREDICTIONS.json'), (D / 'LANE_X25_ISO14801_RAW/raw/specimens.json', 'inputs/specimens.json'), (D / 'LANE_X34_STL_DESIGN_GATE/reports/real_designgate.json', 'inputs/X34_real_designgate.json')]
    for design in ['D1', 'D2', 'D3', 'M1', 'M2']:
        for part in ['crown', 'die', 'preparation']:
            for ext in ['stl', '3mf']:
                selected.append((source / f'exports/{design}/{part}.{ext}', f'inputs/exports/{design}/{part}.{ext}'))
    for (src, dst) in selected:
        out = R / dst
        out.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, out)
        records.append(dict(source=str(src), path=dst, bytes=out.stat().st_size, sha256=sha(out)))
    save('INPUT_LOCK.json', dict(frozen_utc=now, files=records, total_bytes=sum((x['bytes'] for x in records))))
    common = dict(claim_type='capability', frozen_utc=now, consumer='Dental laboratory: preserve design identity through CAM conversion and plan a fixed experiment before specimens', parent_results=[_release_expand('X1B'), _release_expand('X34'), 'LANE_X25_ISO14801_RAW'], full_cost=dict(preparation='selected 30 existing mesh files plus 3 JSON files, hash-bound; source search and primary specification reading', fit='none', discovery='R1 positional counterexample; R2 changed region identity; fixed-horizon and two-group statistical contracts', validation='independent trimesh imports, published SciPy/statmodels controls, exact mass summation and injected faults', queries='15 mesh roundtrips and fixed-plan endpoint/power queries', fallback='refuse unsupported/remeshed/ambiguous meshes; retain early censoring as unknown; preserve all failed gates', human_discovery_time='UNKNOWN; wall timestamps and commands saved'))
    freeze('PREREG_R1.json', dict(common, capability='Region-bearing transport through facet reordering', obstacle='STL cannot carry units or regions and facet IDs are not durable', changed_operation='Positional JSON region array plus geometry/volume checks', metric=dict(name='region_disagreement_fraction', tolerance=0, decision='PASS iff zero region disagreement under unchanged-geometry reverse facet order; otherwise FAIL'), strongest_equally_informed_control='Trimesh import checks same geometry; independent geometry-attached region oracle generated before conversion', falsifier='Reversing facet order preserves geometry but moves a region', external_referent=dict(kind='published_code', locator='https://trimesh.org/trimesh.exchange.stl.html', compared_quantity='Imported unchanged triangle geometry', refutes_us=True)))
    freeze('PREREG_R2.json', dict(common, capability='Roundtrip with explicit unit, per-facet region identity, material, sinter convention and frozen prediction hash', obstacle='Facet-order sidecars silently relabel unchanged geometry; mutable metadata is detached from frozen predictions', changed_operation='One-to-one oriented triangle correspondence in physical mm plus a frozen contract digest; native 3MF triangle sets and sidecar fallback', metric=dict(max_vertex_correspondence_mm=1e-05, geometry_resolution='PER_POINT', region_mismatches=0, region_resolution='PER_SURFACE_REGION', asset_hash_mismatches_allowed='only explicit converted mode, with matching contract and independently checked geometry', decision='all 15 original meshes preserve geometry through binary STL, ASCII STL and 3MF plus published trimesh conversions; synthetic region partition recovered with zero mismatch; all declared faults refused'), strongest_equally_informed_control='Published trimesh mesh/scene import and export; own fixture is only a fault probe, never empirical facit', falsifiers=['scale/translation >1e-5 mm passes', 'missing STL unit passes', 'region swap or missing prediction file passes', '3MF transform silently ignored', 'same volume used to accept changed geometry', 'anatomical labels claimed from unclassified X1 surfaces'], external_referent=dict(kind='published_code', locator=['https://trimesh.org/trimesh.exchange.threemf.html', 'https://github.com/3MFConsortium/spec_core/blob/master/3MF%20Core%20Specification.md'], compared_quantity='Physical-coordinate triangles, unit conversion, region-set membership and independent import', refutes_us=True), exclusions=['remeshing', 'multi-object/components', 'clinical/anatomical region validation', 'CAM vendor interoperability', 'self-intersection certification', 'physical manufacture or calibrated sinter factor']))
    freeze('PREREG_STATS.json', dict(common, capability='Fixed-plan minimum specimens, conservative censored horizon risk and two-design power for binary or continuous outcomes', obstacle='Three runouts are mistaken for low risk; early censoring is mistaken for a survivor; confidence and test power are conflated', changed_operation='Invert exact binomial tail; partial-identification bound counts unknown horizons conservatively; enumerate two-sided Fisher rejection probability or noncentral-t power', metrics=dict(risk_bound_abs_tolerance=1e-10, Fisher_pvalue_abs_tolerance=1e-10, power_abs_tolerance=1e-08, sample_minimality='n passes and all preceding n in declared search fail', decision='3 survivors => upper 0.6315968501359613; <10% at95% requires29; agreement with published controls; all declared faults rejected'), strongest_equally_informed_control='SciPy binomtest exact confidence interval/binomial-CDF inversion and fisher_exact; statsmodels TTestIndPower for continuous power', falsifiers=['29 treated as 80% probability of acceptance at true risk10%', 'early censor discarded or encoded as complete', 'duplicate specimen counted', 'fixed-plan bound advertised as anytime-valid', 'binary risk effect reported without pA,pB', 'wrong risk/power value escapes independent checker'], external_referent=dict(kind='closed_form', locator=['https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/exacbici.htm', 'https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fisher_exact.html', 'https://www.statsmodels.org/stable/generated/statsmodels.stats.power.TTestIndPower.html'], compared_quantity='Exact binomial confidence limits, Fisher rejection probability and two-sample noncentral-t power', refutes_us=True), assumptions=['independent units at common prespecified load/protocol', 'fixed sample size and no optional stopping', 'no extrapolation in cycle horizon', 'binary comparison independent unpaired groups; two-sided Fisher', 'continuous comparison normal independent common-SD groups; SD/effect supplied by lab']))
    leaves = [('triangle transport', 'DERIVED_UNDER_ASSUMPTIONS', 'T_i=oriented triples in physical mm; accept iff bijection with max vertex norm<=1e-5 mm and equal labels', 'Stop at tessellation-preserving transport; remeshing needs a new surface-region representation'), ('units', 'DERIVED_UNDER_ASSUMPTIONS', 'x_mm=s_unit*x_file; STL has no intrinsic s_unit, require external assertion', 'Stop at declared unit plus geometry cross-check; original scan calibration UNKNOWN'), ('sinter factor', 'UNKNOWN', 'L_manufacturing=f*L_final; store f and geometry state; do not apply f implicitly', 'Replace by same-batch before/after sinter dimensions; no generic physical factor used'), ('anatomical regions', 'UNKNOWN', 'External face-index map required; demo source_surface is unclassified', 'Replace by lab/independent reviewer annotation at PER_SURFACE_REGION'), ('zero failures', 'DERIVED_UNDER_ASSUMPTIONS', 'P(K=0|p)=(1-p)^n; U=1-alpha^(1/n); n=min{n:U<target}', 'Stop at iid fixed horizon Bernoulli model; batch correlation and clinical mapping UNKNOWN'), ('early censored endpoints', 'DERIVED_UNDER_ASSUMPTIONS', 'k<=K<=k+u; conservative upper beta_quantile(1-alpha,k+u+1,n-k-u)', 'All latent completions bounded without censor-independence closure; stop at horizon event definition'), ('two-group binary power', 'DERIVED_UNDER_ASSUMPTIONS', 'sum_x sum_y I[p_Fisher(x,y)<=alpha] Bin(x;n,pA) Bin(y;n,pB)', 'Exact finite sample under iid unpaired groups; no load/risk closure inferred'), ('continuous power', 'CONSTITUTIVE_CLOSURE', 'T~noncentral_t(2n-2,d*sqrt(n/2)); power=P(|T|>t_(1-alpha/2))', 'Normal common-SD population closure; replace SD/distribution by pilot failure-force observations'), ('X25 observations', 'EXTERNALLY_MEASURED', 'Published per-specimen time/event at force; local rows retain exact locator', 'Stop at local independently published table; protocol gaps retained')]
    save('DECOMPOSITION.json', dict(idea='Keep prediction identity intact from design to a prospectively sized lab test', mechanism='Geometric correspondence and frozen metadata hand over specimen identity; exact probability turns requested uncertainty into sample count', equations=[a[2] for a in leaves], operation='import -> freeze -> export -> reimport -> verify -> fixed-plan sample count', representation='oriented triangles, 3MF native sets, JSON sidecar, event/time specimen table', leaves=[dict(name=n, status=s, relation=e, stopping_argument=t) for (n, s, e, t) in leaves]))
    freeze('FROZEN_PREDICTIONS.json', dict(frozen_utc=now, claim_type='capability', input_lock_sha256=sha(R / 'INPUT_LOCK.json'), predicted_R1='FAIL under facet reversal', predicted_R2='PASS for tessellation-preserving conversions, refuse changed geometry/metadata', zero_failure_upper_3=0.6315968501359613, zero_failure_minimum_n_10pct_95pct=29, R2_geometry_tolerance_mm=1e-05, real_manufacturing_measurement_performed=False, upstream_crown_predictions_sha256=sha(R / 'inputs/X1B_FROZEN_PREDICTIONS.json'), statistical_power_outputs='derived after freeze; no fitted or physically measured power claim'))
    save('CURRENT_WORK_STATE.json', dict(lane='X38-export-gate', updated_utc=now, phase='PREREG_FROZEN', latest_gate='Inputs and three contracts frozen before numerical tests', next_operation='Execute R1 order-loss experiment, then R2 and stats', threads=1, intermediate_limit_bytes=3000000000))
    print('Prepared', len(records), 'selected files;', sum((x['bytes'] for x in records)), 'bytes. Contracts frozen.')
if __name__ == '__main__':
    main()
