import json, hashlib, datetime
from pathlib import Path
H = Path(__file__).resolve().parents[1]
p = H / 'PREREG_R4.json'
x = dict(round='R4', frozen_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(), parent='R2 coarse/fine force profiles differ46.51pp in case3; source projected gaps often negative, signed penetration unverified', capability='Fixed-pose 3D surface-proximity contact witnesses, suitable for future registered force measurement', obstacle='Vertical extrema can mark deep projected overlap as contact even when sampled opposing surface points are separated in3D', changed_operation='Replace g<=h by exact unsigned point-to-opposing-triangle clearance on the same upper raster quadrature points; centroid-radius BVH screening across ALL lower triangles proves no omitted contact<=0.2mm at those sample points', equation='d(p,T)=min plane projection if barycentric inside, or closest edge segment; ||p-c_T||-r_T lower bound for exclusion', cases=list(range(1, 13)), grid_mm=0.2, bands_mm=[0.05, 0.1, 0.2], metrics=dict(query_classification_exact_on_samples='every opposing triangle not tested has lower bound>0.2mm', brute_force_nearest_parity_mm_max=1e-09, heldout_points_per_case=8, negative_projection_away_contact_reported=True, external_reference_claim='No force validation; published triangle-distance derivation and locally measured STL data'), strongest_control='Brute force every lower triangle at8deterministic sampled points/case; same raw faces, same samples, same thresholds', falsifier='Radius screen misses a triangle within0.2mm, injected999distance passes brute-force check, or unsigned clearance is mislabeled penetration/force', cost=dict(preparation='R1 raster/source decode retained; extra lower centroid/radius trees charged', fit='none', discovery='R1-R3 recorded including failures', validation='12cases×8fulltriangle oracles', queries='all saved projected upper points; max0.2band', fallback='Unsigned clearance sampling only; no signed SDF, no all-surface continuous certificate, no clinical force', disk_limit_bytes=3000000000), external_referent=dict(kind='closed_form', locator='https://www.geometrictools.com/Documentation/DistancePoint3Triangle3.pdf', compared_quantity='Exact closest point-to-triangle unsigned distance, mm', refutes_us=True), measured_geometry_referent=dict(kind='published_dataset', locator='https://ditto.ing.unimore.it/bits2bites/; raw/cases member hashes', compared_quantity='Fixed-pose opposing triangles and source surface sample coordinates', refutes_us=True))
if p.exists():
    raise RuntimeError('Frozen')
p.write_text(json.dumps(x, indent=2) + '\n')
Path(str(p) + '.sha256').write_text(hashlib.sha256(p.read_bytes()).hexdigest() + '\n')
