import json, hashlib, datetime
from pathlib import Path
R = Path(__file__).resolve().parents[1]

def save(name, x):
    p = R / name
    p.write_text(json.dumps(x, indent=2) + '\n')
    (R / (name + '.sha256')).write_text(hashlib.sha256(p.read_bytes()).hexdigest() + '  ' + name + '\n')
now = datetime.datetime.now(datetime.timezone.utc).isoformat()
save('PREREG_R1.json', dict(frozen_at=now, claim_type='capability', capability='Design-STL and repeated scans -> regional manufactured discrepancy, repeatability and registration dependence', obstacle='No scan/design measurement operator; pose can absorb deformation; CAD is not measured scanner reference', changed_operation='Rigid robust region-balanced ICP, marginal and intaglio locks; fixed design-area measurement sites; separate mean bias and within-part variance', consumer='K48 -> X1B LAB_PROTOCOL and K43 process calibration; no clinical decision', resolution=['PER_POINT', 'PER_SURFACE_REGION', 'PER_TOOTH'], timescale='HANDOVER', metrics={'rigid_recovery_rms_um_max': 2, 'known_deformation_normal_field_rmse_um_max': 8, 'registration_occlusal_difference_um_min': 10, 'pairwise_sd_identity_error_um_max': 1e-09, 'equal_summary_identity_error_um_max': 0, 'sufficiency_downstream_difference_um_min': 30, 'source_cell_reproduction_error_um_max': 0.01, 'fault_injection_all_reject': True}, decision='Each gate reported independently; physical validation UNKNOWN until independent paired raw scans exist', strongest_equally_informed_control='SciPy nonlinear least_squares rigid fit with identical sites/normals/regions and robust loss, plus closed-form Kabsch for datum/known correspondence. No method contest.', external_referent={'kind': 'independent_measurement', 'locator': 'EuropePMC local primary XML table locators; exact cells extracted before validation', 'compared_quantity': 'Published manufacturing RMS and explicitly typed precision; aggregate-only cannot validate a surface registration algorithm', 'refutes_us': True}, falsifiers=['Rigid injection exceeds 2 um', 'Known deformation field error exceeds 8 um', 'Wrong scale, corrupt regions or duplicate repeat scans accepted', 'Reported CAD deviation is called scanner bias', 'Published SD between crowns treated as repeat scan precision'], cost={'preparation': 'source search, hashes, region preparation and mesh sampling charged', 'fit': 'each registration timed', 'discovery': 'coding/reasoning wall time recorded; token cost UNKNOWN', 'validation': 'all injections/source checks timed', 'queries': 'regional summaries timed', 'fallback': 'manual landmarks + independent calibrated scan; cost UNKNOWN', 'limits': {'threads': 1, 'intermediates_max_bytes': 3000000000, 'estimated_ram_gb': 0.5}}, assumptions=['mm only; rigid fit never estimates scale', 'Design region labels frozen in face order', 'Same physical specimen for repeatability', 'Normal distance is not seated marginal gap', 'ICP local basin requires rough alignment; no global certificate', 'No rigorous pose uncertainty enclosure; linearized matrix used only for observability diagnostics']))
save('DECOMPOSITION_R1.json', dict(idea='A regional error field is the measurement state, rather than one global RMS', mechanism='Manufacture changes geometry; scan adds observation error; rigid coordinate gauge must be separated', equations={'observation': 'q_j = R_j (p + u(p)) + t_j + e_j(p)', 'alignment': 'argmin_T sum w_region rho(n^T(Tq-p)) under rigid T', 'bias': 'b_i = mean_j d_ij', 'precision': 's_i^2 = sum_j(d_ij-b_i)^2/(m-1)', 'regional': 'RMS_b = sqrt(mean_area b_i^2), s_r = sqrt(mean_area s_i^2)', 'identity': 'mean_pairs RMS(d_j-d_k)^2 = 2 mean_area s_i^2'}, operation=['area-stratified sampling of named design regions', 'robust point-to-plane fit with hard regional locks', 'exact closest-triangle evaluation at fixed design sites', 'retain signed field, Euclidean distance, coverage and transforms'], representation='PER_POINT position/normal/region/deviation/repeat identifier -> consumer aggregates', leaves=[{'name': 'SE3 rigid transform and Kabsch', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'stop': 'Coordinate operation exact up to floating point; scale deliberately excluded'}, {'name': 'Closest triangle and normal projection', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'stop': 'Exact mesh primitive; tessellation and true surface discrepancy UNKNOWN'}, {'name': 'Repeatability sample variance', 'status': 'DERIVED_UNDER_ASSUMPTIONS', 'stop': 'Independent repeats of same item; Gaussian t intervals conditional, spatial correlation not ignored via point count'}, {'name': 'Sinter direction/stretch from X14', 'status': 'CONSTITUTIVE_CLOSURE', 'stop': 'Reuse deformation operation; chosen residual stretch is synthetic, not calibrated crown shrinkage'}, {'name': 'Edge rounding', 'status': 'CONSTITUTIVE_CLOSURE', 'stop': 'Prescribed smooth displacement on marginal vertices; no measured CAM tool path'}, {'name': 'Scanner noise from X10', 'status': 'UNKNOWN', 'stop': 'X10 has aggregate source summaries not calibrated independent per-vertex noise; selected 8 um simulation must not be called measured'}, {'name': 'Independent reference and repeat raw scans', 'status': 'UNKNOWN', 'stop': 'Published group aggregates do not identify actual point fields or scanner bias'}, {'name': 'ISO scope', 'status': 'EXTERNALLY_MEASURED', 'provenance': 'https://www.iso.org/standard/68414.html ; https://www.iso.org/standard/69418.html', 'stop': 'Public scope/definitions only; full compliance not asserted'}]))
save('FROZEN_PREDICTIONS.json', dict(frozen_at=now, prereg_sha256=hashlib.sha256((R / 'PREREG_R1.json').read_bytes()).hexdigest(), predictions={'rigid_injection': 'all regional RMS <=2 um', 'deformation': 'known-alignment normal field RMSE <=8 um', 'registration': 'whole vs intaglio lock changes occlusal signed bias >=10 um on 60 um occlusal lift', 'precision_identity': 'pairwise RMS / sqrt(2) equals pooled sample s_r within 1e-9 um', 'sufficiency': 'same exact global RMS permits >=30 um different marginal consumer', 'physical_manufacturing_trueness': 'UNKNOWN; no physical paired data acquired'}, synthetic_inputs={'seed': 5501, 'repeats': 5, 'scanner_vertex_normal_sigma_um': 8, 'residual_sinter_stretch_xyz': [0.995, 1.002, 0.998], 'marginal_rounding_um': 35, 'occlusal_lift_um': 60}, note='Frozen before fixture generation or numerical exploration; published values already seen are retrospective references'))
save('CURRENT_WORK_STATE.json', dict(updated_at=now, status='R1_PREREG_FROZEN', latest_gate='not_run', next_operation='Implement CLI and independent metric controls', parent='DENT-MFG-ASBUILT-DEVIATION'))
