import json, hashlib, datetime
from pathlib import Path
now = datetime.datetime.now(datetime.timezone.utc).isoformat()
p = {'round': 'R1', 'tag': 'XBREAK-hunt-4', 'frozen_at_utc': now, 'claim_type': 'capability', 'capability': 'Give decision-compatible posterior ranges for all four joint cold/percussion results without invented conditional independence.', 'parent_goal': 'Choose only diagnostically and therapeutically relevant observations at the dental chair under unmeasured shared error and selected verification.', 'obstacle': 'Two marginal test tables discard conditional dependence and reference/target distinction.', 'changed_operation': 'Replace product likelihood by exact admissible joint contingency polytope; export opposite compatible worlds and an acquisition query.', 'consumer': 'Research-only binary reference-status classifier and acquisition planner; never treatment recommendation.', 'input': 'Primary PBRN PMC4884138 Table1 cold/percussion/reference counts only. Table2 combined results not used in R1; retained as later source cross-check.', 'metrics': {'range_width': 'max minus min conditional probability, unit probability', 'tolerance': 1e-08, 'validity': 'attainable endpoints and LP agreement <=1e-8, no missed admissible world', 'decision_gate': 'all four posterior widths <=0.10; benchmark thresholds 0.1,0.2,...,0.9 require robust sign or UNKNOWN', 'facit': 'Published combined-test Table2 is same-cohort source facit, not independent patient validation.'}, 'strongest_equally_informed_control': 'Independent eight-atom Charnes-Cooper linear-fractional program using same exact margins; naive product is current-model diagnostic only, not strongest algorithm baseline.', 'falsifier': 'Any LP endpoint differs >1e-8; any admissible world outside range; reported empirical treatment certainty from bleeding reference.', 'full_cost': {'preparation': 'Source retrieval, reading, transcription, coding; wallclock measured where possible, reasoning tokens/time UNKNOWN', 'fit': 'No fitted parameter; input marginal calibration inherited from selected cohort', 'discovery': 'All 4 patterns and 9 fixed thresholds, including failing questions', 'validation': 'Independent LP, source cross-check after R1; patient-level validation unavailable', 'questions': 'Time all interval and decision queries', 'fallback': 'UNKNOWN then seek joint observations; acquisition cost not zero, NOT_RUN if prospective'}, 'resources': {'threads_max': 4, 'rss_limit_gb': 3, 'intermediate_limit_gb': 3, 'gpu': False}, 'assumptions': ['Source counts are exact sample counts, not known population probabilities. R1 identifies empirical-compatible tables only.', 'Reference is absence of bleeding in pulp chamber, not biological vitality or treatment benefit.', 'No conditional independence. No population transport.', 'Binary mathematical action labels have scenario loss only; thresholds are benchmark values not clinical rules.']}
Path('PREREG_R1.json').write_text(json.dumps(p, indent=2) + '\n')
Path('PREREG_R1.sha256').write_text(hashlib.sha256(Path('PREREG_R1.json').read_bytes()).hexdigest() + '\n')
leaves = [('probability_atoms', 'DERIVED_UNDER_ASSUMPTIONS', 'Nonnegative eight cells sum to sample N, marginalization is linear.', 'Finite binary observables fully specified; deeper biology would change empirical target not this algebra.'), ('test_marginals', 'EXTERNALLY_MEASURED', 'PMC4884138 Table1, to extract only after freeze.', 'Counts can constrain joint sample; individual rows/conditional error mechanisms remain unavailable.'), ('dependence', 'UNKNOWN', 'No joint calibration in Table1.', 'Do not descend into unsupported nerves/apical mechanisms; retain whole admissible range.'), ('bleeding_reference', 'CONSTITUTIVE_CLOSURE', 'For this benchmark D means absent chamber bleeding.', 'Cannot equate with all-canal necrosis, irreversible pulpitis, or causal treatment utility.'), ('reference_error', 'UNKNOWN', 'No independent matched histology or error rate yet.', 'R1 will not infer it from agreement with index tests.'), ('population_transport', 'UNKNOWN', 'All subjects already scheduled for RCT.', 'No unselected sampling counts, so point posterior is not target-population probability.'), ('decision_threshold', 'CONSTITUTIVE_CLOSURE', 'False-positive loss lambda, false-negative 1 gives t=lambda/(1+lambda).', 'Benchmark t grid is not measured patient preference.'), ('sharp_extrema', 'DERIVED_UNDER_ASSUMPTIONS', 'Conditional q bounds from Frechet rectangle; linear-fractional extrema attain boundary; separately solve LP.', 'Binary finite model exhausted; floating-point residual recorded, no formal directed rounding.'), ('full_clinical_choice', 'UNKNOWN', 'Requires action-dependent outcomes and preferences.', 'Diagnosis of reference endpoint alone cannot identify potential-outcome contrast.')]
d = {'round': 'R1', 'chain': ['idea: useful choice from incomplete observations', 'mechanism: retain shared test errors', 'equations: x_dcp>=0, sum_cp x_dcp=N_d; posterior=x_1cp/sum_d x_dcp; threshold=lambda/(1+lambda)', 'operation: extrema plus witnesses', 'representation: eight counts with fixed class marginals', 'assumptions: selected empirical sample; bleeding surrogate'], 'leaves': [{'leaf': a, 'status': b, 'basis': c, 'stop_argument': d} for (a, b, c, d) in leaves]}
Path('DECOMPOSITION_R1.json').write_text(json.dumps(d, indent=2) + '\n')
state = {'tag': 'XBREAK-hunt-4', 'stage': 'R1_FROZEN_SOURCE_ACQUISITION', 'updated_utc': now, 'latest_gate': 'PREREG_R1 frozen before count extraction and numerical exploration', 'next_operation': 'Retrieve primary XML/PDF; independently transcribe Table1; run exact and LP joint bounds', 'no_subagents': True, 'clinical_recommendation': False, 'resources': p['resources']}
Path('CURRENT_WORK_STATE.json').write_text(json.dumps(state, indent=2) + '\n')
