import json, datetime, hashlib
from pathlib import Path
p = json.loads(Path('PREREG_R5.json').read_text())
p.update(round='R6', frozen_at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(), parent_artifact='raw/R5_RESULTS.json', capability='Estimate observed intraoperative fallback risk by preoperative CBCT category in trial-eligible thermally-responsive molars, rather than predicting no chamber bleeding.', obstacle='A vitality/diagnosis label and completed procedure ignore a decision-relevant transition after treatment starts.', changed_operation='Condition assignment-to-fallback transition on preoperative imaging, preserve one missing fallback CBCT; evaluate all three compatible missing allocations. Never condition a causal treatment effect on completed subgroup.', input='PMC11629050 Table4: planned-P arm completedP61 (normal34,widening17,lesion10) and switched25 (normal5,widening10,lesion9,missing1). No external diagnosis weights.')
p['metrics'] = {'tolerance': 1e-08, 'association_gate': 'Normal vs any abnormal one-sided Fisher exact p<=0.05 AND absolute fallback-risk difference>=0.15 in all three missing-CBCT allocations. This is source-cohort association only.', 'forecast_gate': 'Jeffreys-smoothed leave-one-out Brier loss reduces pooled prior-only prediction by>=5% in all three missing allocations. Internal reconstruction, not independent prospective validation.', 'uncertainty': 'Exact simultaneous95% binomial intervals for3 observed categories under IID trial patients, transportUNKNOWN.', 'holdout': 'One-at-a-time count deletion from each outcome/category, no replicated individual-data fiction.'}
p['strongest_equally_informed_control'] = 'Beta-binomial pooled rate with no CBCT uses same assigned-P outcome counts; literal count-deletion leave-one-out implementation checks aggregated identity. Standard same-information count lookup is identical, no algorithm novelty.'
p['falsifier'] = 'Missing allocation violates either frozen gate; internal forecasting presented as external validation; CBCT association presented as causal scan benefit or indication.'
p['full_cost']['fit'] = '3 category counts with Jeffreys(0.5,0.5) fixed smoothing, pooled comparator same smoothing; no tuning.'
p['full_cost']['validation'] = 'Exact Fisher and missingness bounds plus literal count-deletion LOOCV; independent clinical validation NOT_RUN.'
Path('PREREG_R6.json').write_text(json.dumps(p, indent=2) + '\n')
Path('PREREG_R6.sha256').write_text(hashlib.sha256(Path('PREREG_R6.json').read_bytes()).hexdigest() + '\n')
d = json.loads(Path('DECOMPOSITION_R5.json').read_text())
d['round'] = 'R6'
d['chain'] = ['idea: predict need for fallback before starting plan', 'mechanism: preop observation linked to intraoperative guard failure', 'equation: P(F|assigned P,G)=k_G/(n_P,G+k_G), not P(D|cold,percussion)', 'operation: condition path transition and retain missing scan outcome', 'representation: assignment/eligibility/observation/guard/final procedure are separate atoms', 'assumptions: trial association, no causal/patient transport']
d['leaves'] += [{'leaf': 'scan_x_guard_counts', 'status': 'EXTERNALLY_MEASURED', 'basis': 'Table4 published joint count of CBCT grade and completed procedure among randomized P arm.', 'stop_argument': 'Available joint patient-level link in aggregate, individual records not public; can estimate cohort association only.'}, {'leaf': 'unknown_scan', 'status': 'UNKNOWN', 'basis': 'One of25 fallback cases has no displayed CBCT category.', 'stop_argument': 'Enumerate all placements; no missing-at-random claim.'}, {'leaf': 'within_stratum_timing', 'status': 'UNKNOWN', 'basis': 'Group mean andSD times not linked to CBCT grade.', 'stop_argument': 'Knowing fallback probability does not imply branch timing independent of severity; retained for R7.'}, {'leaf': 'fixed_forecaster', 'status': 'CONSTITUTIVE_CLOSURE', 'basis': 'Jeffreys posterior predictive with0.5 pseudo-count per binary outcome; chosen before numeric comparison.', 'stop_argument': 'This smoothing is a model component, not biological law; no tuning or discovery performance claim.'}]
Path('DECOMPOSITION_R6.json').write_text(json.dumps(d, indent=2) + '\n')
