import json, datetime, hashlib
from pathlib import Path
p = json.loads(Path('PREREG_R5.json').read_text())
p.update(round='R7', claim_type='capability', frozen_at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(), parent_artifact='raw/R6_RESULTS.json', capability='Determine whether preoperative category and fallback-risk counts suffice to plan category-specific first-appointment time.', obstacle='CBCT x fallback and procedure x time moments exist, but CBCT x procedure x time is unmeasured; multiplying risk by marginal branch time invents independence.', changed_operation='Represent per-branch timing vectors with fixed sum and sample variance; pull category-average and normal-minus-lesion time contrast back as linear coefficients. Derive support intervals, build attained opposite joint timing worlds, independently optimize original timing variables.', input='Patel Table4 column-N timing closure:61 completedP and25fallback, nominal displayed means/SD (inside source rounding bands), and all4 CBCT-category counts including one missing fallback. Nominal compatible worlds suffice to refute identification; bound is not a full rounding or sampling enclosure.')
p['metrics'] = {'tolerance': 'Control endpoints1e-5min; constructed world mean/SD residual1e-8min; all times>=0.', 'first_visit_budget_scenario_min': 100, 'decision_gate': 'All3 observed-category upper time bounds<=100min AND all interval widths<=20min under stated moment/denominator closure.', 'order_gate': 'Sign of normal-minus-lesion average first-visit time must be identified in all nominal moment-compatible worlds; otherwise UNKNOWN with opposite worlds.', 'facit': 'Constructed source-moment-compatible timing arrays, not measured individual times; source-cohort branch counts are measured.'}
p['strongest_equally_informed_control'] = 'Separate scipy SLSQP optimization on original61/25 nonnegative timing variables with sum constraints and centered-squared-norm upper bound. Independent attained equality-variance worlds check sharpness. Same means,SD and counts.'
p['falsifier'] = 'Optimizer differs>1e-5min, moments differ>1e-8min, negative time, any asserted category time precision narrower than attained compatible worlds.'
p['full_cost']['discovery'] = '6 category endpoint optimizations and2 contrast endpoints; all86 timing variables each. No new biological data.'
p['full_cost']['validation'] = 'SLSQP plus explicit moment/positivity/per-category reconstruction, saved raw timing vectors.'
p['full_cost']['fallback'] = 'Already measured branch counts retained; correlation-specific times and second-appointment times UNKNOWN. No independent branch-time substitution.'
Path('PREREG_R7.json').write_text(json.dumps(p, indent=2) + '\n')
Path('PREREG_R7.sha256').write_text(hashlib.sha256(Path('PREREG_R7.json').read_bytes()).hexdigest() + '\n')
leaves = [('source_joint_branch', 'EXTERNALLY_MEASURED', 'Table4 CBCT counts by finalprocedure and protocol switched25of86.', 'Conditional time within those counts is not displayed.'), ('time_moments', 'EXTERNALLY_MEASURED', 'Table4 procedure mean/SD.', 'Assume sampleSD denominatorn-1 and columnN timing n as closures; raw individual times unavailable.'), ('moment_closure', 'CONSTITUTIVE_CLOSURE', 'For n times t>=0, sum t=nmu and sum(t-mu)^2=(n-1)s^2.', 'Display values are compatible nominal points, not exact biological parameters or distribution families.'), ('linear_pullback', 'DERIVED_UNDER_ASSUMPTIONS', 'Category average sum t/nCategory and contrast are linear functionals a·t. Center a by subtracting mean(a) inside each branch.', 'This retains correlations. E[T|category] cannot be obtained from separate branch moments without these supports.'), ('support', 'DERIVED_UNDER_ASSUMPTIONS', 'a·t=mu sum a+(a-mean a)·(t-mu); Cauchy-Schwarz bound ±s sqrt(n-1)||a-mean a||. Equality t=mu±s sqrt(n-1)(a-mean a)/norm when positive.', 'Finite Euclidean algebra exhausted. Source/timing-denominator sampling and empirical validation remain outside.'), ('physical_times', 'UNKNOWN', 'Saved equality worlds are mathematical fixtures.', 'No fictional patient times labeled measured; acquire joint panel on actualassigned patients next.'), ('treatment_utility', 'UNKNOWN', 'Time is only one decision coordinate.', 'Longterm efficacy, pain, total visits and patient preferences missing. Do not reduce treatment utility to minutes.')]
Path('DECOMPOSITION_R7.json').write_text(json.dumps({'round': 'R7', 'chain': ['idea: a useful preoperative time bound', 'mechanism: unknown timing severity correlation survives label reconstruction', 'equation: support = mu*sum(a) ± s*sqrt(n-1)*norm(a-mean(a))', 'operation: query pullback and attained witnesses', 'representation: whole joint feasible timing state by procedure, not independent interval bands', 'assumptions: positive moments/columnN/source nominal points'], 'leaves': [{'leaf': a, 'status': b, 'basis': c, 'stop_argument': d} for (a, b, c, d) in leaves]}, indent=2) + '\n')
