from pathlib import Path
import json, hashlib, datetime
R = Path(__file__).resolve().parents[1]
D = R.parents[1]

def save(name, obj):
    p = R / name
    if p.exists():
        raise RuntimeError('Already frozen ' + name)
    p.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + '\n')
    p.with_suffix('.sha256').write_text(hashlib.sha256(p.read_bytes()).hexdigest() + '\n')
now = datetime.datetime.now(datetime.timezone.utc).isoformat()
inputs = [D / 'results/LANE_X53_MILLING_TOOLS/NOMINAL_TIP_REFERENCE_CARD.json', D / 'results/LANE_X53_MILLING_TOOLS/INPUT_MANIFEST.json', D / 'results/PROOF_LANE_FULL_CROWN_R4/FROZEN_EXPORTS.json', D / 'results/LANE_X53_MILLING_TOOLS/code/collision.py', D / 'results/LANE_X49_DESIGN_GATE/code/design_gate.py']
manifest = {str(p): hashlib.sha256(p.read_bytes()).hexdigest() for p in inputs}
save('PREREG_R1.json', dict(timestamp_utc=now, claim_type='capability', capability='Exported crown -> local library tool witnesses AND maximum cutting force / maximum holder compliance satisfying explicit film-error budget', obstacle='Access and bending are separate; nominal diameter is not enough; actual neck/flutes, forces and holder are unmeasured', changed_operation='PER_POINT inverse compliance budget, same geometry both limits neck access and mechanical bending; inflate swept capsules by displacement bound', consumer='Read-only extension of X49 post-CAD design gate, X13 signed PER_POINT manufacturing-to-film handover', scope='5 crownloop exports + 3 frozen PROOF_LANE_FULL_CROWN_R4 exports, intaglio and margin samples. No manufacturing release.', input_sha256=manifest, metrics=dict(n_per_region=16, seed=89, force_N=1.0, scale_green_to_final=0.8, modulus_N_mm2=572000.0, holder_compliance_mm_N=0.001, other_geometry_error_final_mm=0.005, film_error_tolerance_final_mm=0.02, roundoff_allowance_mm=1e-06, local_required_bending_final_mm=0.005), decision_criteria=dict(inverse_algebra_abs_mm=1e-10, independent_quadrature_rel=1e-08, sufficiency_summary_identity=0.0, sufficiency_downstream_difference_min_mm=0.001, all_injected_impossible_rejected=True, physical_admission='UNKNOWN unless measured force, full assembly, runout, pose and process bounds AND whole surface coverage exist', no_pose='NOT_FOUND_ON_DECLARED_GRID, not global impossibility'), strongest_equally_informed_control='Independent SciPy quadrature of circular beam compliance and published trimesh closest-point code; verification, no method contest', external_referent_plan='After first own calculation search primary published dental milling force/deflection or geometry error with numeric table/figure locator. No claim of calibration unless quantity and assembly match.', falsifiers=['Accepted tool exceeds stock/overcut budget under frozen worst case', 'Missing force/holder metadata leads to physical PASS', 'Injected too long flexible neck is accepted', 'Region mean conceals adverse point', 'Published paired same-setup measurements outside frozen enclosure'], full_cost=dict(preparation='timed intake; prior datasets/search UNKNOWN', fit='zero; no fitted mechanics', discovery='timed local query', validation='timed quadrature/injection', questions='0; autonomous', fallback='UNKNOWN physical measurement/CAM', threads_max=4, ram_GB_max=1, gpu=0, disk_bytes_max=3000000000), resolution='PER_POINT', time_scale='HANDOVER'))
leaves = [('surface', 'Triangle geometry of final-scale crowns, local facet/region/normal', 'EXTERNALLY_MEASURED', 'Source-derived designs; not measured manufactured crowns', 'Stop at mesh since exact CAD->process correspondence is unavailable'), ('access', 'Swept capsule minimum distance to retained triangles', 'DERIVED_UNDER_ASSUMPTIONS', 'Reused X53 collision.py; EPS is floating tolerance not rounding proof', 'Stop at continuous straight translation; actual CAM/fixtures are unknown'), ('beam', 'C= integral_0^L s^2/(E I(s)) ds with s measured from loaded tip; I=pi*d(s)^4/64', 'DERIVED_UNDER_ASSUMPTIONS', 'Small-deflection Euler-Bernoulli circular beam; physical neck vs ball-center convention declared', 'Stop at homogenized circular solid; flute inertia/dynamics/shear unknown'), ('profile', 'Solid cylindrical neck plus shank; diameter bound is nominal tip diameter', 'CONSTITUTIVE_CLOSURE', 'X53 corrected tip card only; real flutes/profile UNKNOWN', 'Stop without metrology; scenario never promoted'), ('E', '572 GPa scenario from parent; typical material sheet, not certified bound', 'CONSTITUTIVE_CLOSURE', 'XBREAK SOURCE_ADMISSION_AUDIT.json', 'Stop: material batch/tool grade unknown'), ('force', '1 N transverse load', 'CONSTITUTIVE_CLOSURE', 'Declared stress test, not measured dental cutting force', 'Stop: needs same-tool dynamometer peak plus bandwidth'), ('holder', '1 um/N translational effective compliance', 'CONSTITUTIVE_CLOSURE', 'Declared scenario; spindle rotation/runout UNKNOWN', 'Stop: instrument installed assembly at contact lever arm'), ('film', 'Manufacturing normal displacement leaves a signed local geometry error as seating input', 'DERIVED_UNDER_ASSUMPTIONS', 'X13 CEMENT_FIELD_PORT: not seated-film measurement', 'Stop: actual seating/flow/topology coupling unavailable'), ('tolerance', '20 um final-scale film-error budget, 5 um geometry reserve', 'CONSTITUTIVE_CLOSURE', '20 um reused X13 experimental error criterion; no universal clinical threshold', 'Stop: lab must choose local acceptance band and error reserve'), ('enclosure', 'For bounded displacement u, distance to inflated sweep >=0 implies collision exclusion; normal stock in offset +/-|u|+e', 'DERIVED_UNDER_ASSUMPTIONS', 'Triangle inequality; analytic conditional enclosure; no rigorous floating outward rounding', 'Stop: point samples cannot establish whole-surface coverage')]
save('DECOMPOSITION_R1.json', dict(idea='Tool choice becomes a simultaneous design constraint', mechanism='Smaller radius fits details but d^-4 flexibility increases geometric error; long neck enables access but adds s^2 bending moment', equations=['I=pi*d^4/64 [mm4]', 'C_tool=sum 64*(b^3-a^3)/(3*pi*E*d^4) [mm/N]', 'e=scale*F*(C_tool+C_holder)+e_other [mm final]', 'offset=e+eps; final stock envelope [eps,2*e+eps]', 'F_max=(tolerance-2*e_other-eps)/(2*scale*(C_tool+C_holder))', 'C_holder_max=(tolerance-2*e_other-eps)/(2*scale*F)-C_tool'], operation='For every region point test geometry, then inverse compliance and expanded swept body', representation='PER_POINT rows, tool serial candidate, face id, pose, force/holder requirements, UNKNOWN debts', assumptions='Quasistatic, circular solid profile, straight approach, uniform shrink map; geometric scenarios not apparatus measurements', leaves=[dict(id=i, equation=q, status=s, provenance=p, stopping_argument=t) for (i, q, s, p, t) in leaves]))
(R / 'CURRENT_WORK_STATE.json').write_text(json.dumps(dict(lane='X89-milling-codesign', claim_type='capability', phase='R1_FROZEN', latest_gate='Prerequisites inspected; no numerical exploration yet', next_operation='First beam calculation on corrected local tool card, then external source search', updated_utc=now, review_state='PENDING_INDEPENDENT_REVIEW'), indent=2) + '\n')
(R / 'GOAL_TO_STRESS_POINT.md').write_text('Mesh → manufacture → measured local film within declared laboratory band requires geometry, tool access, load, assembly stiffness and process error simultaneously. Small tips access tight radii but bend; long necks reach a cavity but bend more. X53 supplies local access, XBREAK supplies coupled mechanics, X13 rejects mean film sufficiency, X49 supplies the consumer. The new operation exports pointwise inverse requirements and refuses a physical release without the missing measurement ports. Parent capability remains whole-crown measured fit; this round is a conditional design constraint.\n')
