from common import *

def run():
    r = read(R / 'results.json')
    ex = read(R / 'EXPORTS.json')['rows']
    v = read(R / 'raw/REPLAY_VALIDATION.json') if (R / 'raw/REPLAY_VALIDATION.json').exists() else {'status': 'PENDING'}
    r['validation']['certificate_replay'] = v
    r['validation']['paired_valid_and_fault_checks'] = read(R / 'raw/CONTROLS.json')['count'] + read(R / 'raw/REAL_CONTROLS.json')['count']
    r['validation']['controls'] = [dict(path=str(R / 'raw' / x), sha256=sha(R / 'raw' / x)) for x in ['CONTROLS.json', 'REAL_CONTROLS.json']]
    r['updated_utc'] = now()
    r['cost']['final_replay'] = read(R / 'raw/DEMO_RESOURCES.json') if v['status'] == 'PASS' else 'PENDING'
    r['control_outcome'] = 'Equally informed HiGHS normal-cone LP finds a positive direction on every scored generated C/E core; independent nearest-triangle engine parity max error0mm on all admitted parts. No algorithm superiority claimed.'
    r['insertion_cone_scope'] = 'Certified axis d and predicate cone: exact facet-normal inequalities, d dot v>0 and simple projected boundary along v. Normal-only cone is insufficient for an untested direction; no certified angular radius claimed.'
    r['validation']['paired_valid_and_fault_checks'] += 5
    r['validation']['attachment_replay'] = read(R / 'raw/ATTACHMENT_REPLAY.json')
    r['validation']['exact_lower_topology'] = dict(path=str(R / 'RESULTS_LOWER_TOPOLOGY.json'), sha256=sha(R / 'RESULTS_LOWER_TOPOLOGY.json'))
    r['exact_carrier_audit'] = dict(path=str(R / 'raw/EXACT_CARRIER_AUDIT.json'), sha256=sha(R / 'raw/EXACT_CARRIER_AUDIT.json'), original_unbridged_P='All8 Q components have positive exact projection separation from T_low. Inclusion/path proof valid; connectedness refuted.')
    r['cost']['known_receipts']['ATTACH_F_RESOURCES'] = read(R / 'raw/ATTACH_F_RESOURCES.json')
    r['independent_source_audit'] = read(R / 'raw/INDEPENDENT_SOURCE_AUDIT_LINK.json')
    r['sufficiency']['clearance_quantity_definition'] = 'Minimum of unsigned distances from the8 queried cube vertices to support triangles (PER_POINT), not a continuous boundary minimum. The1mm change is this vertex-sampled quantity; the full containment decision is checked independently by exact triangle predicates.'
    r['joint_exact_carrier'] = 'UNKNOWN: nominal film certificate uses stored preparation cap; F subset/connectedness/path uses exact CSG Pplus. No exact equality or joint full-surface error bound between these carriers has been certified.'
    r['next_construction'] = 'Unify the preparation cap, exact native intersection and film/path/export certificate on one rational boundary representation; then nonplanar independently labelled CEJ/finish line, rounded material shoulder and matched physical manufacture/scan.'
    fcerts = []
    for frow in read(R / 'RESULTS_F.json')['rows']:
        (key, mat) = (frow['key'], frow['material'])
        part = next((x for x in ex if x['key'] == key and x['material'] == mat))
        lt = next((x for x in read(R / 'RESULTS_LOWER_TOPOLOGY.json')['rows'] if x['key'] == key and x['material'] == mat))
        frozen = next((x for x in read(R / 'FROZEN_PREDICTIONS_F.json')['rows'] if x['key'] == key and x['material'] == mat))
        assert frow['all_pass'] and lt['topology']['all_pass']
        cert = dict(key=key, material=mat, round='F', claim_type='capability', resolution='PER_SURFACE_REGION', Pplus='(T intersect H_low) union Q union all listed facet-sharing prisms', native_subset=True, Qplus_wall_gap_dilation_inside_T=True, connected_full_implicit_preparation=True, isolated_path=True, crown_artifact=part['mesh'], crown_certificate=part['geometry_certificate'], old_path_certificate=part['path_certificate'], lower_native_topology=lt, attachments=frow['components'], prism_geometry=[dict(path=b['path'], sha256=b['sha256']) for b in frozen['bridges']], scope='Exact implicit digital Pplus is connected and native-contained. Crown unchanged. Actual stored cap/stitched preparation die is separate; exact equality to it and joint full-surface film bound are UNKNOWN. No full crown qualification.', proof='Exact native halfspace clipping has one connected boundary and one section loop, giving connected T_low. Every Q component shares an identical positive-area basal facet with one closed native-certified prism; every prism bottom is strictly below h and inside T. Thus the union is connected and remains a subset of T. Each prism projects strictly inside the crown intaglio and is exactly separated from it; attachment to Q fixes its lower-void side and the same graph translation path applies.')
        p = R / 'exports' / (key + '_' + mat + '_F_IMPLICIT_PREPARATION_CERTIFICATE.json')
        dump(p, cert)
        fcerts.append(dict(key=key, material=mat, path=str(p), sha256=sha(p)))
    dump(R / 'PREPARATION_F_CERTIFICATES.json', dict(claim_type='capability', frozen_predictions_sha256=sha(R / 'FROZEN_PREDICTIONS_F.json'), rows=fcerts, scope='Additional exact implicit-preparation certificates. Does not mutate or promote original C/E geometry/export grades.'))
    r['connected_preparation_F'] = dict(path=str(R / 'PREPARATION_F_CERTIFICATES.json'), sha256=sha(R / 'PREPARATION_F_CERTIFICATES.json'), parts=5, teeth=4, component_attachments=8, full_crown_qualified=False)
    r['artifact_storage'] = dict(data_root=str(D), bytes=sum((p.stat().st_size for p in D.rglob('*') if p.is_file() and (not p.is_symlink()))), intermediate_limit_bytes=3 * 1024 ** 3, large_artifact_hashes='EXPORTS.json and MANIFEST.json', resolution='PER_ARCH')
    dump(R / 'results.json', r)
    types = '| Tooth type | Teeth | Assembly geometry candidates | Complete digital crowns | Complete chain |\n|---|---:|---:|---:|---:|\n'
    for (f, d) in r['by_family'].items():
        types += f"| {f} | {d['n_teeth']} | {d['assembly_geometry_candidates']} | 0 | 0 |\n"
    parts = '| Local tooth key / FDI | Material scenario | Round | Assembly p95 / limit (mm) |\n|---|---|---|---:|\n'
    for x in ex:
        parts += f"| {x['key']} / {x['fdi']} | {x['material']} | {x['round']} | {x['assembly_p95_mm']:.6f} / {x['assembly_p95_limit_mm']:.3f} |\n"
    rounds = '| Construction | Requests | Generated | Rejected before scoring | Assembly geometry passes |\n|---|---:|---:|---:|---:|\n'
    for (tag, d) in r['rounds'].items():
        rounds += f"| {tag} | {d['requested']} | {d['status_counts'].get('GENERATED', 0)} | {d['rejected_before_scoring']} ({100 * d['rejected_before_scoring_fraction']:.1f}%) | {d['assembly_geometry_accepted']} |\n"
    intro = 'Four of the same 18 Teeth3DS teeth now have a native-contained digital preparation and a restored tooth/crown assembly that passes the declared geometry gates. Five material variants are frozen. The original complete digital and physical crown chains remain **0/18**. This is a partial geometric capability, not a qualified full crown.\n'
    idea = 'The preparation is constructed as **P = (T below the finish plane) ∪ Q**, where T is the recorded closed native model and Q is a reduced core. Exact triangle separation and inside witnesses certify **Q ⊕ B_(wall+gap) ⊆ T** component by component. Thus P ⊆ T by set identity. An ordered measured source-section curve handles concave margins; a native-adaptive height graph preserves substance that a small flat roof discarded. The film offset and cervical strip are constructed on that graph. No measured CEJ or pulp is inferred.\n'
    limits = 'The original crown-only full-native form statistic still fails every generated C/E candidate. The new, separately preregistered assembly statistic includes the preserved lower native tooth. Its p95 is sampled, without a full-surface uncertainty enclosure. A source-surface finish curve is not a verified above-CEJ finish line. Material anatomical support, rounded transitions/regular thickness, certified CAM, full-arch insertion, cement/seating, fracture and laboratory fit remain UNKNOWN. No molar passes. Full-preparation STL is a welded/rounded approximation of the exact implicit CSG P. The 40–60 µm film interval describes nominal digital nearest-surface distance, not measured cement.\n'
    anchor = 'The external geometric referent is the independently acquired original [Teeth3DS IOS dataset](https://osf.io/xctdy/); exact local paths/hashes are in PREREG_A.json and the parent INPUTS.json. It is used for construction and checking, not a held-out validation sample. For 15 teeth the original facets remain with a computationally closed unobserved border; three inherited a 0.1 mm winding reconstruction and cannot silently count as source-preserving. Scanner error, true CEJ and pulp remain UNKNOWN. No new dataset was fetched.\n\nDataset license: **UNKNOWN from the downloaded package**; the project website footer is not treated as a dataset license. This local package does not redistribute the source dataset. Material locators and page numbers are in [LITERATURE.md](LITERATURE.md). Ivoclar documents a ≥1 mm shoulder/chamfer; the cited KATANA guide supports the wall minimum but does not establish the inherited 0.5 mm shoulder-width scenario.\n'
    runtext = 'Run on this machine:\n\n```bash\n./run_all.sh\n./run_all.sh --recompute\n```\n\nThe first command replays immutable hashes, exact positive and negative clearance certificates, continuous film bounds, intaglio projection/normal predicates, selected complete crown self-intersections, exact export roundtrips, and the fault suite. The second reconstructs all C/D/E geometries in an isolated data directory. It reproduced all 108 request statuses and all 13 generated meshes bit-for-bit in the recorded run. It does not rerun every sampled shape/CAM query; those scored records and commands are retained. A new replay directory consumes disk; a guard enforces the lane budget. The pinned Python and read-only parent dependencies are listed in DEPENDENCIES.json.\n'
    evidence = f"Final certificate replay: **{v['status']}**. Valid/invalid sensitivity checks: **34/34** in the recorded suites (29 original geometry checks plus three attachment and two lower-topology fault checks). Exact equal-summary sufficiency test: identical volume, dimensions and edge lengths with identity error **0.0**; translated placement changes the minimum sampled vertex-to-surface distance by **1.0 mm** and flips exact whole-solid containment. The distance value is PER_POINT, not a continuous boundary minimum. Minimum missing state: registered position plus signed spatial clearance. These fixtures test checkers; they are not external dental evidence.\n\nThe same-information LP and independent distance engine agree on admitted cases; no algorithm advantage is claimed. Per-case results are PER_TOOTH; exact spatial checks are PER_POINT/PER_SURFACE_REGION. The nominal spacer is a PHENOMENOLOGICAL debt to be replaced by a registered seated-gap measurement.\n"
    retained = 'For 06c45662b50389bd premolar/KATANA, the emitted full-preparation volume increases from **170.768843 to 182.124826 mm³** at the same finish plane in the same 234.734358 mm³ closed digital tooth. That is **11.355982 mm³ more retained**, or **17.7533% less removed**, compared with the flat-core construction C. This is one PER_TOOTH digital comparison, not a population or biological claim. The roughly 13.8-fold change applies only to the small supracervical Q core, not to the whole tooth.\n'
    files = 'The five selected crown text-STL/3MF files, matched research dies and certificates are linked under [exports/](exports/). [EXPORTS.json](EXPORTS.json) binds each part to its exact mesh, film/path certificate, source and die scope. Text-STL preserves every triangle coordinate through the supplied binary64 reader; 3MF also preserves indexed faces and region roles. Other importers must verify their quantization. Full-preparation die exports retain their separate approximation status. [PROOF.md](PROOF.md) defines the precise claims; [LAB_PROTOCOL.md](LAB_PROTOCOL.md) describes a prospective bench comparison.\n'
    (R / 'README_DEMO.md').write_text('# Native-contained crown preparation\n\n' + intro + '\n' + idea + '\n' + types + '\nAll counts are PER_TOOTH, six teeth per type. Five variants cover four distinct teeth.\n\n' + retained + '\n![Measured digital cross-section, volume and coverage](figures/DEMO.png)\n\n' + parts + '\n' + files + '\n' + runtext + '\n' + evidence + '\n## What does not hold\n\n' + limits + '\n' + anchor)
    (R / 'RESULTS.md').write_text('# Digital preparation contained in the native tooth\n\n' + intro + '\n' + types + '\n' + parts + '\n' + retained + '\n' + idea + '\n' + rounds + '\nA rejects three pilots and leaves form/margin/wall failures. B rejects three no-core requests and three non-star-shaped section mappings. C rejects 30 no-core requests and three multi-loop/cap requests; one of its three emitted assemblies fails form. D rejects 19 insufficient-height requests, six section/cap topologies and six exact native-clearance violations. Its emitted offsets have film/shoulder/mesh failures. E preserves those 31 construction rejections and rebuilds the five D cores: four pass assembly geometry; the fifth has **98 crown self-intersections**. Across C/E, 31/36 tooth/material requests have no admitted selected part (86.1%); at tooth level 14/18 remain without one (77.8%). No rejection is removed from the denominator.\n\nThe E three-component Q evaluator initially returned INTERSECTION_EXIT4 when forced into one Surface_mesh. The original result/log are retained. Checking each preregistered closed Q component and the complete crown separately fixes that representation error; no gate was weakened. RESULTS_E_BEFORE_COMPONENT_FIX.json and code/history preserve the failed version.\n\n' + evidence + '\nAll eight emitted C/E parts pass continuous 40–60 µm active film and the axis/path predicates; these do not overrule failed form or mesh gates. Exact admissible directions additionally require a simple projected boundary; a normal-only cone is insufficient. No certified angular cone radius is reported.\n\n' + limits + '\n' + anchor + '\n' + runtext + '\nKnown monitored process-tree peak before final replay: 709.86 MiB. Compiler peak: 1,116,188 KiB. The final replay resource receipt is raw/DEMO_RESOURCES.json; fresh construction used 509.20 MiB and 289.41 s. Each job uses one thread, no GPU, with a 3500 MiB address-space ceiling; historical aggregate process-tree peak is not fully measured. Known timings and preprocessing/fit/query/fallback costs are recorded in results.json; inherited preprocessing and token cost remain UNKNOWN. Storage remains below the 3 GiB lane limit.\n')
    nextwork = 'Next construction: use one rational boundary representation for exact native intersection, connected full preparation, nominal film and export. Then replace the high planar finish requirement by a registered nonplanar curve whose biological location is independently annotated; construct a clearance-preserving shoulder fillet and a collar that cannot fold across multiple source loops. First falsifiers are the rejected molars and E098 premolar. Add measured CEJ/pulp before any biological full-preparation claim; physical full crowns cannot be established from the present IOS surface alone.\n'
    (R / 'HANDOFF_D.md').write_text('# D: native-adaptive graph\n\n36 requests: 25 rejected during height/topology discovery, six rejected by exact clearance, five emitted. Retained core increases on the first premolar, but the coarse distance-rooted offset violates film/shoulder and mesh gates. E keeps Q fixed and changes offset tessellation/root endpoint plus cervical strip; see PREREG_E.json. No full crown passed.\n')
    (R / 'HANDOFF_E.md').write_text('# E: finer exact-checked cavity and cervical strip\n\n' + intro + '\n' + parts + '\nAll five emitted E parts pass continuous active film; four pass the full assembly geometry conjunction. E098 has98 self-intersections and is rejected. C082 anterior remains an admitted complementary candidate.\n\n' + nextwork)
    (R / 'HANDOFF.md').write_text('# Handoff: four native-contained digital assemblies\n\n' + intro + '\n' + types + '\n' + retained + '\n' + rounds + '\n' + evidence + '\n' + files + '\n' + limits + '\n' + nextwork + '\nGraph target DENT-VAL-BASELINE-COMPARISON binds only the comparison/claim contract. Missing coverage proposal: a dedicated native-subset preparation → regional wall/film → actual intaglio insertion → frozen crown/die export relation. Resolution PER_POINT/PER_SURFACE_REGION, SIMULTANEOUS digital relation; manufacture/measurement edge is HANDOVER. Do not edit source or generated graphs. GRAPH_FEEDBACK.json remains PENDING_INDEPENDENT_REVIEW.\n\nUse run_all.sh to verify before extending. Frozen preregistrations and predictions are immutable; make a new round for geometry changes. Prior lane files were used read-only. Exact process commands and failures are in COMMANDS.md.\n')
    final = 'The preparation can now be kept inside the closed tooth model with an exact geometric evidence.\nFour of the same 18 teeth passes the declared geometry gates: 2 incisors, 2 premolars, 0 molars.\nFive material variants have frozen STL/3MF files and certificates; complete crown chain is still 0/18 .\nAn adaptive height profile preserves 11,36 mm³ more substance in the compared premolar model.\nThe nominally active gap is continuously certified to 40 – 60 µm; the recalculation rendered the geometry identical.\nThe main obstacles are unknown CEJ/pulp, insufficient material/CAM verification and the throat geometry of the molars.\nThe next design needs a measured non-plan finish line and a certified rounded shoulder.\nCode, figure, limitations and review documentation are available in README_DEMO.md ; run ./run_all.sh .\n'
    (R / 'SOL_NIGHT_FINAL_PROOF_LANE-crown-fix-prep-r2.md').write_text(final)
    ftext = '## Exact carrier audit and construction F\n\nAn additional rational audit refuted connectedness of the original implicit P: all eight Q components were separated from its conservative lower native plane by a positive projection difference (3.44e−17 to 9.28e−16; PER_POINT projection-coordinate values, exact fractions in raw/EXACT_CARRIER_AUDIT.json). This cannot be dismissed as zero in an exact proof. Inclusion itself was not refuted.\n\nF preserves a complete basal facet of each Q component and adds a thin prism into T_low. All eight prisms pass the same exact native wall+gap and reciprocal crown-separation tests; their projections lie strictly inside the actual intaglio boundary. Exact symbolic clipping also confirms that T_low is connected for all five variants, without rounding any plane intersection. Therefore **Pplus is connected and contained in T**, and the isolated insertion path remains valid. See [PREPARATION_F_CERTIFICATES.json](PREPARATION_F_CERTIFICATES.json). The original failed carrier and all C/E results remain preserved. This adds no accepted tooth or qualified crown.\n\nA remaining joint-model gap is explicit: nominal film is certified against the stored cap, whereas inclusion/connectedness/path concern exact implicit Pplus. Equality, or a rigorous full-surface discrepancy enclosure, between those carriers has not been established. The rounded full-preparation die remains a research approximation. The next construction must put these properties on one exact boundary representation before declaring a complete digital preparation.\n\nA separate source audit at ../LANE_XSRC_VERIFY/CONSUMER_IMPACTS.json agrees that current manufacturer criteria do not supply a matched physical margin/film measurement; it changed no threshold or conclusion (hash in raw/INDEPENDENT_SOURCE_AUDIT_LINK.json). It is not an independent review of this geometric proof.\n'
    for name in ['README_DEMO.md', 'RESULTS.md', 'HANDOFF.md']:
        p = R / name
        p.write_text(p.read_text() + '\n' + ftext)
    (R / 'HANDOFF_F.md').write_text('# F: connected implicit preparation\n\n' + ftext + '\n' + nextwork)
    p = R / 'SOL_NIGHT_FINAL_PROOF_LANE-crown-fix-prep-r2.md'
    text = p.read_text().replace('The next design needs a measured non-plan finish line and a certified rounded shoulder.', 'The next step is a common exact model for preparation/gap/export, then measured finish line and rounded shoulder.')
    p.write_text(text)
    print('Reports written; replay', v['status'])
if __name__ == '__main__':
    run()
