from common import *
result = read(ROOT / 'results.json')
review = ROOT / 'REVIEW_SNAPSHOT.json'
if not review.exists():
    review.write_bytes((ROOT / 'results.json').read_bytes())
feedback = dict(schema='dental-result-binding-v1', status='PENDING_INDEPENDENT_REVIEW', review_state='PENDING_INDEPENDENT_REVIEW', claim_type='capability', target_id='DENT-VAL-BASELINE-COMPARISON', binding_scope='Definition and conditional numerical experiment only; missing dedicated inverse-crown physical goal coverage', result_file='results/PROOF_LANE_INVERSE_CROWN/REVIEW_SNAPSHOT.json', sha256=sha(review), measured_quantity='Frozen cohort prerequisite admission; discrete whole-crown relative Weibull norm across continuous angle/m; minimum adverse spatial flaw-density contrast', units='dimensionless force ratio and density contrast; mm, mm3; seconds, MiB', uncertainty='No physical optimal-crown fracture data; no floating/continuum FE enclosure; finite support set; unknown whole hard-condition conjunction', population_regime='18 unchanged Teeth3DS tooth sites, all excluded from full physical admission; separate one STS-derived whole molar on virtual preparation, C3D4 linear perfect-tie/fixed-patch volume-flaw model', preregistered_gate='A full conjunct required; B useful ratio>1.02 FAIL; B width0.002 FAIL; C density>=2 FAIL; initial C LP check FAIL then C2 same tolerance PASS; D width0.0002 FAIL2/3', baseline='Same reference geometry; actual X60 R3/R4/R5 controls under same supports/load/m; direct FE load solve; conventional bounded LP; original Weyl bounds', outcome='NO_CERTIFIED_PHYSICAL_GAIN; CONDITIONAL_CONTINUOUS_RELATIVE_ORDER_AND_SPATIAL_PROCESS_REQUIREMENT_DELIVERED', negative_result=True, external_referent=result['external_referent'], resolution='PER_POINT tensors and flaw measure -> PER_TOOTH ratio; cohort per tooth/type', edges=result['edges'], next_operation='Same-object measured conforming prep/cement/support/contact and regional failure process; rigorous FE/rounding bounds before physical ordering')
save(ROOT / 'GRAPH_FEEDBACK.json', feedback)
files = []
for p in sorted(ROOT.rglob('*')):
    if p.is_file() and p.name not in ['ARTIFACT_MANIFEST.json', 'CURRENT_WORK_STATE.json', 'SOL_NIGHT_FINAL_PROOF_LANE-inverse-crown.md'] and ('__pycache__' not in str(p)):
        files.append(dict(path=str(p.relative_to(ROOT)), bytes=p.stat().st_size, sha256=sha(p)))
save(ROOT / 'ARTIFACT_MANIFEST.json', dict(created_utc=now(), review_state='PENDING_INDEPENDENT_REVIEW', files=files, data_files=[dict(path=str(p), bytes=p.stat().st_size, sha256=sha(p)) for p in sorted(DATA.rglob('*')) if p.is_file()], source_lock_sha256=sha(ROOT / 'INPUT_LOCK.json'), final_result_sha256=sha(ROOT / 'results.json')))
print(json.dumps(dict(result_sha256=sha(ROOT / 'results.json'), files=len(files))))
